MODFLOW-ORG/modflow6

- README.md
- code.json
- src/Solution/NumericalSolution.f90
- src/Solution/SparseMatrixSolver/ims8linear.f90
- src/Utilities/InputOutput.f90
- src/Utilities/Observation/Observe.f90
- src/Utilities/TimeSeries/TimeArraySeries.f90
- src/Utilities/TimeSeries/TimeSeries.f90
- src/Utilities/genericutils.f90
- utils/mf5to6/msvs/mf5to6.vfproj
- utils/mf5to6/pymake/extrafiles.txt
- utils/mf5to6/src/MultiLayerObsModule.f90
- utils/mf5to6/src/Preproc/Discretization3D.f90
- utils/mf5to6/src/Preproc/ObsBlock.f90
- utils/mf5to6/src/Preproc/ObservePHMF.f90
- utils/mf5to6/src/Preproc/Preproc.f90
- utils/zonebudget/pymake/extrafiles.txt
- version.txt
Refactor dclosetest and replace with IS_SAME in GenericUtilities.
Convert IS_SAME to logical function and allow passing of evaluation
value (eps). If eps is not passed then DSAME is used. Modified calls
to dclosetest to IS_SAME but did not pass an eps value (unlike what
was done previously). All tests pass so current tests are not sensitive
to a passed eps value. Need to monitor this for timeseries functionality
which used dclosetest.
> refactor(InputOutputModule): refactor dclosetest

- CONTRIBUTING.md
- README.md
- code.json
- doc/version.tex
- src/Model/GroundWaterFlow/gwf3.f90
- src/Solution/NumericalSolution.f90
- src/Utilities/version.f90
- version.txt
Small improvements to ptc to reduce the ptcdel value loaded on the
diagonal.
> perf(GwfModule): improvements to ptc

- README.md
- autotest/test_gwf_utl03_obs01.py
- code.json
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/version.tex
- src/Utilities/Observation/Obs3.f90
- src/Utilities/Observation/ObsOutput.f90
- src/Utilities/Observation/ObsUtility.f90
- src/Utilities/version.f90
- version.txt
Modified the observation process to use non-advancing output instead of
fixed length strings when writing ascii output. The previous use of
fixed length strings resulted in truncation of ascii observation output
when the product of user-specified digits + 7 and the number of
observations exceeded 5000.
Closes #54
> fix(ObsModule): implemented non-advancing output

- doc/mf6io/mf6ivar/dfn/gwf-npf.dfn
- doc/mf6io/mf6ivar/dfn/sim-nam.dfn
- doc/mf6io/mf6ivar/dfn/utl-obs.dfn
- `double` → `double precision`
- `valid_values` → `valid`
- `in_record = false` → `in_record false`
> docs(dfn): fix 3 dfn typos

- README.md
- code.json
- doc/version.tex
- pre-commit.py
- src/Utilities/version.f90
- version.txt
Update pre-commit hook to evaluate if repo is a fork of the main
repository. If it is a fork, the branch name is parsed from README.md
rather than using 'git status'. This will make pre-commit hooks work as
expected for fix-branch/pull request approach currently being used.
> docs(hooks): update pre-commit hook

- autotest/test000_setup.py
Happens on Windows only. It is only used for logging, so no functional change.
Example of issue:
```python
>>> import os
>>> os.getcwd()[:2]
'D:'
>>> os.path.relpath("C:\\tmp")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\bin\Miniconda3\lib\ntpath.py", line 586, in relpath
path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
>>> os.path.relpath("D:\\tmp")
'..\\..\\tmp'
```
And the new behavior:
```python
>>> relpath_fallback("D:\\tmp")
'..\\..\\tmp'
>>> relpath_fallback("C:\\tmp")
'C:\\tmp'
```
> test(test000_setup): fallback for when os.path.relpath throws

- autotest/test_gwf_idomain01_fail.py
- autotest/test_gwf_mvr01.py
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/ModelUtilities/Mover.f90
- src/Model/ModelUtilities/PackageMover.f90
- src/Utilities/Memory/MemoryManager.f90
With the refactoring of the memory manager, the error checking was not working in the mover package, which was relying on the memory manager to return a null pointer.  Checks are now based on whether a package has the mover option specified.  This is in reference to issue #130.
> fix(mover): added better error trapping for mover entries

- autotest/test_gwf_idomain01_fail.py
- autotest/test_gwf_returncodes.py
- src/Utilities/Sim.f90
Add mf6 return codes and command args autotest. Update return codes to
use select case.
> test(returncodes): add mf6 return codes and command args autotest

- src/Exchange/GhostNode.f90
- src/Exchange/GwfGwfExchange.f90
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3hfb8.f90
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/ModelUtilities/Xt3dInterface.f90
iasln was being passed in as iasln of the dis%con object, so it was named wrong and it was not used.  Removed so that it would help make code clearer.  Should not affect model results.
> refactor(gnc): removed iasln as it was not used and named wrong

- src/Utilities/ListReader.f90
> fix(ListReaderType): initialize attributes in declaration

- autotest/test_z03_nightly_build_largeexamples.py
- doc/mf6io/mf6ivar/dfn/sim-nam.dfn
- src/SimulationCreate.f90
- src/Utilities/Sim.f90
Error messages are stored in memory.  If something goes terribly wrong, the number of errors can be so large that memory runs out.  Limit the number of errors stored, by default, to 1000.  The user can control this maximum number by specifying MAXERRORS in the mfsim.nam options block.  Number of errors and number of errors above maxerrors are not written to mfsim.lst and to terminal.
Closes #106
> feat(maxerrors): limit the number of errors stored to maxerrors

- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/ModelUtilities/Connections.f90
- src/Model/ModelUtilities/Xt3dInterface.f90
(to prepare for the upcoming interface model) the mask allows to skip insertion and calculation of amat coefficients for certain connections.
> feat(cmask): add mask for calculation of amat terms

- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/ModelUtilities/DiscretizationBase.f90
this is a PR for issue #204 
It adds cellxy to DIS and DISV, and makes it available through a subroutine getcellxy(...). The upcoming interface model needs it to construct an interface grid (of type DISU) out of multiple discretizations, which can be either DIS, DISV, or DISU.
> Add get_cellxy procedure to DisBaseType #204

- src/Model/GroundWaterFlow/gwf3dis8.f90
- fixed how celly is determined from column numbers
>  Bugfix: cellxy in DIS

- .travis.yml
if modflow6-examples has a branch with the same name as the modflow6 branch that is being tested, then checkout that branch of modflow6-examples for the z01 autotest
> ci(.travis.yml): use change branch of modflow6-examples

- autotest/test_gwf_rch01.py
bug could not be reproduced
close #181
> test(rch): add test for reported issue #181

- src/Exchange/GhostNode.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/GroundWaterFlow/gwf3hfb8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/SimulationCreate.f90
- src/Solution/NumericalSolution.f90
- src/Solution/SparseMatrixSolver/ims8linear.f90
- src/Timing/tdis.f90
- src/Utilities/NameFile.f90
- src/Utilities/Observation/Obs3.f90
- src/Utilities/OutputControl/OutputControl.f90
- src/Utilities/TimeSeries/TimeArraySeries.f90
- src/Utilities/TimeSeries/TimeSeries.f90
added supportopenclose=.true. to many getblock calls
closes ##163
> fix(getblock): parser%getblock suppotopenclose=.true.

- doc/ConverterGuide/converter_mf5to6.tex
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/ModelUtilities/Connections.f90
- utils/mf5to6/src/MawPackageWriter.f90
* converter appears to not work for mnw2 wells that span multiple layers
* closes #185
> fix(mf5to6): fix converter for multiple mnw2 wells

- autotest/test000_setup.py
- autotest/test_gwf_disu01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/gwf-disu.dfn
- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/ModelUtilities/Connections.f90
- src/Model/ModelUtilities/DiscretizationBase.f90
* user can specify idomain for disu package
* vertical flow-through cells not supported (idomain must be 0 or 1)
> feat(disu idomain): add support for disu idomain

- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
There is good reason to read all of the static advanced package data as part of DF rather than as part of AR.  This will allow this information to be available earlier in the program so that a transport model, for example, has access to it early on.
> refactor(advanced packages): read static data as part of df()

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/gwf-lak.dfn
- src/Model/GroundWaterFlow/gwf3lak8.f90
* User-specified values for RAINFALL, EVAPORATION, RUNOFF, INFLOW, and WITHDRAWAL must be positive.  The program worked if these values were negative, but that doesn't necessarily make sense and is probably an input error.
* Updated definition file to reflect these changes
* Corrected minor typo in lake definition file
* Updated release notes to reflect this change
* Close #287
> fix(lak): added sign checks for user specified lak flow terms

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3dis8.f90
Code was incorrectly calculating cell center elevations when nozee was .false.  This error would have affected XT3D simulations with unconfined flow and non-zero values specified for ANGLE2 in the NPF Package.  It also would affect dispersive transport with XT3D for unconfined conditions.
> fix(dis): corrected connection vector error in DIS package

- src/Model/GroundWaterFlow/gwf3sfr8.f90
> fix(sfr): Remove upstream_fraction check from PACKAGEDATA block

- autotest/test_gwf_csub_sk01.py
- src/Model/GroundWaterFlow/gwf3csub8.f90
DNODATA values reported if 1) delay interbed observations are specified
and no delay interbeds are specified and 2) interbed observations are
specified and the number of interbeds is zero.
closes #298
> fix(csub): Allow interbed observations when no interbeds specified

- doc/Common/gwf-csubobs.tex
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Utilities/Constants.f90
- src/Utilities/Observation/Obs3.f90
- src/Utilities/Observation/Observe.f90
> fix(csub): Add additional inelastic- and elastic-compaction-cell obs.

- distribution/mkdist.py
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/mf6core.f90
* update mkdist.py to copy additional MSVS solutions and projects
> refactor(src): remove unused variables

- autotest/test_gwf_csub_sub01.py
- autotest/test_gwf_mvr01.py
- autotest/test_gwf_npf03_sfr.py
- doc/mf6io/mf6ivar/dfn/gwf-csub.dfn
- doc/mf6io/mf6ivar/dfn/gwf-lak.dfn
- doc/mf6io/mf6ivar/dfn/gwf-sfr.dfn
- doc/mf6io/mf6ivar/dfn/gwf-uzf.dfn
- doc/mf6io/mf6ivar/md/mf6ivar.md
- doc/mf6io/mf6ivar/tex/gwf-csub-desc.tex
- doc/mf6io/mf6ivar/tex/gwf-csub-options.dat
- doc/mf6io/mf6ivar/tex/gwf-lak-desc.tex
- doc/mf6io/mf6ivar/tex/gwf-lak-options.dat
- doc/mf6io/mf6ivar/tex/gwf-sfr-desc.tex
- doc/mf6io/mf6ivar/tex/gwf-sfr-options.dat
- doc/mf6io/mf6ivar/tex/gwf-uzf-desc.tex
- doc/mf6io/mf6ivar/tex/gwf-uzf-options.dat
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/NumericalModel.f90
- src/Solution/NumericalSolution.f90
- src/Utilities/Constants.f90
- src/Utilities/Table.f90
> feature(ims): add additional solver output

- doc/Common/obstypetable.tex
- msvs/mf6core.vfproj
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/GroundWaterFlow/gwf3obs8.f90
- src/Utilities/Budget.f90
- src/Utilities/BudgetObject.f90
* implemented table writer for mvr flows
* turned on fpp preprocessing in vfproj for compilerversion.fpp
* modifed obs table header in tex file
* minor changes to budget and budgetobject to support transport
> refactor(misc): bringing in changes made on transport branch

- src/Exchange/GwfGwfExchange.f90
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3mvr8.f90
* refactoring of the budget object resulted in an unassociated dis object when writing flows for exchange water mover
* dis is no longer optional for mvr_cr()
* closes #423
> fix(exg-mvr): dis object not associated for binary save flows

- src/Model/GroundWaterFlow/gwf3sfr8.f90
Initialize diversion flow (divflow) to zero in the event that they are
not defined in the first stress period.
> fix(sfr): fix error in upstream factor check with diversions

- autotest/test_gwf_npf03_sfr.py
- autotest/test_gwf_ts_sfr01.py
- src/Solution/NumericalSolution.f90
Refactor iteration total for time step and simulation to clarify
data stored in these variables. Updated test_gwf_npf03_sfr.py and
test_gwf_ts_sfr01.py to output inner and outer iteration convergence
information to listing and csv files for evaluation of proper output.
Also evaluated results for test_gwf_npf02_rewet.py autotest since it
has more than 1 time step.
Closes #410
> fix(NumericalSolution): add counter for time step iteration total

- src/Exchange/BaseExchange.f90
- src/Exchange/NumericalExchange.f90
- src/Model/BaseModel.f90
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/NumericalModel.f90
- src/Solution/NumericalSolution.f90
- src/Utilities/Memory/MemoryManager.f90
- src/mf6core.f90
* we refactored the model_ad and exchange_ad calls for bmi, but these changes broke transport.  
* allocate auxname to size 0 and then reallocate when auxiliary detected
> refactor(model_ad): revert the model advance back to numerical model

- src/Solution/NumericalSolution.f90
- src/mf6core.f90
- srcbmi/mf6ami.f90
- srcbmi/mf6bmi.f90
- Finished refactoring, considering the work in #462
- renaming: prepare_iteration, ... now is prepare_solve, solve, finalize_solve
- style: prepare_timestep becomes prepare_time_step etc.
- add safety check no to use the subcomponent concept of AMI in combination with multiple solution groups: this is not supported (yet)
Note: the python BMI/AMI wrapper (https://github.com/mjr-deltares/modflow6-bmipy) will be updated accordingly
> Further refactoring BMI for upcoming release

- srcbmi/mf6bmi.f90
Previously we used the 'save' attribute to allocate the memory and
persist over the call to the routine.
This is not fool proof (multiple calls before using the results will mess things up).
After this commit, the caller has to allocate the appropriate memory,
similar to get_var_shape.
Note: This commit also includes whitespace & line ending fixes.
Unfortunately I found no good way to entangle this afterwards...
> refactor(bmi): refactor grid routines

- .gitignore
- src/Model/ModelUtilities/BoundaryPackage.f90
Since tomvr flows are lagged by one non-linear iteration it is possible
for tomvr to be numerically greater than the calculated boundary
discharge. This can result in small positive values in the lst budget
when there should not be (for example, with the drn package). Add
check for tomvr/rrate ratio > 1. In this case, set rrate to 0 so that
the budget error is correctly accounted for the the lst budget.
> fix(BndType): fix issue with boundary rates when mvr package in use

- src/Model/NumericalModel.f90
- src/Utilities/Memory/MemoryManager.f90
@mjr-deltares  and I pair-programmed in order to find out why https://github.com/MODFLOW-USGS/modflow6/pull/492 broke our scripts.
This PR solves a few smaller problems and lets our scripts run, but leaves the bigger problem untouched.
The discussion of this one might be more suitable for a separate meeting.
- BaseModelType will be deallocated last
- Specify optional arguments in mem_deallocate
(this is only a workaround for a bigger problem)
- Fix typo: name -> name2
> Refactor model_da and fix typo

- autotest/test_gwt_prudic2004t2.py
- autotest/test_gwt_prudic2004t2fmi.py
- autotest/test_gwt_ssm01fmi.py
* Found that adding under_relaxation='DBD' and under_relaxation_theta=0.7 to transport IMS solution allowed simulation to easily converge so that the simulation continue_=True setting could be switched to False.
> test(convergence): ensure transport simulations converge

- autotest/targets.py
- autotest/test_gwt_mt3dms_p01.py
- src/Exchange/GwfGwtExchange.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
Data for calculating normal vector and unit vector components are
not available with DISU grids if VERTEX data are not specified.
Also modified GWF-GWT exchange to reset integer flag to calculate
specific discharge data (icalcspdis=1) only if the GWT dispersion
package is on. Previously, the specific discharge integer flag was
reset to 1 anytime the GWF-GWT exchange was used. This resulted in
segfault issues for DISU models without VERTEX data but only used
advection (ADV).
> fix(gwt): fix error when using gwt and disu when vertices not specified

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/ModelUtilities/Xt3dInterface.f90
Fixed error in Newton correction for XT3D; qrhs should not have been subtracted back out. Affected only simulations that used NEWTON with XT3D RHS.  Array qrhs no longer needed, so removed from code.
> fix(xt3d): removed inappropriate subtraction of qrhs from rhs in xt3d_fn

- doc/mf6io/mf6ivar/dfn/gwf-disu.dfn
- doc/mf6io/mf6ivar/dfn/gwf-disv.dfn
- doc/mf6io/mf6ivar/dfn/gwt-disu.dfn
- doc/mf6io/mf6ivar/dfn/gwt-disv.dfn
FloPy was updated to better support plotting and export for unstructured grid models.  The numeric index tag was added to the vertex numbers for the disu package so that flopy would know that they are numeric indices that flopy should convert to and from zero-based values.
> doc(dfn): small changes to dfn for flopy disu support

- autotest/test_gwf_uzf_gwet.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
Includes a new autotest to ensure that actual ET does not exceed potential ET for each row-column index in the test model domain
fixes #605
> fix(uzf): clean-up of gwet calculations in the uzf package

- autotest/test_gwf_csub_wtgeo.py
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
Add water compressibility directly to delay bed flow equation formulation instead of calculating after delay bed solution.
> feat(csub): add initial support for water table conditions in delay interbeds

- src/Utilities/Memory/MemoryManager.f90
Fix the memory table that is printed to end of mfsim.lst.  This is likely a recent bug that was not present in previous distribution.
> fix(memory): memory_print_option ALL table had remnants of memaccess

- msvs/mf6bmi.vfproj
- src/Utilities/Memory/MemoryHelper.f90
- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiError.f90
- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.f90
- implemented error module (e.g. xmipy can now get the last error to provide the user with diagnostics)
- add get_component_name
- add error messages throughout the BMI and XMI
- prevent MODFLOW from crashing on invalid address strings passed in through the BMI functions
> Enhancing diagnostics in BMI

- autotest/test_z02_nightly_build_mf5to6.py
- src/Utilities/Memory/MemoryList.f90
- src/Utilities/TimeSeries/TimeSeries.f90
- src/Utilities/TimeSeries/TimeSeriesRecord.f90
- utils/mf5to6/src/Auxiliary.f90
- utils/mf5to6/src/CharacterContainer.f90
- utils/mf5to6/src/ChdPackageWriter.f90
- utils/mf5to6/src/ChdType.f90
- utils/mf5to6/src/ExchangeWriter.f90
- utils/mf5to6/src/Lake.f90
- utils/mf5to6/src/LakeConnection.f90
- utils/mf5to6/src/LakeOutlet.f90
- utils/mf5to6/src/LakeTributary.f90
- utils/mf5to6/src/Model.f90
- utils/mf5to6/src/ModelPackage.f90
- utils/mf5to6/src/Mover.f90
- utils/mf5to6/src/Preproc/FileList.f90
- utils/mf5to6/src/Preproc/Preproc.f90
- utils/mf5to6/src/SfrDiversion.f90
- utils/mf5to6/src/SfrPackageWriter.f90
- utils/mf5to6/src/SfrReach.f90
- utils/mf5to6/src/SfrSegment.f90
- utils/mf5to6/src/SimFileWriter.f90
Initilization to null() to determine if the intermittent mf5to6 CI
segfault errors can be eliminated.
> refactor(mf5to6): initialize local class(*) to null()

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3uzf8.f90
Clean redo of #660 that now includes fixes from #662
> fix(uzf): set proper iuzno index for water-content observation type

- src/Model/GroundWaterTransport/gwt1fmi1.f90
- src/Model/NumericalPackage.f90
- src/Utilities/Constants.f90
- utils/mf5to6/src/MF2005/pcgn2.f90
- utils/mf5to6/src/ModelConverter.f90
- utils/mf5to6/src/Mover.f90
- utils/mf5to6/src/OutputControlWriter.f90
- utils/mf5to6/src/Preproc/FileList.f90
- utils/mf5to6/src/Preproc/GlobalVariables.f90
- utils/mf5to6/src/Preproc/ObsBlock.f90
- utils/mf5to6/src/Preproc/SimPHMF.f90
Compiling with gfortran's -Wcharacter-truncation option, the following warnings appear:
```
/home/mtoews/src/modflow6/src/Model/NumericalPackage.f90:259:43:
varname = adjustl(varinames(j))
1
Warning: CHARACTER expression will be truncated in assignment (16/24) at (1) [-Wcharacter-truncation]
/home/mtoews/src/modflow6/src/Model/NumericalPackage.f90:261:38:
varname = adjustl(tags(j))
1
Warning: CHARACTER expression will be truncated in assignment (16/24) at (1) [-Wcharacter-truncation]
/home/mtoews/src/modflow6/src/Model/GroundWaterTransport/gwt1fmi1.f90:916:27:
pname = keyword
1
Warning: CHARACTER expression will be truncated in assignment (16/300) at (1) [-Wcharacter-truncation]
/home/mtoews/src/modflow6/src/Model/GroundWaterTransport/gwt1cnc1.f90:480:39:
tslink%Text = 'CONCENTRATION'
1 …
```
> fix(warnings): resolve character truncation warnings

- .gitignore
- autotest/test_gwf_libmf6_sto01.py
- autotest/test_z01_testmodels_mf6.py
- msvs/mf6core.vfproj
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/ModelUtilities/GwfStorageUtils.f90
- src/Model/ModelUtilities/StorageBase.f90
Use Ss and Sy directly in storage calculations. Eliminates need for
handlers to update sc1 and sc2.
> refactor(STO): replace sc1 and sc2 arrays with ss and sy arrays

- autotest/common_regression.py
- autotest/simulation.py
- autotest/test_z01_testmodels_mf6.py
- autotest/test_z02_testmodels_mf5to6.py
- autotest/test_z03_largetests.py
- src/Solution/NumericalSolution.f90
- src/Solution/SparseMatrixSolver/ims8linear.f90
Previous changes to address issue 655 are not necessary as a result
of changes to linear accelerators to trap potential divide by zero
errors and exit the linear iteration loop. Partial refactor of
comments in ims8linear.f90 to be consistent with rest of MODFLOW 6 code.
Added some doxygen comments to ims8linear.f90.
> fix(NumericalSolution): revert fix for issue 655

- src/Utilities/SmoothingFunctions.f90
The optional `ta` argument was not properly processed in functions `sSlope` and `sSlopeDerivative`.
These functions are not used anywhere else in the codebase.
> fix(SmoothingFunctions): process optional ta in sSlope and sSlopeDerivative

- autotest/test_gwf_lak01.py
- src/Model/GroundWaterFlow/gwf3evt8.f90
- src/Model/GroundWaterFlow/gwf3rch8.f90
When a lake is active and above a vertically connected GWF cell, recharge and evapotranspiration are automatically set to zero.  Although the rates are zero in the solution, the budget terms were not set to zero.  This fix ensures that the rates are set to zero in the budget terms and adds a test.
> fix(lak): set rch/evt flows to zero for overlying lake

- autotest/test_gwf_uzf_wc_output.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/gwf/binaryoutput.tex
- doc/mf6io/mf6ivar/dfn/gwf-uzf.dfn
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
- src/Utilities/SmoothingFunctions.f90
- Adds 'wc' keyword to UZF `OPTIONS` block
- New binary output file records mean water contents for every UZF object
- Includes new autotest that compares MODFLOW6/UZF6 output to MFNWT/UZF1 output recorded in the MT3D linker file (written by LMT package)
- Updates UZF definition file (.dfn) for supporting new binary output file with flopy
- Records these updates in the releaseNotes.tex file
> feat(uzf): new uzf output option - mean water content for all objects

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/gwf-disu.dfn
- doc/mf6io/mf6ivar/dfn/gwt-disu.dfn
- src/Model/GroundWaterFlow/gwf3disu8.f90
* Close #674
* Add new VERTICAL_OFFSET_TOLERANCE option to DISU options block
*  Cell thickness was being checked for all idomain values; now check is only performed for cells with idomain = 1
> refactor(dis): allow user to specify tolerance in top/bot check for disu

- autotest/test_gwf_lakobs01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3lak8.f90
- Addresses #534
- Includes autotest that generates error message, asserts that error occurred, then fixes error in lak.obs input file and reruns model successfully
- Release notes updated
> fix(lakobs): throw error if ID2 missing when ID is integer

- src/Model/GroundWaterFlow/gwf3uzf8.f90
* final part of uzf refactor to allow uzf multiple uzf_solve() calls without advancing the state.  This is being implemented as a precursor to ATS compatibility.  This approach does require one extra uzf_solve() in ot() in addition to cq(), but this should not drastically affect runtime as most of the work will be the uzf_solve() calls during the non-linear picard iterations.
> refactor(uzf): advance uzf waves to new state in ot instead of cq

- autotest/test_gwt_fmi01.py
- src/Model/GroundWaterTransport/gwt1fmi1.f90
* With recent BD refactoring, the residual is now stored in the diagonal position of the GWF flowja array.  The previous code that was added to FMI to calculate the flow residual can now be eliminated.  This may offer performance benefits and should not have any effect on the simulation results.
> refactor(fmi): use residual in flowja instead of recalculating

- src/Utilities/Message.f90
- src/Utilities/Sim.f90
- src/mf6core.f90
Running two simulations, one after the other, with the same dll was causing exceptions. This should fix it. (NB: we didn't have that at hand before the API)
(cherry picked from commit 0fec1a772c8dd82d5c45a9d387bdff2c6c6a6e92)
> Messaging facility has a state that requires initialization.

- autotest/test_gwf_multimvr.py
There was no test for when a multi-model simulation invokes simulation-level and gwf-level MVRs.  This test uses a modified version of the LGR problem (Mehl and Hill, 2013; problem 3) that keeps the original simulation level MVR for transferring flow between SFR reaches residing in the parent and child models, but adds two WEL->SFR MVR connections at the GWF-level - one in the parent model and one in child model.  In this way, this test invokes three instances of the MVR package.  In addition, an SFR-to-SFR connection was established in the parent model that uses two scenarios to test a 50/50 and 75/25 transfer of the total flow between reaches whereby the GWF and simulation MVRs are sharing the transfer.  The image below attempts to depict where the changes in the flow model were made.
> test(mvr): New test for simultaneous usage of sim- and gwf-level MVRs

- src/Model/GroundWaterTransport/gwt1mst1.f90
Fix indexing error that would have resulted in a mismatch of budget table names
> fix(MST): fix budget table labels for sorption and decay

- src/Utilities/InputOutput.f90
* Close #720
* Fix problem using large binary flow files as input to transport model
> fix(io): fseek needs an 8 byte integer to store file position

- autotest/get_build_exes.py
- autotest/test_gwf_multimvr.py
- src/Model/GroundWaterFlow/gwf3oc8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
- src/Model/GroundWaterTransport/gwt1oc1.f90
- src/Utilities/OutputControl/OutputControl.f90
- src/Utilities/OutputControl/OutputControlData.f90
- src/Utilities/OutputControl/PrintSaveManager.f90
* Output control was not correctly determining if it was the end of a stress period for ATS simulations
* Output control now uses tdis%endofperiod to determine if last time step of stress period instead of kstp == nstp(kper)
* Close #764 
* Update to doxygen comments for output control modules
* Remove two unused UZF variables
> fix(oc): output control correctly determines end of period

- autotest/test_gwf_npf_tvk02.py
- autotest/test_gwf_npf_tvk03.py
- autotest/test_gwf_sto_tvs01.py
- src/Model/GroundWaterFlow/gwf3sto8.f90
Added three new tests: gwf_npf_tvk02, gwf_npf_tvk03 and gwf_sto_tvs01.
@langevin-usgs Does something further need to be done to add these to the set of CI build tests, or will they be picked up automatically?
@jdhughes-usgs While writing the TVS tests, I noticed that part of the recent refactor was causing TVS to crash, as the memory allocation for OLDSS and OLDSY was moved to occur prior to when the integratechanges flag is set by TVS. I have kept the modification to use mem_allocate and mem_deallocate, but changed where and when it occurs back to using a "lazy" allocation approach, which I believe is a better option here. In addition to supporting the existing order of operations on TVS initialisation, it allows the integratechanges flag potentially to be changed at any point in the …
> TVK and TVS tests

- autotest/test_gwf_npf01_75x75.py
- autotest/test_gwf_rch03.py
- src/Model/ModelUtilities/BoundaryPackage.f90
- srcbmi/mf6bmi.f90
* The number of rows in the bound package table printed to the list file was not consistent with the number of rows written to the table.  The table writer was modified so that an entry is not written if ibound is less than or equal to zero.  This is consistent with mf2005.
* Added new recharge test that mixes irch and idomain
* Minor tweaks to mf6bmi.f90 and test_gwf_npf01_75x75.py
> fix(boundarypackage): do not print rates to list file table if ibound <= 0

- meson.build
Otherwise modflow users will have to provide them themselves or we have to ship them.
> Link intel libraries statically and add unix configuration

- srcbmi/meson.build
This results in "libmf6.dll" instead of "mf6.dll" on Windows with ifort
> Enforce "lib" prefix for shared library

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3sfr8.f90
* Close #803
* The SFR Package can die with a floating point error when calculating the stream depth as a function of flow if the flow is near zero. The stream depth should be calculated only if the flow is greater than zero, otherwise it should return a depth of zero.
> fix(sfr): Correct floating point error in depth calculation

- autotest/test_gwf_auxvars02.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Utilities/ListReader.f90
* The line variable for the list reader was only 300 characters
* This meant that lists could not be wider than 300 characters
* Values were not correctly for large numbers of aux variables
* This PR uses u9rdcom and an allocatable character string to read unlimited columns
> fix(listreader): list could not be wider than 300 columns

- meson.build
- src/Model/Connection/GridConnection.f90
- src/Model/GroundWaterTransport/gwt1uzt1.f90
- src/Solution/NumericalSolution.f90
This PR fixes a few warnings, but it mostly silences them.
None of them are really relevant as far as I can see.
Unfortunately, I can't add a workflow to check for ifort warnings since ifort doesn't support `-Werror`.
> Reduce ifort warnings to zero

- .vscode/build_vscode.py
While working on related tasks I've noticed that the vscode task fails if there is no bin folder
> Fix failure if bin dir does not exist

- autotest/test_gwt_mvt02.py
- autotest/test_gwt_mvt02fmi.py
- autotest/test_gwt_ssm01fmi.py
- src/Exchange/GwfGwtExchange.f90
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterTransport/gwt1fmi1.f90
- src/Model/GroundWaterTransport/gwt1ssm1.f90
- src/Model/NumericalModel.f90
- src/Utilities/Budget.f90
- src/Utilities/Constants.f90
- src/Utilities/PackageBudget.f90
* The gwf terms seen by FMI and SSM were different if GWF flows were read from a file or passed through a GWF-GWT exchange.
* SSM terms listed in budget table should now correspond with stress package terms listed in GWF budget table
* This is a first step toward #835
> fix(gwt-fmi-ssm): remove inconsistency in gwf terms

- autotest/build_mfio_tex.py
- autotest/update_flopy.py
- distribution/mkdist.py
The Python function `run_command` is used in a few places, and should use the process [returncode](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode) for ierr.
This fixes instances like [this one](https://github.com/modflowpy/flopy/runs/4877208422?check_suite_focus=true#step:10:215) which shows:
```
running...createpackages.py
successfully ran...createpackages.py
```
when really the command was not successful due to an unrelated error in the script.
> fix(run_command): use process.returncode for ierr

- autotest/test_gwf_npf_tvk01.py
- autotest/test_gwf_npf_tvk02.py
- autotest/test_gwf_npf_tvk03.py
- autotest/test_gwf_sto_tvs01.py
- doc/mf6io/mf6ivar/dfn/utl-tvk.dfn
- doc/mf6io/mf6ivar/dfn/utl-tvs.dfn
- src/Model/GroundWaterFlow/gwf3tvbase8.f90
* The TVK and TVS packages wrote all property changes to model listing file
* This list could be enormous for large models with many property changes
* By default writing these lists is now inactive
* These lists can be optionally written now by specifying the PRINT_OPTION option in TVK and/or TVS
* Close #871
> feat(tvk-tvs): add support for TVK/TVS PRINT_INPUT

- src/Exchange/GwfGwtExchange.f90
- src/Model/Connection/GwtInterfaceModel.f90
-Check on idisp and idiffc before copying arrays into GWT interface model
> -Use simvals for gwtgwt exchange flows in all cases

- src/Model/GroundWaterFlow/gwf3lak8.f90
* Lake outlet flows can be sent to a lake number of 0
* In this case, the flows are not stored in the budget object
* Thus, this budget term is not ordered
* Marked this budget term as unordered
* Close #893
> fix(lak): budget flow table for lake had erroneous outlet flows

- .github/workflows/ci-large-tests.yml
- autotest/test_z03_examples.py
The z03_examples.py file runs examples even if they are marked for not working with the regression version.  This fix prevents the regression simulation from running in this case.
> ci(regression-test): regression tests run even if marked they should not

- README.md
The links to CI badges had changed because we changed the names of our workflows.  This commit updates the badge links so they show up properly on the main Github page.
> docs(badges): update main page badges for renamed workflows

- .github/workflows/ci-check-warnings-gfortran.yml
- .github/workflows/ci-tests-gfortran-latest.yml
- .github/workflows/ci-tests-gfortran-previous.yml
Not strictly needed, but why shouldn't we be explicit about it.
(seems like my yaml formatter disagrees with your formatting, sorry for the noise)
> Specify FC env var in CI

- autotest/test_gwf_ifmod_xt3d01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterTransport/gwt1ssm1.f90
- src/Model/ModelUtilities/Xt3dInterface.f90
* The xt3d procedure for storing and adding matrix coefficients for extended xt3d connections did not work for lgr configurations in which a highly refined child model was nested inside a coarser parent model.  The logic was improved so that matrix terms added by exchanges were properly handled by the internal calculations used by xt3d.   Prior to this fix, the xt3d logic assumed that any matrix terms added to the local model space of the solution were because of xt3d.  This can no longer be assumed for lgr configurations.
> fix(xt3d): array access error for highly refined nested gwf or gwt model

- make/makedefaults
- make/makefile
- msvs/mf6core.vfproj
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/ModelUtilities/GwfMvrPeriodData.f90
- src/Model/ModelUtilities/Mover.f90
- src/meson.build
* create new GwfMvrPeriodData object for reading and storing mover stress period data
* store mover stress period data as vectors in the memory manager
* revise the low-level mover object to point into the input data
> refactor(GwfMvr): store mover variables in memory manager

- make/makefile
- msvs/mf6core.vfproj
- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/TransportModel.f90
- src/meson.build
Initial refactor of gwt to use a generalized base class that will support other types of transport models, for example gwe.
> refactor(gwt): Create generalized transport base class for gwe

- src/Model/Connection/CellWithNbrs.f90
- src/Model/Connection/ConnectionBuilder.f90
- src/Model/Connection/CsrUtils.f90
- src/Model/Connection/GridConnection.f90
- src/Model/Connection/GridSorting.f90
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/GwfInterfaceModel.f90
- src/Model/Connection/GwtGwtConnection.f90
- src/Model/Connection/GwtInterfaceModel.f90
- src/Model/Connection/SpatialModelConnection.f90
> style(connections): apply fprettify formatting

- DEVELOPER.md
The [developer README](https://github.com/MODFLOW-USGS/modflow6/blob/develop/DEVELOPER.md#python) stipulates Python>=3.7. However [`xmipy`](https://github.com/Deltares/xmipy) uses f-string [self-documenting expressions](https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging) (a Python 3.8 feature) [here](https://github.com/Deltares/xmipy/blob/7375186e91b4868c364a9269ba82539a915e8d91/xmipy/xmiwrapper.py#L381). Running tests with Python 3.7 produces syntax errors in the following:
- test_gwf_ifmod_mult_exg.py
- test_gwf_libmf6_evt01.py
- test_gwf_libmf6_ghb01.py
- test_gwf_libmf6_ifmod01.py
- test_gwf_libmf6_ifmod02.py
- test_gwf_libmf6_ifmod03.py
- test_gwf_libmf6_rch01.py
- test_gwf_libmf6_rch02.py
- test_gwf_libmf6_riv01.py
- …
> docs: require Python3.8 per xmipy dependency

- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/GroundWaterTransport/gwt1adv1.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/GroundWaterTransport/gwt1cnc1.f90
- src/Model/GroundWaterTransport/gwt1dsp.f90
- src/Model/GroundWaterTransport/gwt1fmi1.f90
- src/Model/GroundWaterTransport/gwt1ic1.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
- src/Model/GroundWaterTransport/gwt1lkt1.f90
- src/Model/GroundWaterTransport/gwt1mst1.f90
- src/Model/GroundWaterTransport/gwt1mvt1.f90
- src/Model/GroundWaterTransport/gwt1mwt1.f90
- src/Model/GroundWaterTransport/gwt1obs1.f90
- src/Model/GroundWaterTransport/gwt1oc1.f90
- src/Model/GroundWaterTransport/gwt1sft1.f90
- src/Model/GroundWaterTransport/gwt1src1.f90
- src/Model/GroundWaterTransport/gwt1ssm1.f90
- src/Model/GroundWaterTransport/gwt1uzt1.f90
> style(gwt): apply fprettify formatting

- .github/common/install-python-std.sh
- meson.build
The issue is caused by the latest meson release. Exclude meson version 0.63.0.
> ci: fix Intel OneAPI build on Windows

- .github/common/fortran-format-check.sh
- .github/common/install-python-std.sh
- .github/workflows/ci-format.yml
* currently only searches modflow6/src for files to check
This new action is expected to fail for modflow6/src files updated by PR #980 (not yet approved) but creating this now to test and evaluate.
> ci(actions): add ci action to check fortran source formatting

- .github/common/fortran-format-check.sh
- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiError.f90
- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.f90
> style(srcbmi): apply fprettify formatting

- .vscode/README.md
- CONTRIBUTING.md
- DEVELOPER.md
* reorganize vscode README and include fprettify integration
* update DEVELOPER and CONTRIBUTING docs to describe tools and standard
> docs(formatting): add fortran source formatting to documentation

- .github/common/install-python-std.sh
- .github/workflows/ci-check-warnings-gfortran.yml
- .github/workflows/ci-docs.yml
- .github/workflows/ci-format.yml
- .github/workflows/ci-large-tests.yml
- .github/workflows/ci-tests-gfortran-latest.yml
- .github/workflows/ci-tests-gfortran-previous.yml
- .github/workflows/ci-tests-ifort.yml
- .vscode/README.md
- .vscode/run_python.cmd
- .vscode/run_python.sh
- .vscode/tasks.json
- DEVELOPER.md
- environment.yml
This PR adds an `environment.yml` which should make it easier to keep docs and CI in sync.
It also changes the behavior of the vscode tasks.
It expects an environment called `modflow6` created with the following command.
```
conda env create --force -f environment.yml
```
You might also want to change your `"fortran.fortls.path"` setting to the `fortls` in your `modflow6` environment.
Ideally, you would use this environment for your daily development work as well and adapt it if our dependencies change.
@jmccreight, @mjr-deltares, @langevin-usgs, @jdhughes-usgs, @mjreno
> Add conda `environment.yml`

- DEVELOPER.md
I removed the Visual Studio installation on my Windows laptop (because I'm using VSCode), and then I found out ifort wouldn't compile anymore. I reinstalled Visual Studio, but still got a confusing error: "visual studio 2017 or 2019 is not found in c:\program files (x86)\microsoft visual studio\<2017 or 2019>\<edition>, please set vs2017installdir or vs2019installdir".
This is resolved by installing the C++ Desktop Development components. Apparently, the ifort compilers rely on some of the C++ parts.
I'm quite confident some parts aren't required (E.g. Test Adapter for Boost.Test), but I haven't done the research to find which parts are required and not. At the least, just checking the "Desktop Development with C++" checkbox does the trick.
> DEVELOPER.md: Visual Studio for ifort

- doc/mf6io/mf6ivar/dfn/gwf-buy.dfn
To hopefully avoid confusion on my part, I had a look in `gwf3buy8.f90` and it does not appear to look for a PERIOD block, so I think this reference in the `nrhospecies` description might be leftover from previous code development.
> docs(gwf-buy.dfn): variable description refers to block that does not exist

- autotest/test_gwt_adv01_gwtgwt.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/exg-gwtgwt.dfn
- src/Exchange/GwtGwtExchange.f90
The main point of this PR is to always use the interface model, even if xt3d is not used for dispersion.
In this PR I've changed several keywords in options block of the GWT-GWT Exchange file. 
ADVSCHEME => ADV_SCHEME
XT3D_OFF => DSP_XT3D_OFF
XT3D_RHS => DSP_XT3D_RHS
It seems desirable to mark these options with the underlying packages to which they belong.  The downside is that this will break any models that used these keywords.  I doubt they have been used much (since the XT3D_OFF keyword didn't work correctly), but it does break some things.  This is why we have a CI failure at the moment.  Maybe we support ADVSCHEME (only in the Fortran code) and ADV_SCHEME for one release to avoid the headaches associated with keyword renaming?
> fix(gwtgwt): allow exchange to work without XT3D active for dispersion

- autotest/test_z03_examples.py
- distribution/evaluate_run_times.py
Skip regression test for ex-gwtgwt-mt3dms-p10 because PR #1008 changed the gwtgwt keywords.  The name for this test was also based on an earlier name (ex-gwtgwt-mt3dms-p10), which is slightly different from the current test name (ex-gwt-gwtgwt-mt3dms-p10).
> ci(z03): prevent regression on gwtgwt example since keyword changed

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
* When the LAK Package was used with a combination of outlets that routed water to another lake and outlets that did not, then the budget information stored for the LAK Package had uninitialized records for LAK to LAK flows.  These uninitialized records were used by the LKT Package and possibly other programs.  The LAK to LAK budget information was modified to include only valid records.
* Close #1006
* Close #1007
> fix(gwt): LKT fix for outlet flows

- .vscode/README.md
Turns out you need to run vsdbg to debug with ifort compiled binaries on Windows.
> docs: Add vsdbg to vscode docs

- src/Exchange/DisConnExchange.f90
* If cellid in exchange is in IDOMAIN<1 cell, then the cellid written to the error message was wrong
* Close #1038
> fix(exg): cellid not correct in error message

- autotest/test_gwt_lkt04.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/gwf-lak.dfn
- doc/mf6io/mf6ivar/dfn/gwf-sto.dfn
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
* Close #1043
* When a WITHDRAWAL value was specified for lakes, only the withdrawal value for the last lake would be reported in budget files, lake budget tables, and in lake withdrawal observations.  This error would also be propagated to the GWT Lake Transport (LKT) Package, if active.  This error would only show up for models with more than one lake and if the lake withdrawal term was included.
* When lakes were assigned with the STATUS CONSTANT setting to prescribe the lake stage, the CONSTANT term used in the lake budget table was tabulated using an incorrect sign for aquifer leakage.  This error would result in inaccurate budget tables.  The program modified to use the correct leakage values for calculating the CONSTANT term.
* The BUDGETCSV option was activated to work for the GWT …
> fix(lak): withdrawal and budget errors

- autotest/test_gwf_evt02.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3evt8.f90
- MF6 crashes if the user chooses to run with a single ET segment and also activate the `SURF_RATE_SPECIFIED` keyword in the `OPTIONS` block
- The current EVT01 autotest (`test_gwf_EVT01.py`) didn't check this condition
- New test confirms that model runs when `nseg` is equal to 1 and `SURF_RATE_SPECIFIED` option activated by ensuring model output is generated.
- Ran black
> fix(evt): model crashes with option SURF_RATE_SPECIFIED and nseg=1

- src/Model/Connection/GridConnection.f90
- src/Model/Connection/GridSorting.f90
- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/ModelUtilities/DiscretizationBase.f90
prep. refactoring for the interface model:
- introduced cell center coordinate arrays for all DIS, getting rid of get_cellxy subroutine
- transform_xy is now stateless
> rfct(dis): add xc, yc to DIS as cell center coordinates

- src/Model/GroundWaterFlow/gwf3maw8.f90
not a big deal, but output message written to .lst might be confusing to a new user.  Based on what's in mf6io.pdf, the four allowed options are `THEIM`, `SKIN`, `CUMULATIVE`, and `MEAN`.
> fix(maw): patch-up relatively minor typo

- src/Model/GroundWaterFlow/gwf3buy8.f90
Based on a review comment in the VSC PR (#1071) related to a missing `else` statement, adding the missing `else` in BUY as well (VSC parallels BUY).  See lines 1229-1232 in the PR'd file.  Because the added `else` statement includes a msg written to the standard listing file, and because messaging is being switched to lowercase, went ahead and updated all the messages in BUY as it doesn't look like BUY has been updated yet (e.g., #1073).
> fix(buy): add missing else; switch messaging to lowercase

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Exchange/GwfGwfExchange.f90
- src/Model/GroundWaterFlow/gwf3.f90
* update release notes
* issue error if more than one VSC6/BUY6 package active
* convert to lower case error messages
> fix(vsc): issue error if VSC used in GWF-GWF model

- .github/workflows/ci.yml
- .github/workflows/release.yml
- autotest/pytest.ini
- autotest/test_gwf_ifmod_buy.py
- autotest/test_gwf_ifmod_mult_exg.py
- autotest/test_gwf_ifmod_rewet.py
- autotest/test_gwf_ifmod_vert.py
- autotest/test_gwf_libmf6_ifmod02.py
- autotest/test_gwfgwf_lgr.py
- autotest/test_gwt_adv01_gwtgwt.py
- autotest/test_gwt_dsp01_gwtgwt.py
- autotest/test_z01_testmodels_mf6.py
- distribution/build_dist.py
- distribution/update_version.py
- Only trigger job to open PR reinitializing `develop` after release is published. The automated workflow only creates a draft release &mdash; the release must be published manually after inspection. Previously the reinitialization job was triggered immediately after the release branch was merged to `master`, after this reinit will only happen after the release post is converted from draft to official.
- Update `develop` reinitialization job such that, for minor version releases, minor version number is incremented from just-released version and patch number is reset to 0, while for patch releases, the version on `develop` does not change. This is according to the tentative expectation that minor version releases will branch from `develop`, while patch releases will branch from `master` …
> fix(ci): revise distribution scripts and workflow

- autotest/test_gwf_sfr_evap.py
- doc/ReleaseNotes/v6.5.0.tex
- src/Model/GroundWaterFlow/gwf3sfr8.f90
Currently, evaporation from SFR reaches uses the variable rwid even if the wetted top width in a n-point cross-section is narrower than rwid.
- Includes new autotest (ran black)
- Ran fprettify
- Includes a short description of bug in appropriate release notes .tex file
- Visual inspection of SFR budgets in .lst file looks good
- Rain calculations are currently using the fixed rwid value and not taking into account changing surface area widths associated with an irregular n-point cross-section, but this is probably OK as the rain falling on the dried channel width  falling between `rwid` and the actual wetted top width (< `rwid`) would likely be accumulated in the channel.  
- Also, in `gwf3sfr8.f90` the following code, starting around line 2200, may need updating to account for n-point …
> fix(sfr): evaporation from sfr reaches should use wetted top width

- distribution/update_version.py
- meson.build
The version number in `meson.build` was still 6.4.1. Bump it to 6.5.0 and modify `distribution/update_version.py` to update it as part of the automated release process.
> fix(version): update meson.build to 6.5.0, autoupdate in update_version.py

- autotest/simulation.py
- autotest/test_z01_testmodels_mf6.py
- doc/ReleaseNotes/v6.5.0.tex
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/PackageMover.f90
* update release notes
* store previous qfrommvr iterate in PackageMover
* add qfrommvr convergence check to UZF, SFR, and LAK.  The qfrommvr rate is converted into a depth (using delt over area), which is used to check against DVCLOSE.  
* Related to #1116
> feat(uzf): add qfrommvr convergence check to UZF

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/large.yml
- DEVELOPER.md
- autotest/build_exes.py
- autotest/common_regression.py
- autotest/conftest.py
- autotest/get_exes.py
- autotest/simulation.py
- autotest/test_gwf_henry_nr.py
- autotest/test_mf6_tmp_simulations.py
- autotest/test_z01_testmodels_mf6.py
- autotest/test_z02_testmodels_mf5to6.py
- autotest/test_z03_examples.py
- autotest/test_z03_largetestmodels.py
Update tests that load models from external repos to use devtools fixtures, with a bit of other refactoring. This was carved out of #1066 for a smaller changeset and more incremental refactor.
- Use fixtures from `modflow-devtools` to:
- map target executable names to their paths (`targets` fixture)
- parametrize tests with models loaded from external repos
- the set of models tested is not changed &mdash; coupled GWT models are skipped, as before
- support example selection by model name/package via `--model`/`--package` pytest CLI options
- ~~there is a package filtering bug in devtools, soon to be fixed in https://github.com/MODFLOW-USGS/modflow-devtools/pull/44~~
- support `--original-regression` flag as a pytest CLI option/fixture (configured in new `conftest.py` file)
- update …
> refactor(tests): use devtools fixtures

- .build_rtd_docs/requirements.rtd.txt
- .github/workflows/ci.yml
- DEVELOPER.md
- autotest/conftest.py
- autotest/pytest.ini
- autotest/test_z01_testmodels_mf6.py
- autotest/test_z02_testmodels_mf5to6.py
- autotest/test_z03_examples.py
- autotest/test_z03_largetestmodels.py
Add `pytest` as a ReadTheDocs dependency. Needed because the docs build procedure [updates timestamps with `distribution/update_version.py`](https://github.com/MODFLOW-USGS/modflow6/blob/29dfdcfe03d1d73d48f244787b8241d3a396d416/.build_rtd_docs/conf.py#L41), which uses `pytest`. ReadTheDocs-hosted builds have been failing since #1069 because of this. The GitHub Actions `docs.yml` workflow has passed in the meantime because it installs the Conda `environment.yml` before installing extra docs deps.
Also address a few issues with external model test selection introduced in or noticed after #1130
- Explicitly deselect large/example model tests in commit-triggered CI, since the convention is to only run these nightly.
- With the [recent …
> ci: fix tests and readthedocs

- .build_rtd_docs/requirements.rtd.txt
Neglected to add `filelock` as another ReadTheDocs dependency in #1132. Like `pytest`, this is used by `update_version.py`, which is run in the automated ReadTheDocs build to update timestamps.
> ci: add filelock as readthedocs dependency

- .build_rtd_docs/conf.py
- .build_rtd_docs/requirements.rtd.txt
- .doc/conf.py
- .doc/requirements.txt
- .github/workflows/docs.yml
~~I think this is the last remaining issue breaking the ReadTheDocs build. I tried setting up another RTD project to debug on my fork, but couldn't match this repo's configuration.~~
Fix automated RTD builds where #1132 and #1135 failed to do so. Tested on my fork with a [separate RTD integration](https://modflow6-w-bonelli-test.readthedocs.io/en/latest/index.html). Apologies for all the PRs. Also:
- update copyright year from 2020 to 2023
- use `myst-parser`, drop `recommonmark` [as per recommendation](https://github.com/readthedocs/recommonmark/issues/221)
- use `update_version()` function directly in `conf.py` instead of `Popen`
> ci: fix readthedocs

- autotest/get_exes.py
- distribution/benchmark.py
- distribution/build_docs.py
Update `modflow-devtools` usages in distribution scripts. This is to reflect changes introduced in https://github.com/MODFLOW-USGS/modflow-devtools/pull/68. These include improvements to utility functions used for querying/downloading from the GitHub API, including standardized signatures and adding retries. This seemed worthwhile for consistency and resilience to transient network errors, but will try to keep further breaking changes to devtools to an absolute minimum.
To avoid breaking the nightly build, this will need to be merged the same day that a [new version of devtools](https://github.com/MODFLOW-USGS/modflow-devtools/pull/72) is released. CI is expected to fail here in the meantime, pending such.
This PR also replaces a lingering `pymake` usage.
> refactor(dist scripts): update modflow-devtools usages

- environment.yml
Today's [update](https://github.com/MODFLOW-USGS/modflowapi/commit/de4452c64d2f0091068af177eae609db7ccce40c#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52R40) to `modflowapi` led to [dependency resolution issues](https://github.com/MODFLOW-USGS/modflow6/actions/runs/4188649571/jobs/7260041004) with the modflow6 Conda environment. Conda does not seem to check pip/GitHub dependencies to determine whether they point to the same branch.
Remove `xmipy` from `environment.yml` since `modflowapi` will install it as its own dependency &mdash; `modflowapi` is used directly in autotests, but `xmipy` is not.
> fix(dependencies): remove explicit xmipy dependency

- .build_rtd_docs/conf.py
- autotest/build_exes.py
- autotest/build_mfio_tex.py
- autotest/conftest.py
- autotest/update_flopy.py
- distribution/build_dist.py
- distribution/build_docs.py
- distribution/conftest.py
- distribution/update_version.py
- distribution/utils.py
The primary fix is with `make_distribution.py`, which would raise non-sense errors like "FileNotFoundError: [Errno 2] No such file or directory: '/path/to/modflow6/distribution/version.txt'" (it is off by one directory) when invoked using a relative path. The issue is that `__file__` when invoked as a script is not always absolute, which is fixed by `Path(__file__).resolve()`. (And there is no need to use `expanduser()` for these instances).
Other changes:
- use the absolute path to the current Python interpreter `sys.executable` instead of `"python"`
- add `expanduser()` in a few places that may need it
- re-use pathlike variables
> fix(Python paths): use absolute paths for scripts and Python executable

- CITATION.cff
- distribution/update_version.py
This is similar to https://github.com/modflowpy/flopy/pull/1547. Authors can change for each software release. Not sure if it is useful, but I've added "affiliation" for each author. The list and order in this PR is the same as https://github.com/MODFLOW-USGS/modflow6/releases/tag/6.4.1
A plain-text version of the citation can be show via (first `pip install cffconvert`) `cffconvert -f apalike` or other format. GitHub will show both APA-like and BibTeX versions.
Version number and date is updated via `distribution/update_version.py`
Should https://github.com/dieghernan/cff-validator be added? If so, which workflow?
> feat(CITATION.cff): add software citation

- .vscode/tasks.json
* run dfn2f90.py -- convert definition files to Fortran 90 input data model equivalents
* run update_flopy.py -- update flopy to support the definition files in the modflow6 repo
* run mf6ivar.py -- rebuild the mf6io latex documents from definition files
With the changes for the input data model and our broader adoption of vscode, this PR adds several vscode build tasks for common operations.
> feat(vscode-tasks): add build commands for common tasks

- distribution/build_dist.py
- distribution/build_docs.py
- distribution/update_version.py
- doc/ReleaseNotes/v6.5.0.tex
- doc/ReleaseNotes/vx.x.x-template.tex
- Include release notes in development mode distributions (e.g. the nightly build)
- Use tex version commands in release notes template
- Miscellaneous cleanup in distribution scripts
https://github.com/MODFLOW-USGS/modflow6-nightly-build/pull/24 updates the nightly build workflow. Here is a [test run](https://github.com/w-bonelli/modflow6-nightly-build/actions/runs/4577430990) on my fork, and the [release created](https://github.com/w-bonelli/modflow6-nightly-build/releases/tag/20230331) by it
> refactor(distribution): add release notes to dev dist (nightly build)

- autotest/test_gwt_zb01.py
- doc/zonebudget/zonebudget.tex
- mention support for GWT budget files in zonebudget docs, motivated by https://github.com/MODFLOW-USGS/modflow6/discussions/1181
- add a test case `test_gwt_zb01.py` for zonebudget with GWT budget file
- minor non-functional refactoring to `test_gwf_zb01.py`
- use `with` context manager for file writing
- use `pathlib`
> docs(zbud): mention support for GWT budget files, add test

- src/Model/GroundWaterFlow/gwf3drn8.f90
Error msg cites the variable name `AUXDDRNNAME` but the keyword in the OPTIONS block is `AUXDEPTHNAME`.  Suggesting this minor fix for consistency.
Related to #414.
> fix(gwf3drn8): auxddrnname in error msg does not exist

- doc/mf6io/mf6ivar/dfn/gwf-sfr.dfn
The `false` setting was leading to an oddity in mf6io.pdf
> docs(gwf-sfr.dfn): cross_section keyword is a part of sfrsetting

- autotest/test_gwf_ptc01.py
- autotest/test_z01_testmodels_mf6.py
- src/Model/GroundWaterFlow/gwf3.f90
- src/Solution/NumericalSolution.f90
Also simplified PTC psuedo timestep calculation to eliminate need to evaluate the maximum and minimum non-zero diagonal entry. Also eliminated evaluation of the PTC ratio in the NumericalSolution. Elimination of the evaluation of diagonal entries is in preparation for parallel implementation of PTC.
> refactor(PTC): fix residual calculation used in calculate PTC timestep

- .github/workflows/docs.yml
Switch from `peaceiris/actions-gh-pages` to `actions/deploy-pages` to deploy the Doxygen docs to GitHub Pages. This, in combination with switching the Pages source from branch to actions, allows removing the `gh-pages` branch. This should shrink the `.git` directory and speed up clone/fetch/pull as suggested in #1122
[Tested on my fork](https://github.com/w-bonelli/modflow6/actions/runs/4786691780) with the [deployed site here](https://w-bonelli.github.io/modflow6/)
> ci: use actions/deploy-pages (allows removing gh-pages branch)

- autotest/test_gwt_ssm04fmi.py
- src/Model/GroundWaterTransport/gwt1ssm1.f90
- src/Model/ModelUtilities/GwtSpc.f90
The Stress Package Concentration (SPC) input for the GWT SSM package was not working correctly when (1) flow models were run first in a separate simulation before the transport model, (2) the READASARRAYS option was specified, and (3) the model had IDOMAIN active with some cells marked as non-existent.  The problem stems from how lists of boundary conditions that support READASARRAYS (recharge and evapotranspiration) are stored in memory or written to binary budget files.  Lists of recharge entries written to the GWF binary budget file do not include entries for cells that are marked with IDOMAIN < 1.  In most cases, a stress cannot be assigned to a cell marked with IDOMAIN < 1, as mf6 will terminate with an error, but with the READASARRAYS option, stresses can be assigned to non-existent …
> fix(gwtssmspc): another fix for readasarrays with SPC

- src/Model/GroundWaterFlow/gwf3uzf8.f90
* implicit array assignment can result in stack overflow for large uzf packages
* change array assignment to explicit loop
> fix(gwfuzf): fix array assignment to prevent stack overflow

- environment.yml
- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiError.f90
By exposing `get_value_ptr_double` and `get_value_ptr_int` we are strictly speaking not BMI conform.
This PR fixes this aspect by adding `get_value_ptr`.
The corresponding PR on the xmipy side can be found here: https://github.com/Deltares/xmipy/pull/98
If merged, we should coordinate the next xmipy and MODFLOW 6 release
- New versions of xmipy will not work with older versions of MODFLOW.
- The xmipy API stays the same.
- Remove  `get_value_ptr_double` and `get_value_ptr_int` completely
> Add `get_value_ptr`

- .github/workflows/ci.yml
- distribution/build_docs.py
[Un-escaped underscores](https://github.com/MODFLOW-USGS/modflow6/pull/1241) were causing errors when building the documentation PDF. To catch this kind of thing before PRs are merged, install docs dependencies on Linux CI and build the example model used to capture sample mf6 output (`ex-gwf-twri`) so that we test the full docs build. Previously the test for building the PDF was skipped due to missing exes. Also refactor `distribution/build_docs.py` to make the sample example configurable, plus a bit of cleanup
> test(docs): test pdf docs build in linux CI

- autotest/conftest.py
- autotest/test_gwf_tdis.py
- src/Timing/tdis.f90
This PR ensures that `totim` should more accurately track along `perlen` for the end of each stress period, without introducing floating point errors during geometric progression.
For instance, take a simulation with `nper=4`, `nstp=3`, `perlen=7.0` and `tsmult=1.2`. The total duration is 28.0. Using mf6.4.1 (12/09/2022), here are the `totim` values from the end of each stress period:
```
7.000000000000002
14.000000000000004
21.000000000000004
28.0
```
Using the latest development snapshot:
```
6.999999999999998
13.999999999999996
20.999999999999993
28.0
```
awkward! Only the last `totim` is exact since it is substituted by `totalsimtime`. Older MODFLOW releases have similar accumulation errors. The PR changes the last `totim` values to the expected sequence:
```
7.0
14.0
21.0
28.0
``` …
> refactor(tdis): Calculate exact last delt to avoid accumulation errors with totim

- README.md
- autotest/conftest.py
- autotest/test_gwf_ifmod_buy.py
- autotest/test_gwf_ifmod_idomain.py
- autotest/test_gwf_ifmod_mult_exg.py
- autotest/test_gwf_ifmod_newton.py
- autotest/test_gwf_ifmod_rewet.py
- autotest/test_gwf_ifmod_vert.py
- autotest/test_gwf_libmf6_ifmod02.py
- autotest/test_gwfgwf_lgr.py
- autotest/test_gwt_adv01_gwtgwt.py
- autotest/test_gwt_dsp01_gwtgwt.py
- autotest/test_z01_testmodels_mf6.py
- autotest/test_z03_largetestmodels.py
Some tests were originally marked with `@pytest.mark.developmode` in https://github.com/MODFLOW-USGS/modflow6/commit/8c9388d0f89df97b6b138d7ff981ff48cd799af2, then the marker was mistakenly removed in https://github.com/MODFLOW-USGS/modflow6/commit/e51530cd90d701549a00c216b371fcc6281451da. Also add mechanism to skip tests from modflow6-testmodels repo (in `z0*` scripts) if the name contains "dev".
Tangentially, add a link to modflow-devtools in the CI section of the README since devtools is a testing dependency.
> test: add markers/mechanism to skip developmode tests in release mode

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- autotest/test_cli.py
- distribution/README.md
- distribution/build_docs.py
- distribution/check_dist.py
- distribution/conftest.py
- distribution/update_version.py
- distribution/utils.py
Update release procedures to reduce duplication across repositories and increase configurability. The main changes are:
- make `release.yml` reusable with [`workflow_call` trigger](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow)
- allows nightly build repo to test release procedure without duplicating the workflow definition
- add `release_dispatch.yml` workflow
- preserves previous release trigger mechanism (pushing a release branch named `vx.y.z` etc), preserves mechanism to distinguish preliminary from approved releases (does the branch name end with "rc"?)
- add support for [manual trigger via UI or CLI](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) with `workflow_dispatch`
The `release.yml` …
> ci: refactor/cleanup release workflow, make reusable

- .github/workflows/release.yml
- distribution/check_dist.py
- Don't default to develop branch in `release.yml` since `release_dispatch.yml` already prevents releasing from develop and master. Releases are expected to come from release branches. Currently the branch must preexist the workflow run, in future we might add a mechanism to automatically create a release branch from develop or master
- Fix tests in `check_dist.py`. Previously the IDEVELOPMODE check was conditioned on the presence of "rc" in the branch name, now there is an explicit pytest arg for it, `--approved`  (short `-A`)
> ci: fix release refactor

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- distribution/README.md
- distribution/build_dist.py
- distribution/build_docs.py
- distribution/check_dist.py
- distribution/conftest.py
- distribution/update_version.py
Previously there were overlapping concerns between the `development` and `approve` inputs to `release.yml`. This PR
- Introduces `full` to control what is included in the distribution. If false, only binaries, mf6io, release notes, and code.json are included (i.e. a minimal dist). If true, everything (previously listed items plus sources, examples, all docs, etc) is included ((a full distribution).
- Renames `development` to `developmode` which now controls only whether binaries are built in develop or release mode (`IDEVELOPMODE` 1 or 0).
- Modifies the behavior of `approve` to control only whether language is "preliminary/provisional" or "approved for release", etc, in readme and disclaimer, and whether "(preliminary)" is appended to the version string emitted by executables.
This …
> ci: refine release workflow after feedback

- src/Utilities/Sim.f90
This resolves an issue with mf6 built using GNU Fortran on Linux, which doesn't flush output buffers as frequently as other builds.
Before this PR, running `pytest` with xmipy would delay the output such that it would not be captured by pytest.; see https://github.com/Deltares/xmipy/issues/107
> refactor(print_final_message): flush console buffer output to stdout

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- distribution/benchmark.py
- distribution/build_dist.py
- distribution/build_docs.py
- distribution/build_makefiles.py
- distribution/check_dist.py
- distribution/conftest.py
- distribution/update_version.py
- distribution/utils.py
- prevent double-zipping on Windows (workaround [upload/download artifact behavior](https://github.com/actions/upload-artifact/issues/39))
- update `release_dispatch.yml` input descriptions
- fix sample output substituted into mf6io
- fix steps to build examples
- format dist scripts
> ci: fix release scripts and workflow

- .github/workflows/release.yml
- set default ubuntu used for releases to 20.04
- allows making decisions like https://github.com/MODFLOW-USGS/modflow6/discussions/1163 on a case by case basis. For now the convention has been releases here and executables repo build on 20.04 and nightly build on 22.04. If this is merged, nightly build needs an update to select 22.04 explicitly (if we still want that). Or maybe we could do both 20 and 22 nightly
> ci(release): make linux version used for build configurable

- autotest/test_gwf_chd02.py
- doc/ReleaseNotes/v6.4.2.tex
- src/Utilities/ListReader.f90
- Added autotest (test_gwf_chd02) to confirm that binary stress period data with auxiliary data can be run.
- Updated the release notes.
> fix(ListReader): fix issue reading binary stress period data with AUX variables

- .github/workflows/docs.yml
MF6 benchmarks run in `docs.yml` and results are uploaded as artifacts, then are downloaded by the release workflow to include in the distribution. However the artifact produced by `docs.yml` has been broken for some time, because FloPy classes were not updated from DFNs before benchmarking. Update flopy before running benchmarks to fix this.
> ci: update flopy before benchmarking in docs.yml

- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
Accommodate empty inputs in `release_dispatch.yml`. Inputs are empty if the workflow is triggered by pushing a release branch. Later on this should be done in a cleaner way, e.g. all inputs should be processed in the `set_options` job, so conditionals later in the workflow can be simplified. Expediting a temporary solution to allow moving forward with the 6.4.2 release.
> ci: release fixes related to example models

- distribution/check_dist.py
Adapt version string test in `check_dist.py` to the new develop branch versioning scheme (`x.y.z.dev0`)
> fix(check_dist.py): correct version str check

- .github/workflows/ci.yml
[Version 13](https://gcc.gnu.org/gcc-13/changes.html) of the GNU toolchain is out.
- update `build` job to gfortran 13
- consolidate latest/previous jobs in a single `test_gfortran` matrix
- ubuntu-20.04, gfortran 7-11
- ubuntu-22.04, gfortran 12-13
- macos-12, gfortran 13
- windows-2022, gfortran 12* (`setup-fortran` action doesn't yet support gfortran 13 on Windows)
- only run autotests on latest version on each platform
> ci: test with gfortran 13

- .github/workflows/ci.yml
- autotest/get_exes.py
- [`awvgwk/setup-fortran`](https://github.com/awvwgk/setup-fortran) now supports the Intel toolchain on Windows. Switch from `install-intelfortran-action`. Plan to switch all EC repos and eventually archive both `install-[intel/g]fortran-action`
- Expand Intel test matrix. Meson compile and test a range of `ifort` and select `ifx` versions, where compatible (ifx only on linux and windows as it's [not yet supported](https://www.intel.com/content/www/us/en/docs/fortran-compiler/get-started-guide/2023-2/get-started-on-macos.html) on mac). Only run autotests on one ifort job per platform to avoid lengthening CI too much. Run autotests on an older ifort (2021.7) because newer ones fail to rebuild 6.4.2 due to backspace issues.
- Remove some now-unnecessary duplication of steps
> ci: test more Intel compiler versions

- .github/workflows/large.yml
update `large.yml` nightly workflow ([test run](https://github.com/w-bonelli/modflow6/actions/runs/5757588617))
- cache warming was broken when `ci.yml` switched to `setup-fortran` for intel
- use `setup-fortran` for test matrix
- test ifx 2022.2.1 and ifort 2021.6
> ci: use setup-fortran in large.yml, expand matrix, cache intel compilers

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
as discussed offline
- add compiler version to suggested info in bug report template (if mf6 built from source)
- introduce [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with checklist (should there be any more items?)
> docs: add PR template, add compiler version to bug report template

- .build_rtd_docs/conf.py
- .build_rtd_docs/index.rst
- .github/workflows/docs.yml
- .github/workflows/release.yml
- DEVELOPER.md
- distribution/build_docs.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/mk_deprecations.py
- doc/mf6io/mf6ivar/deprecations.py
- doc/mf6io/mf6ivar/md/deprecations.md
- doc/mf6io/mf6ivar/mf6ivar.py
- doc/mf6io/mf6ivar/readme.md
* add script `doc/mf6io/mf6ivar/deprecations.py` to scrape DFNs and generate markdown table
* run deprecations script in `docs.yml` CI and upload result file as artifact
* add `mk_deprecations.py` script to convert markdown to LaTeX table
* update `build_docs.py` to include deprecations in release notes
* add deprecation policy section to `DEVELOPER.md`
* add deprecations page to ReadTheDocs
> ci(release): track deprecations in release notes

- .build_rtd_docs/Doxyfile
- .build_rtd_docs/conf.py
- fix broken RTD styling https://stackoverflow.com/questions/73220398/sphinx-rtd-theme-not-formatting-correctly-missing-theme-css
- fix outdated Doxyfile date
> docs(conf.py): use html_css_files instead of html_context

- .doc/conf.py
- .doc/requirements.txt
* use `html_css_files` instead of `html_context` in `.doc/conf.py`
* constrain `sphinx` & `sphinx_rtd_theme` versions in `.doc/requirements.txt`
> docs: multiple fixes

- .gitlab-ci.yml
- .hpc/cray-meson-build.slurm.batch
- .hpc/update-module.slurm.batch
- add `gitlab-ci.yml` with denali deploy job, triggered on push to default branch on internal USGS GitLab mirror
- add `update-module.slurm.batch` job to update denali mf6 module
- move hardcoded info to env vars set via git forge (github or gitlab) variables
> ci: add gitlab config for automatic denali build

- doc/mf6io/mf6ivar/examples/gwf-rch-example.dat
Not sure how this snuck in, but it has been around for some time.
> fix(docs): list-based recharge example has an error

- .fprettify.yaml
`.fprettify.yaml` lives in the project root now
> chore: fix comment in .fprettify.yaml

- autotest/test_gwf_disu.py
- autotest/test_gwf_disv.py
- autotest/test_gwf_disv_uzf.py
- doc/ReleaseNotes/develop.tex
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/ModelUtilities/DisvGeom.f90
> refactor(disv): improve cell area calculation

- src/Utilities/ArrayHandlers.f90
Support expanding 2D integer & double allocatable arrays. For use by PRT for particle bookkeeping.
*unit testing demo/discussion moved to #1387*
> feat(ArrayHandlers): add 2D array expansion interface

- environment.yml
* fixes CI failures caused by `setup-micromamba` now using python 3.12 (released 10/2) as default
* see https://github.com/csdms/bmi-python/issues/19#issuecomment-1758408976 for context
> refactor: use python <= 3.11 for bmipy compatibility

- src/Model/GroundWaterTransport/gwt1.f90
A bit of additional information about the PR: These routines are not needed because the code solves for the advanced transport packages in the matrix equations directly.  By solving them in the matrix, the solver will do all the needed checks.  These additional convergence checks are needed if a package solves a balance equation separately (like SFR--not SFT).  None of the transport boundary packages should be doing this; however, MVT has a routine to force at least 2 outers.  Thus, this PR deletes the commented code and mentions some of this reasoning in the doxygen comment.
> misc(gwt1.f90): remove commented code and supplement doxygen comment

- .github/workflows/ci.yml
- DEVELOPER.md
- autotest/TestArrayHandlers.f90
- autotest/meson.build
- autotest/tester.f90
- meson.build
* introduce [test-drive](https://github.com/fortran-lang/test-drive) unit test framework as optional development aid
* tests hook into meson test if test-drive installed, otherwise ignored
* add minimal test cases for ExpandArray2D ArrayHandlers interface
* add unit testing section to developer docs
* include tests in smoke test job in `ci.yml`
* close #1387
> test(ArrayHandlers): add unit tests via optional framework

- src/Utilities/InputOutput.f90
Part of the generalized transport refactoring is that the dependent variable name varies depending on which type of model is implemented (GWT vs GWE).  To accommodate this in the standard output listing file, `padl` assists with writing well-formatted messages.
> feat(InputOutput.f90): Introduce padl, a string manipulation function

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- switch from `modflowpy/install-intelfortran-action` to `fortran-lang/setup-fortran`
- give `release.yml` inputs `compiler_toolchain` and `compiler_version`
- for supported values see [`fortran-lang/setup-fortran`](https://github.com/fortran-lang/setup-fortran) and [mf6 compatibility matrix](https://github.com/MODFLOW-USGS/modflow6/blob/develop/DEVELOPER.md#compiler-compatibility)
- makes compilers configurable if release is manually triggered or called from another workflow
- if release is triggered with a release branch, default is `intel-classic` (ifort) version `2021.7`
~~**Blocked** until `setup-fortran` action supports intel compilers on ubuntu 20.04~~
> ci(release): make compiler toolchain/version configurable

- environment.yml
- meson.build
- meson.options
- src/Utilities/defmacro.F90
- src/Utilities/version.f90
* rename PROFESSIONAL to EXTENDED version
* add function to test if __WITH_NETCDF__ define
* refactor is_pro to is_extended function that evaluates if either WITH_PETSC or WITH_NETCDF are defined
* add -Dextended=true meson option that will eventually replace -Dparallel=true
> build(meson): add support for NetCDF in meson build system

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- DEVELOPER.md
* relative links [are supported in markdown files](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#relative-links-and-image-paths-in-readme-files)
* close #1411
* hyphens -> mdashes in `CODE_OF_CONDUCT.md` 
* remove unnecessary links in `CONTRIBUTING.md`
> docs: use relative links in markdown files

- autotest/TestGeomUtil.f90
- autotest/meson.build
- autotest/tester.f90
- make/makefile
- msvs/mf6core.vfproj
- msvs/mf6lib.vfproj
- src/Utilities/GeomUtil.f90
- src/meson.build
- utils/mf5to6/make/makefile
* add `GeomUtilModule` with `point_in_polygon()` function
* unit test rectangular cell interior/exterior and edge cases (vertices/faces)
* ported from Javascript solution https://stackoverflow.com/a/63436180/6514033
* for use by PRT to check particle release point coordinates with cell IDs &mdash; boundary points are included
* accepts one point, could be reimplemented to support arrays like [flopy](https://github.com/modflowpy/flopy/blob/4ed68a2be1e6b4f607e27c38ce5eab9f66492e3f/flopy/utils/geometry.py#L837) but not yet needed and approach would need modification to include edge cases I think
> feat(GeomUtil): add geometry module with point_in_polygon utility

- DEVELOPER.md
- environment.yml
* new bmipy release is out, compatible with python3.12: https://github.com/csdms/bmi-python/issues/19#event-10771075714
* mention macOS classic linker workaround for Xcode 15 in `DEVELOPER.md`, [more info](https://github.com/mesonbuild/meson/issues/12282)
* update macOS gcc install examples to use latest (13)
> chore: unpin python<=3.11, mention Xcode 15 workaround in dev docs

- autotest/simulation.py
- autotest/test_gwf_sfr01gwfgwf.py
- autotest/test_gwt_sft01gwtgwt.py
* fix sfr gwtgwt test to add mover to exchange files
> ci: add simple gwfgwf exchange model with sfr mover

- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3drn8.f90
- src/Model/GroundWaterFlow/gwf3evt8.f90
- src/Model/GroundWaterFlow/gwf3ghb8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3rch8.f90
- src/Model/GroundWaterFlow/gwf3riv8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterFlow/gwf3wel8.f90
- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/GroundWaterTransport/gwt1src1.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/ModelUtilities/PackageMover.f90
- src/Model/NumericalModel.f90
- src/Solution/NumericalSolution.f90
and possibly more resets to follow
> rfct(model_reset): add model_reset for package movers

- autotest/TestGeomUtil.f90
- src/Utilities/GeomUtil.f90
There were a few bugs in the `point_in_polygon()` routine added in #1407 (off-by-n errors and premature termination). The test included in that PR was only a very basic case (unit square) and so did not catch these. Fix the issues and add test cases for other geometries:
* triangle
* irregular pentagon
Tests are also refactored a bit for easier future expansion and nicer messages on failure
> fix(GeomUtil): fix point_in_polygon, expand unit tests

- autotest/conftest.py
* removed from devtools in https://github.com/MODFLOW-USGS/modflow-devtools/pull/124
> test: move get_version fn to conftest.py from devtools

- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/TransportModel/tsp1.f90
- src/Model/TransportModel/tsp1oc1.f90
Relates to:
#1386
#1391
#1392
#1396
#1398
#1399
#1400
#1428
-Anticipated to be the last piece of #1306 (closed without merging) now redone in the PRs cited above and including this PR.
-fprettify
> refactor(tsp1.f90): move code from gwt1.f90 to tsp1.f90

- .gitignore
- autotest/meson.build
* test-drive has limited intel compatibility, limit it to gnu builds for now
* needs ifort <= 2021.6 on linux and mac
* link errors on windows (all versions AFAICT)
* add `.DS_Store` to `.gitignore`
> refactor: disable test-drive dependency with intel compilers

- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/ModelUtilities/DiscretizationBase.f90
* use compact format for docstrings in discretization types
* remove unneeded `return` statements at the end of routines
* move `use` statements used multiple times to module scope
> chore(discretization): cleanup docstrings in DIS/DISV/DISU

- utils/idmloader/scripts/dfn2f90.py
* use vars for paths
* remove unused imports
* run black/isort
> refactor(dfn2f90): factor out paths

- autotest/conftest.py
- autotest/test_gwf_csub_distypes.py
- autotest/test_gwf_returncodes.py
- autotest/test_gwt_mt3dms_p01.py
- autotest/test_z03_examples.py
- autotest/test_z03_largetestmodels.py
* update `autotest/conftest.py` and test scripts to
* fail tests if development binaries not found
* warn if downloaded or rebuilt binaries not found
* allow testing to proceed even without all downloaded/rebuilt binaries
* motivated by test failures in https://github.com/MODFLOW-USGS/executables/pull/22
> test: require dev exes, warn/skip if download/rebuilt not found

- .gitattributes
This applies a few [overrides](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md) to configure github-linguist, marking (and excluding) documentation and re-classifying `*.inc` as Fortran files (not C++). Autotests are kept (as I guess is expected?). The new breakdown is:
```bash
$ github-linguist
76.57%  8244554    Fortran
22.90%  2465281    Python
0.27%   29321      Meson
0.22%   23329      Makefile
0.04%   4375       Shell
```
> refactor(.gitattributes): Configure github-linguist

- autotest/TestArrayHandlers.f90
- src/Utilities/ArrayHandlers.f90
* support expanding 1D logical arrays (for use by PRT)
* expand tests to check both resizing and copying of existing elements
* use compact docstring format, remove unneeded return statements
> feat(ArrayHandlers): support 1D logical array resizing, add tests

- make/makefile
- msvs/mf6core.vfproj
- msvs/mf6lib.vfproj
- src/Model/Connection/ConnectionBuilder.f90
- src/Model/Connection/GridConnection.f90
- src/Solution/NumericalSolution.f90
- src/Utilities/ArrayHandlers.f90
- src/Utilities/DevFeature.f90
- src/Utilities/ErrorUtil.f90
- src/Utilities/List.f90
- src/Utilities/Sim.f90
- src/Utilities/genericutils.f90
- src/meson.build
- utils/mf5to6/make/makefile
- utils/mf5to6/msvs/mf5to6.vfproj
- utils/mf5to6/pymake/extrafiles.txt
- utils/zonebudget/make/makefile
- utils/zonebudget/msvs/zonebudget.vfproj
- utils/zonebudget/pymake/extrafiles.txt
* remove `SimModule` dependency and `sim_message()`/`stop_with_error()` usages
* minimize dependencies of generic utilities on simulation modules so latter can use former without circularity
* on programmer error, just print error message and `error stop 1`
* use `associated(x, y)` as default `isEqual` procedure for `ContainsObject`
* more descriptive docstrings, use compact format
> refactor(ListModule): trim dependencies, add defaults, improve docstrings

- autotest/TestMathUtil.f90
- autotest/meson.build
- autotest/tester.f90
- make/makefile
- msvs/mf6core.vfproj
- src/Utilities/MathUtil.f90
- src/meson.build
* add `mod_offset()` interface (supports int/double) for use by PRT
* reference: https://en.wikipedia.org/wiki/Modulo#Modulo_with_offset
* dovetails with #1446, both introduce new `MathUtilModule` for math-related utilities
> feat(MathUtil): add generic routine for modulo with offset

- src/Timing/tdis.f90
- src/Utilities/Constants.f90
- Also, converted what looks like an old MF2K5 style (or earlier?) function into MF6 style.  
- Moves some constants specified in tdis to the Constants module
> chore(tdis.f90): cleanup docstrings in tdis class

- .github/workflows/compilers.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
Revert `upload-artifact` and `download-artifact` from v4 to v3 for now, v4 has issues https://github.com/actions/download-artifact/issues/249
> ci: revert to upload/download-artifact v3

- autotest/common_regression.py
- autotest/framework.py
Minor maintainability work, all non-functional changes from the tests' perspective
* fold `run_main_model` and `run_comparison_model` into `run_simulation` method
* factor methods out of framework into standalone functions
* pass more args explicitly to member methods
* remove limit on 2 simulations/models
* update docstrings and type hints
This is with a view to
- support for any number of reference/comparison simulations
- explicit workspace configuration, eliminating implicit dependencies
- further deduplication via autodiscovery of tests from named hook functions?
> test: more autotest framework refactoring

- autotest/common_regression.py
- autotest/framework.py
- autotest/test_gwf_mf6io_app2_examples_distypes.py
* https://github.com/MODFLOW-USGS/modflow6-testmodels/pull/10
* remove support for testmodel `*.cmp` reference solution files
* support for mf2005/etc comparisons preserved
* fix default mf6 regression executable selection
* misc cleanup
> test(framework): drop support for *.cmp file comparisons

- autotest/common_regression.py
- autotest/framework.py
- autotest/test_gwf_csub_zdisp01.py
- autotest/test_gwf_npf01_75x75.py
- autotest/test_gwf_sfr01gwfgwf.py
- autotest/test_gwf_sto01.py
- autotest/test_gwf_utl03_obs01.py
- autotest/test_testmodels_mf6.py
* store simulations/models in `TestFramework.sims` as list, not dict
* previously dict was keyed by workspace path &mdash; this prevented e.g. an MF6 sim and non-MF6 model from sharing the same workspace
* run all simulations registered with the framework up front
* previously only the simulation under test ran up front, comparison simulation/model ran just before compare time
* exceptions: mf6 regression and libmf6 (planning to clean up further soon)
* obviates "run_only" option for `compare`, so this is removed
* decouples registered simulations from comparisons, allows tests involving multiple simulations (e.g. for PRT where GWF runs first, then PRT consumes flows via FMI)
* one consequence is that all non-MF6 models registered with the framework must specify `exe_name` (from …
> test(framework): run simulations up front, tweak options

- src/Model/ModelUtilities/FlowModelInterface.f90
In #1332, wherein some code originally appearing in `tsp1fmi1.f90` was moved to `FlowModelInterface.f90`, the line of code pointed to in the screen grabs below didn't survive the move.  As a result, I was getting some messaging printed to console that was throwing me for a loop while debugging GWE.  That is, when some code in an exchange was being defined it was being reported that "FLOWS ARE ASSUMED TO BE ZERO."  However, that's not the case.  This PR seeks to restore the `if` statement indicated in the screen grabs which should lead to better messaging.  I may be missing something, though?  Also interested in see what the ci comes back with.  This change shouldn't impact any of the autotests.
Original code (prior to #1332):
New code (after #1332) is missing the line in question:
> fix(FlowModelInterface.f90): re-install if statement for proper messaging

- autotest/test_gwfgwf.py
- doc/ReleaseNotes/develop.tex
- src/Exchange/GwfGwfExchange.f90
* Fix budget error that occurs when a constant-head lives on the border of a GWF-GWF Exchange
* Add test for both classic and interface model (this should hopefully cover parallel case)
* close #1529
> fix(gwfgwf): budget error when chd lives on border of exchange

- autotest/common_regression.py
- autotest/conftest.py
- autotest/framework.py
- autotest/test_gwf_csub_zdisp01.py
- autotest/test_gwf_errors.py
- autotest/test_gwf_lakobs01.py
- autotest/test_gwf_maw01.py
- autotest/test_gwf_maw02.py
- autotest/test_gwf_maw03.py
- autotest/test_gwf_maw04.py
- autotest/test_gwf_npf01_75x75.py
- autotest/test_gwf_returncodes.py
- autotest/test_gwf_sto01.py
- autotest/test_gwf_tdis.py
- autotest/test_gwf_uzf_surfdep.py
- autotest/test_gwf_zb01.py
- autotest/test_gwt_mt3dms_p01.py
- autotest/test_gwt_mvt02fmi.py
- autotest/test_gwt_prudic2004t2fmi.py
- autotest/test_gwt_prudic2004t2fmiats.py
- autotest/test_gwt_ssm01fmi.py
- autotest/test_gwt_ssm04fmi.py
- autotest/test_gwt_ssm06.py
- autotest/test_gwt_ssm06fmi.py
- autotest/test_gwt_zb01.py
- autotest/test_testmodels_mf5to6.py
* use dict for targets instead of `Executables` from devtools (to be deprecated?)
* organization and cleanup in framework and common regression utility functions
> test(framework): simplify targets fixture, minor cleanup

- DEVELOPER.md
* basic description of test framework conventions
* could expand &mdash; detail available in docstrings
> docs(dev docs): add autotest framework section to DEVELOPER.md

- autotest/TestList.f90
- autotest/meson.build
- autotest/tester.f90
* add a few exploratory unit tests written during other work
> test(List): add minimal unit tests for ListType

- .github/workflows/compilers.yml
- distribution/build_dist.py
- distribution/check_dist.py
* fix `build_docs()` usage
* check `meson.options` exists in `check_dist.py`
* minor cleanup
* miscellaneous: only open one compiler compatibility PR at a time
> fix(dist): fix distribution scripts, update validations

- autotest/TestMathUtil.f90
- src/Utilities/MathUtil.f90
* remove implicits as per https://github.com/MODFLOW-USGS/modflow6/pull/1521#issuecomment-1886389518
* define real-valued unary function interface `f1d` for procedure pointer passed by callers
> refactor(MathUtil): remove implicits from root-finding fns

- .github/common/fortran_format_check.py
- src/Utilities/InputOutput.f90
- Started with docstrings cleanup and expanded from there.  
- There was some imported mf2k/mf2k5 style code that was massaged into the new code format (lowercase vars, etc.).  
- There remains a number of `go to` statements that would be nice to remove in the future.  
- Ran fprettify
> chore(InputOutput.f90): cleanup docstrings in IO utility

- distribution/build_docs.py
* pass `overwrite` so PDF not recreated from latex if already exists
> ci(dist): fix build_docs() usage in build_dist.py

- autotest/test_gwfgwf.py
- autotest/test_gwt_henry_gwtgwt.py
Any tests that use dev_ options need to be marked with developmode.  These two tests now use dev_interfacemodel_on, so they need to be explicitly marked.
> ci(developmode): dev_interface tests need to be marked with developmode

- distribution/check_dist.py
* only require strictly numeric version string for approved releases
> ci(dist): fix check_dist.py version string validation

- .github/workflows/release_dispatch.yml
* it can be convenient to manually dispatch directly from `develop` e.g. to test the release procedure or create a release without first pushing a new branch
* still prohibit releasing from `master`
> ci(dist): allow release workflow dispatch from develop branch

- .github/workflows/release.yml
* `meson.options` was accidentally omitted when zipping
* unzip and validate the archive created, not just distribution directory
> ci(release): include meson.options in archive, validate archive itself

- .github/workflows/docs.yml
- .github/workflows/large.yml
- .github/workflows/release.yml
* https://github.com/MODFLOW-USGS/modflow6-examples/pull/137 changed how pytest is invoked to build models, update usages
* fix broken [nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/7620227867/job/20755460522)
> ci: fix example model init per upstream

- meson.build
* makes the `autotest/` subdirectory of the proj root optional
* motivated by the distribution which doesn't contain autotests
> refactor(meson.build): check for autotest/ before calling subdir()

- .github/workflows/ci.yml
- .github/workflows/release_dispatch.yml
- CITATION.cff
- distribution/update_version.py
* remove reset step from `release.yml`, since dev version is not always known it can be done manually
* validate `CITATION.cff` in `ci.yml` linting job
* support `--citation` (short `-c`) option for `update_version.py` to make citation from `CITATION.cff`
* use above in `release.yml` to add citation to release notes
* close #1588
> ci: remove release reset step, validate cff, make citation from cff

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/appendixA.tex
- doc/ReleaseNotes/develop.tex
- doc/ReleaseNotes/previous/v6.4.3.tex
- src/Model/GroundWaterFlow/gwf-mvr.f90
* A changed introduced in #1427 resulted in a performance decrease for GWF models with a large number of water movers.  This PR reduces the number of lookups by resetting mapped ids only when the set of movers has changed.
* This PR also resets the release notes for the next release.
> fix(mvr): improve water mover performance

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/large.yml
- .github/workflows/release.yml
* if CI tests fail it can be helpful to inspect their outputs
* add `workflow_dispatch` trigger to `large.yml`
* miscellaneous cleanup
> ci: upload test artifacts on failure

- autotest/get_exes.py
* relevant to https://github.com/MODFLOW-USGS/modflow6/pull/1612
* v15 of executables distribution doesn't have double-precision program versions
* temp workaround until mf2005/mfnwt/etc comparisons replaced with mf6 regression
> test: use v14 of executables distribution

- .github/workflows/compilers.yml
* previously triggered on push/PR to master or release branch
* weekly schedule and manual trigger are sufficient
> ci: don't trigger compiler checks on push or PR

- autotest/conftest.py
- autotest/framework.py
- autotest/test_gwf_csub_zdisp01.py
- autotest/test_gwf_npf01_75x75.py
- autotest/test_gwf_sto01.py
* skip, don't crash/fail tests if downloaded programs or rebuilt regression mf6 programs not found
* only require local development binaries to gracefully run autotests
> test: make downloaded and rebuilt programs optional

- autotest/get_exes.py
* double precision mf2005, mfnwt, mflgr and mfusg are back in [exes dist v16](https://github.com/MODFLOW-USGS/executables/releases/tag/16.0)
> test: remove executables v14 workaround from 7bc29b7

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
* following up on https://github.com/MODFLOW-USGS/modflow6/discussions/1286
* add `macos-14` (M1 runner) to the matrix in `release.yml`
* use devtools `ostags` module instead of hard-coding OS tags
* enabled by https://github.com/MODFLOW-USGS/modflow-devtools/pull/139
* test run: https://github.com/wpbonelli/modflow6/actions/runs/7950956265
* when this merges, a `macarm.zip` asset will become available on the nightly build &mdash; since `release.yml` is reused by the full release procedure, we shouldn't need further modification here to include an ARM build in the next official release, however the exes distribution will
* miscellaneous: remove unused inputs to `release_dispatch.yml`
> ci(release): add distribution for apple silicon

- autotest/test_gwf_sfr_inactive.py
- src/Model/GroundWaterFlow/gwf-sfr.f90
* add test that replicates test model provided in issue #1585
closes #1585
> fix(sfr): resolve divide by zero issue

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
* followup to #1625 which was misguided because intel compilers can't create ARM binaries
* statically linked build with gfortran
* link static `libgfortran` and `libquadmath` by hiding dylibs
* `-static*` flags don't seem to work on macOS
* luckily homebrew gcc includes static libs
* set `LDFLAGS` for macos >= 13 &mdash; https://github.com/MODFLOW-USGS/modflow6/blob/develop/DEVELOPER.md#macos
> ci(release): add gfortran build for ARM macs

- make/makefile
- msvs/mf6core.vfproj
- src/Model/GroundWaterEnergy/gwe-cnd.f90
- src/Model/GroundWaterFlow/gwf-npf.f90
- src/Model/GroundWaterTransport/gwt-dsp.f90
- src/Utilities/HGeoUtil.f90
- src/meson.build
* move function for effective horizontal hydraulic conductivity out of `gwf-npf.f90` so gwt-dsp and gwe-cnd don't depend on gwf-npf &mdash; toward eliminating dependencies between models
* introduce `HGeoUtilModule` for standalone hydrogeologic functions
* split out from #1532
* part of #1491
> refactor: move hyeff function to separate module

- .github/workflows/large.yml
* revert part of [2f52a23](https://github.com/MODFLOW-USGS/modflow6/commit/2f52a232a845a694ba00080f0e08445bd5cd47bd)
* fixes large model test CI
* I don't know why I did this, we should wait until ifx can pass the full test suite before we CI test with it
> ci: don't test large models with ifx

- autotest/framework.py
* base workspace was selected where sim/model-specific workspace should have been
* only collect expected output files if comparison is enabled
* thanks @emorway-usgs for discovering
* a lot of these complications will go away with snapshot testing
> test(framework): fix workspace selection and comparison logic

- autotest/pytest.ini
- autotest/test_gwe_esl_analyt_sln.py
- autotest/test_gwe_lke_conduction.py
- autotest/test_gwe_split_analyt.py
- autotest/test_gwf_sfr_npoint01.py
- autotest/test_gwf_sto03.py
- autotest/test_prt_voronoi1.py
- autotest/test_prt_voronoi2.py
* ignore well-known `python-dateutil` and `pandas` warnings
* use `.item()` to extract single items from numpy arrays
* mark PRT voronoi tests slow (todo: refactor, speed up)
* use raw docstrings if they contain backslashes
There are a few more warnings to clean up, either directly from flopy or indirectly via numpy or matplotlib
```
matplotlib/quiver.py:649: RuntimeWarning: divide by zero encountered in scalar divide
length = a * (widthu_per_lenu / (self.scale * self.width))
```
```
flopy/mf6/data/mfdataplist.py:1092: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
data_frame = pandas.read_csv(
```
```
flopy/utils/geometry.py:871: RuntimeWarning: invalid value encountered in divide
tmp = polygon[i][0] + …
```
> test: avoid warnings from 3rd party libs, misc cleanup

- autotest/test_prt_budget.py
- autotest/test_prt_disv1.py
- autotest/test_prt_drape.py
- autotest/test_prt_exg.py
- autotest/test_prt_fmi.py
- autotest/test_prt_release_timing.py
- autotest/test_prt_stop_zones.py
- autotest/test_prt_ternary_methods.py
- autotest/test_prt_track_events.py
- autotest/test_prt_triangle.py
- autotest/test_prt_voronoi1.py
- autotest/test_prt_voronoi2.py
- autotest/test_prt_weak_sinks.py
* followup to #1670
* fix test name in `test_prt_drape.py`
* reuse functions from `test_prt_voronoi1.py` in `..._voronoi2.py`
* hardcode cell IDs in voronoi tests instead of re-intersecting every run
* remove slow markers, tests now run in a few seconds
> test(PRT): refactor/cleanup voronoi DISV grid tests

- .github/actions/test-par-win/action.yml
- .github/actions/test-par/action.yml
- .github/common/compile_modflow6.bat
- .github/common/compile_petsc.sh
- .github/common/configure_petsc.sh
- .github/common/install_intel_windows.bat
- .github/common/test_modflow6.bat
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- autotest/framework.py
- meson.build
CI test mf6 parallel on Windows. Step toward a Windows parallel distribution.
* use [cygwin approach](https://petsc.org/main/install/windows/#cygwin-gnu-compilers-on-microsoft-windows) to build petsc with `ifort` and `cl`
* factor out actions for parallel testing on windows/non-windows
* factor out scripts for windows steps needing special treatment
* cache oneAPI and PETSc, installing/building is slow
Parallel autotests pass, but there are a couple remaining (but non-blocking) issues
* PETSc `make check` reports some errors, but they don't seem to invalidate the build
* `meson test` fails intermittently on "Parallel simulation test - 2 cores" on Windows, for now it's skipped
@mjr-deltares should these be solved before merging or should we come back to them?
> ci(win/par): add test workflow for parallel mf6 on Windows

- .github/actions/test-par-win/action.yml
- .github/common/test_modflow6.bat
- .github/workflows/ci.yml
* follow up to #1672 
* `libpetsc.dll` wasn't found if PETSc cache miss, maybe interference from cygwin setup? setup PETSc environment after building PETSc to workaround
* simplify `ONEAPI_ROOT` usages
> ci(parallel): fix windows parallel mf6 workflow

- .github/workflows/ci.yml
- autotest/test_swf_dfw_bowl.py
* probably want to maintain compatibility until version EOL
* catch syntax usages only supported on newer versions
* raised in https://github.com/MODFLOW-USGS/modflow6/pull/1673#discussion_r1527624056
* update print format syntax in `test_swf_dfw_bowl.py`
> ci: test oldest supported python (currently 3.9)

- autotest/test_prt_budget.py
- src/Solution/ParticleTracker/Method.f90
- src/Solution/ParticleTracker/MethodCellPollock.f90
- src/Solution/ParticleTracker/MethodCellPollockQuad.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodDis.f90
* conditions to determine whether particle should continue advancing were not independent, use `if` not `else if` so they are evaluated independently &mdash; flushed this bug out while working on https://github.com/MODFLOW-USGS/modflow6-examples/pull/161
* set `cell` when initializing subcell methods &mdash; not currently needed, but might be in future, and probably best to set ptr for consistency
* minor cleanup in `test_prt_budget.py`
> fix(PRT): fix conditionals controlling particle advance within cell

- .github/workflows/release.yml
previously hardcoded which [broke the nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/8406278240/job/23019998994#step:14:60)
> ci(parallel): use GITHUB_WORKSPACE for petsc dll path

- autotest/test_swf_dfw.py
- autotest/test_swf_dfw_beg2022.py
- autotest/test_swf_dfw_bowl.py
- autotest/test_swf_dfw_gwf.py
- autotest/test_swf_dfw_loop.py
- autotest/test_swf_dfw_swrt2.py
- autotest/test_swf_dfw_swrt2b.py
- autotest/test_swf_dfw_swrt2dis.py
- autotest/test_swf_vcatch.py
- doc/mf6io/mf6ivar/dfn/swf-dfw.dfn
- doc/mf6io/mf6ivar/md/mf6ivar.md
- doc/mf6io/mf6ivar/tex/swf-dfw-desc.tex
- doc/mf6io/mf6ivar/tex/swf-dfw-griddata.dat
- src/Idm/swf-dfwidm.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
Slope does not need to be an input parameter in DFW.  It can be calculated from the elevations in the DIS packages.
> refactor(swf-dfw): remove slope as input variable

- autotest/test_prt_voronoi1.py
- src/Model/ParticleTracking/prt-oc.f90
- src/Solution/ParticleTracker/CellDefn.f90
- src/Solution/ParticleTracker/CellPoly.f90
- src/Solution/ParticleTracker/CellRect.f90
- src/Solution/ParticleTracker/CellRectQuad.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodDis.f90
- src/Solution/ParticleTracker/MethodDisv.f90
Performance issue discovered while working on https://github.com/MODFLOW-USGS/modflow6-examples/pull/161. Previously cell definition arrays (face flows, face neighbors, etc) were reallocated for each subcell regardless of tracking method. This introduced overhead for each subcell solve, scaling with the total particle count.
Probably unnoticed until now because a) autotests have fairly low particle counts and b) the initial draft of MP7 example P01 used a smaller number of particles for debugging.
Reallocation can be skipped for structured grids since subcells are guaranteed to be 4-sided, and can happen lazily for unstructured grids.
Removing the unnecessary allocations speeds up the PRT model in the example from a minute or more to subsecond runtime on my machine
> perf(PRT): allocate cell defn arrays lazily

- .github/actions/build-par-win/action.yml
- .github/actions/build-petsc-win/action.yml
- .github/actions/setup-par-oneapi/action.yml
- .github/actions/test-par-win/action.yml
- .github/workflows/large.yml
* factor out an action `build-petsc-win` to build/cache PETSc
* warm the PETSc cache nightly like we do for oneAPI
* cut ~15min off parallel windows CI time, [example](https://github.com/MODFLOW-USGS/modflow6/actions/runs/8524618515/job/23349879474#step:5:125)
> ci(parallel): factor out petsc action, save petsc cache nightly

- .github/workflows/large.yml
* only need to cache intel-classic 2021.7 and intel 2024.0
> ci: trim cached oneapi versions

- .github/workflows/compilers.yml
* add intel 2024.0 and 2024.1 to compiler test matrix
* remove incompatible intel versions 2021.1 - 2022.1
* remove gcc 7 - 10
> ci(compilers): add intel 2024, trim intel versions, drop gcc 7-10

- autotest/test_prt_disv1.py
- src/Model/ModelUtilities/TrackData.f90
- src/Model/ParticleTracking/prt.f90
- src/Solution/ParticleTracker/Method.f90
- src/Solution/ParticleTracker/MethodCellPassToBot.f90
- src/Solution/ParticleTracker/MethodCellPollock.f90
- src/Solution/ParticleTracker/MethodCellPollockQuad.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodDis.f90
- src/Solution/ParticleTracker/MethodDisv.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
Fix two issues:
* maximum tracking time was set incorrectly, particles were solved beyond the end of the time step for multi-step simulations &mdash; max time within the tracking loop should be end of time step unless it's the last time step in the simulation, in which case it should be particle stop time
* if, on recording a particle datum, the tracking time fell exactly on the boundary between time steps, the datum was assigned to the subsequent time step and stress period, while MODPATH 7 assigns it the previous &mdash; factor out a routine in the base `MethodType` to save particle data, with some extra logic for an inclusive upper bound on the time step like MP7
> fix(prt): set tmax properly before particle solve

- autotest/test_gwf_ats_lak01.py
- doc/ReleaseNotes/develop.tex
- src/Model/GroundWaterFlow/gwf-lak.f90
- src/Model/GroundWaterFlow/gwf-maw.f90
- src/Model/GroundWaterFlow/gwf-mvr.f90
- src/Model/GroundWaterFlow/gwf-sfr.f90
- src/Model/GroundWaterFlow/gwf-uzf.f90
- src/Model/GroundWaterFlow/gwf.f90
- src/Model/GroundWaterTransport/gwt-ist.f90
- src/Model/ParticleTracking/prt.f90
- src/Model/SurfaceWaterFlow/swf.f90
- src/Model/TransportModel/tsp-apt.f90
- src/Model/TransportModel/tsp-mvt.f90
- src/Model/TransportModel/tsp.f90
- src/Utilities/Budget.f90
- src/Utilities/BudgetObject.f90
- utils/zonebudget/src/zoneoutput.f90
* add and require a finalize_step method for the budget object
* cumulative terms are calculated only when the finalize_step method is called
* required adding calls to budget%finalize_step() before any budget_ot() calls were made
* add test to ensure cumulative budget is correct for an ats test with failed steps
> fix(ats-budget): fix cumulative budget for failed/retried ATS timesteps

- autotest/test_swf_dfw_loop.py
- doc/mf6io/mf6ivar/dfn/swf-dfw.dfn
- make/makefile
- msvs/mf6core.vfproj
- src/Idm/swf-dfwidm.f90
- src/Model/Discretization/Dis2d.f90
- src/Model/Discretization/Disv1d.f90
- src/Model/GroundWaterFlow/gwf-npf.f90
- src/Model/ModelUtilities/VectorInterpolation.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
- src/Model/SurfaceWaterFlow/swf.f90
- src/meson.build
* Added coordinate invariant flow calculations by using xt3d-style interpolation of gradient on cell faces to cell center.  This gradient is then averaged to cell faces and used in the denominator of the mannings flow expression.
* Added capability to save overland flow velocities to SWF budget file.  Flows are saved when SAVE_VELOCITY keyword is added to the SWF-DFW options block.
* added DEV_SWF_CONDUCTANCE option to SWF-DFW package to allow testing of the SWF model using the flow expression implemented in the SWR Process for MODFLOW-2005.
> patch(swf): coordinate invariant flow calculations

- .github/workflows/ci.yml
- .github/workflows/compilers.yml
- .github/workflows/docs.yml
- .github/workflows/large.yml
- .github/workflows/pixi_auto_update.yml
- .github/workflows/release.yml
* pin pixi version to [0.19.1](https://github.com/prefix-dev/pixi/releases/tag/v0.19.1)
* bump setup-pixi to [0.5.2](https://github.com/prefix-dev/setup-pixi/releases/tag/v0.5.2)
* avoid breaking changes while pixi matures &mdash; pinning the action alone leaves us exposed to regressions in pixi itself
* discussed offline with @langevin-usgs @jdhughes-usgs @mjr-deltares
> ci(pixi): pin pixi version to 0.19.1 for now

- distribution/build_dist.py
- distribution/build_docs.py
- distribution/build_makefiles.py
- distribution/check_dist.py
- distribution/update_version.py
- pixi.lock
* use `no_parallel` marker in distribution tests
* update devtools and flopy versions in `pixi.lock`
> test(distribution): use no_parallel marker for dist tests, update pixi.lock

- .github/workflows/ci.yml
Up to now we only test ARM mac as part of the release workflow. We should probably test in standard CI.
> ci: add test job for arm mac with gfortran

- autotest/framework.py
Showing the end of the list file in case of simulation failure makes CI logs extremely verbose, making it difficult to scroll/read. We upload failed test outputs as artifacts, so the list file can be inspected that way if needed.
> test(framework): remove verbose warnings on simulation failure

- src/Model/GroundWaterFlow/gwf-uzf.f90
* 9 uzf variables had counterparts in uzf%uzfobj with the same memory path
* renamed the uzf package variables by adding _pvar to them
* close #1741 
This does not fix underlying memory problems with UZF.  Instead it is a simple way to avoid multiple uzf variables with the same memory path.  A proper fix will require additional work as the variable contents in uzf and uzf%uzfobj are not the same.
> fix(uzf): rename uzf package variables to avoid name clashes

- src/Utilities/Idm/InputLoadType.f90
- src/Utilities/Idm/mf6blockfile/IdmMf6File.f90
Issue introduced in PR #1610.
- This PR moved iper/ionper to dynamic loader base class
- There are 2 contexts (loaders) for stress data- an input style specific block loader (e.g. list, array) and the generic dynamic loader that manages the load and allocates the input style loader.  These were both allocating iper/ionper via the base class.
- Fix is to move iper/ionper back into the higher level dynamic loader.
> fix(idm): stress package loaders allocate duplicate iper/ionper variables

- autotest/test_gwf_sfr_inactive.py
- autotest/test_gwf_sfr_inactive02.py
- src/Model/GroundWaterFlow/gwf-sfr.f90
- src/Utilities/BudgetObject.f90
- src/Utilities/Table.f90
Add evaluation of DHNOFLO value in tables
> fix(sfr): update budget and table output for inactive reaches

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
- distribution/build_dist.py
- distribution/build_docs.py
* allow model selection for docs/dfns/examples in release workflow and dist scripts
* carved out from #1540 
* step toward #1491
* [test run](https://github.com/wpbonelli/modflow6/actions/runs/8754006064)
> ci(release): support model selection for docs/dfns/examples

- .github/workflows/release.yml
- autotest/get_exes.py
- distribution/build_dist.py
* fix [nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/8761942029/job/24049761871#step:19:35) broken by #1746
*  can't assume models will be explicitly provided, would otherwise need to set default value for `models` workflow input
* fix example filtering in `build_dist.py`, use `rmtree` not `unlink`
* [test run](https://github.com/wpbonelli/modflow6/actions/runs/8767647217) with gwf only &mdash; also, we still need to support model selection for mf6-examples repo, if we want to avoid rebuilding the examples document in `release.yml`
* unrelated: remove old workaround from `autotest/get_exes.py`
> ci(release): fix model selection options for dist scripts

- src/Utilities/TimeSeries/TimeSeriesManager.f90
This should be done now. I ended up keeping the search loop and instead skip it when the time series file is for a boundary condition. My reasoning is that I spent all my time evaluating its application in the CHD and GHB packages and not their auxiliary variables. Just to be safe, I will let it do that for the aux time series files but skip for the boundary time series files.
I ran through each of Richard Winston's examples and get the same answer with a substantial speedup. In particular, the million time series file example reduced the runtime from 19 hours to 3 minutes!
commit message:
The subroutine read_value_or_time_series checks to see if a time series file (TS) has been previously included in the time series manager (tsManager) before adding it.
The check compares against the …
> refactor(ts): skip search for repeated boundary time series file

- autotest/test_prt_stop_zones.py
- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- src/Model/ParticleTracking/prt-prp.f90
Optional support for local z coordinates. This allows positioning particles based on the water table. The motivations here are 1) modpath 7 parity and 2) to provide the same capabilities whether prt is running alongside a gwf model or as a post-processor. Previously dynamic positioning was possible only if prt runs as a post-processor.
Motivated by https://github.com/MODFLOW-USGS/modflow6-examples/pull/171.
> feat(PRT): localz option for particle release point package

- autotest/test_gwe_drycell_cnd0.py
test_gwe_drycell_cnd0.py was reportedly having issues passing on an M1 chip with numbers in 1e-12 range.  This fix cured the `assert` failure.
> fix(test_gwe_drycell_cond0): minor alteration to gwe autotest

- DEVELOPER.md
- src/Idm/sim-namidm.f90
- src/Utilities/Idm/DefinitionSelect.f90
- src/Utilities/Idm/IdmLoad.f90
This PR addresses the error below.  This issue can be seen following #1763 which adds a FILEIN style tag to the mfsim.nam options block in support of parallel.
```
ERROR REPORT:
1. IdmLoad allocate simnam param unhandled datatype: RECORD HPC6 FILEIN
HPC6_FILENAME
UNIT ERROR REPORT:
1. ERROR OCCURRED WHILE READING FILE 'mfsim.nam'
```
> fix(idm): allow filein tags in mfsim.nam options block

- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/exg-gwegwe.dfn
- doc/mf6io/mf6ivar/dfn/exg-gwfgwf.dfn
- doc/mf6io/mf6ivar/dfn/exg-gwtgwt.dfn
- src/Exchange/DisConnExchange.f90
- src/Idm/exg-gwegweidm.f90
- src/Idm/exg-gwfgwfidm.f90
- src/Idm/exg-gwtgwtidm.f90
- src/Utilities/Idm/BoundInputContext.f90
- src/Utilities/Idm/DynamicPackageParams.f90
- src/Utilities/Idm/SourceCommon.f90
- src/Utilities/Idm/mf6blockfile/LoadMf6File.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileListInput.f90
- src/Utilities/Idm/mf6blockfile/StructArray.f90
Support binary for any recarray style input block which is regular and contains no text columns
- Includes, for example, DISV cell2d if ncvert is constant
- Includes exchange exchagedata block if BOUNDNAMES is not optioned (#128)
- Not currently supported by FloPy- how to test in ci for now?
> feat(idm): support binary for regular, numeric list input blocks

- .github/common/check_format.py
- .github/common/check_spelling.py
* `Manager()` creates a server process &mdash; [as recommended](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods), avoid starting new processes outside the main function so the module can safely be imported
* avoid EOF errors (only on mac/python3.12?)
> fix(scripts): create shared memory objects in main function

- doc/mf6io/gwt/dsp.tex
A relatively minor alteration to clarify the role of XT3D within the DSP package.  This change parallels a change made in #1781.
> fix(mf6io): apply suggested change to DSP write-up for consistency with CND write-up

- .github/common/check_format.py
- src/Model/ParticleTracking/prt-prp.f90
- src/Model/ParticleTracking/prt.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
- src/Solution/ParticleTracker/Particle.f90
* minimum tracking level used to be 0 (simulation) but this is not necessary, move minimum tracking level to 1 (model) 
* allocate/resize particle arrays with memory manager utils, no longer need special handling for non-standard array bounds
* update exclusions in `check_format.py`
> refactor(prt): move min tracking level to 1, use mem mgr for particle arrays

- autotest/TestGeomUtil.f90
- src/Model/ModelUtilities/DisvGeom.f90
- src/Solution/ParticleTracker/CellDefn.f90
- src/Solution/ParticleTracker/CellRectQuad.f90
- src/Solution/ParticleTracker/CellUtil.f90
- src/Solution/ParticleTracker/MethodDisv.f90
* remove unneeded `get_npolyverts()` routines from `MethodDisv` and `CellDefn`
* refactor routine to get rectangular dimensions/rotation without unneeded args
* rough benchmark comparing `shared_face()` with `shared_edge()` performance
> refactor(prt): misc cleanup/refactoring, benchmark shared face routines

- DEVELOPER.md
* latest ifx (2024.1) supports modflow6 now, update compiler section to reflect this
* show both pixi and native commands for developer tasks
> docs(DEVELOPER.md): mention ifx support, show pixi and native cmds

- autotest/test_prt_notebooks.py
- src/Solution/ParticleTracker/MethodDisv.f90
* give `MethodDisvType` a neighboring `CellDefn`, don't reallocate on each cell-cell transition
* also remove example name workaround in `test_prt_notebooks.py`
> refactor(methoddisv): share nbr defn, avoid reallocation

- autotest/test_gwe_drycell_cnd4.py
- New test ensures that conduction between an advanced package transport (APT) feature (in this case, a stream reach) and a dry host cell is the same with and without the Newton option activated in the GWF name file
- Black
> test(apt): check APT conduction with and without Newton option

- .github/workflows/ci.yml
- .github/workflows/release.yml
On rectangular grids, the generalized particle tracking method can find itself in an endless loop on macOS 14 compiled with gfortran with optimization=2, confirmed with gfortran 11-14.
It's difficult to say where things are going wrong since on ARM macs neither gdb nor lldb can be used so we are stuck with print debugging. An architecture/compiler problem seems plausible since we'd presumably see the same behavior on other platforms with opt=2 if it were our bug, but I'm not sure.
This should not occur typically since rectangular cells are detected and solved with Pollock's method, but we use `dev_forceternary` in `test_prt_disv1.py` to check that the generalized method reduces to Pollock's. The test has been [hanging in CI recently](https://github.com/MODFLOW-USGS/modflow6/actions/runs/91 …
> ci: use -Doptimization=1 for arm mac test and release

- .github/workflows/release.yml
* fix [failing nightly build](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/9152654770/job/25160466230)
> ci(release): fix dylib path to hide on macos-14

- autotest/test_par_gwe_split_analyt.py
- autotest/test_par_gwf_idomain.py
- autotest/test_par_gwf_newton.py
- autotest/test_par_gwf_rewet.py
- autotest/test_par_gwt_adv01.py
- autotest/test_par_gwt_adv02.py
- autotest/test_par_gwt_subset.py
Add the `developmode` marker to parallel tests that reuse models from tests that use dev options
> test: mark some parallel tests developmode

- .github/actions/test-par-win/action.yml
- .github/common/test_modflow6.bat
- .github/workflows/release.yml
- autotest/test_par_gwt_dsp01.py
Apply `not developmode` marker when testing parallel mf6 in `test-par-win` action
* on `master` branch, generally
* if `developmode` is false in the release workflow
> ci: fix developmode parallel test conditions

- doc/mf6io/framework/binaryoutput.tex
This should've been included with #1493 but was overlooked.  Thanks @rbwinst-usgs for catching this oversight in your review of the upcoming MF6 release.
> docs(binaryoutput.tex): include description for gwe model binary output

- doc/mf6io/framework/binaryoutput.tex
- doc/mf6io/prt/prt.tex
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
- src/Utilities/GeomUtil.f90
* add optional `tol` dummy arg to `nudge()` routine in `MethodSubcellTernary`, better dummy arg naming, improve docstring
* use `LENBOUNDNAME` instead of hardcoded 40 in mf6io document
* clarify docstring for `shared_face()` routine in `GeomUtil`
> docs(prt): improve docstrings, use LENBOUNDNAME in mf6io

- distribution/check_dist.py
Remove `break` statement likely leftover from development/debugging, which caused only the first example model to get a test run. This is why the examples script issue addressed by https://github.com/MODFLOW-USGS/modflow-devtools/pull/156, where models were written to `runall.[sh/bat]` in an order which did not respect flow model dependencies, was not caught before.
After this PR, the `runall.[sh/bat]` script will be tested, as well as 3 of the separate example scripts picked at random.
> test(release): fix distribution example script check

- src/Utilities/Idm/IdmLoad.f90
- src/Utilities/Idm/ModelPackageInputs.f90
- src/Utilities/Idm/SourceCommon.f90
Improve error message for input name length violation as reported in #1774.
Updated error report:
```
ERROR REPORT:
1. Input name "LONGLONGLONG_GWF1" exceeds maximum allowed length (16) for
MODELNAME.
2. Input name "LONGLONGLONG_GWF2" exceeds maximum allowed length (16) for
MODELNAME.
3. Exchange has invalid (unrecognized) model name(s): LONGLONGLONG_GWF
LONGLONGLONG_GWF
UNIT ERROR REPORT:
1. ERROR OCCURRED WHILE READING FILE 'mfsim.nam'
```
> refactor(idm): verify and store error based on length of user input names

- distribution/check_dist.py
* need to consider whether necessary to test all individual example scripts too
* logic to pick them randomly was broken, didn't respect gwf model dependencies
> test(release): disable individual example script checks for now

- .github/workflows/release_dispatch.yml
`developmode`, `run_tests` and `models` inputs were not passed to release.yml correctly
> ci(release): fix input parsing in release_dispatch.yml

- distribution/update_version.py
The `update-version` task was getting substituted too
> fix(update_version.py): fix pixi.toml version string substitution

- .github/actions/setup-par-oneapi/action.yml
The Windows parallel distribution was built with Intel Fortran Classic (`ifort`) 2021.11.1 until now. When running PRT models, Win parallel distributions built with this version of the compiler produce a runtime error in `MethodSubcellPool.f90` when the method pool's pointers to tracking methods are deallocated &mdash; evidently a compiler bug?
```
forrtl: severe (153): allocatable array or pointer is not allocated
Image              PC                Routine            Line        Source             
mf6.exe            00007FF6CF304F37  METHODSUBCELLPOOL          26  MethodSubcellPool.f90
mf6.exe            00007FF6CF02D366  PRTMODULE_mp_PRT_         718  prt.f90
mf6.exe            00007FF6CEF1372A  MF6COREMODULE_mp_         173  mf6core.f90
mf6.exe            00007FF6CEF116C2 …
```
> fix: build windows parallel with ifort 2021.12

- .codespell.ignore
- doc/mf6io/gwf/sfr.tex
The codespell 2.3.0 update broke our spellchecks, add "rin" and "checkin" to `.codespell.ignore` and fix a typo in `sfr.tex`
> chore(codespell): update .codespell.ignore, fix spelling in sfr.tex

- .github/workflows/ci.yml
- .github/workflows/release.yml
With gcc 13.3+ (from brew) on ARM macs we get [this](https://github.com/MODFLOW-USGS/modflow6/actions/runs/9417146166/job/25942390320#step:9:505)
```
Undefined symbols for architecture arm64:
"_is_recursive.16.0", referenced from:
___characterstringmodule_MOD_assign_to_charstring in libmf6core.a(Utilities_CharString.f90.o)
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```
It reproduces locally. On inspection of the symbol table, `_is_recursive.16.0` has type "U" (undefined) while there are several others with the same name and different index `_is_recursive.N` which have type "b" (local bss section symbol). Seems like a GCC bug? Maybe worth building from source and digging deeper, but that is not trivial. Falling back to gcc 12 for now.
> ci(macos-14): use gcc12 on macos-14, workaround is_recursive symbol missing

- src/Model/ParticleTracking/prt-prp.f90
- src/Model/ParticleTracking/prt.f90
- src/Solution/ParticleTracker/Particle.f90
* previously checked that z coordinate was within grid before local->global conversion
* unrelated: better routine names for particle and particle store
> fix(prt): calculate global from local z before checking release point

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Based on [this](https://stackoverflow.com/questions/52139192/github-pull-requests-template-not-showing), renamed and moved pr template.  Also made minor modifications to template list of tasks.
> ci(pr-template): modify pr template and move location

- doc/ReleaseNotes/develop.tex
This can wait and rebase after #1866 to avoid conflicts in `doc/ReleaseNotes/develop.tex`
> docs(release): mention #1865 in release notes

- pixi.toml
> ci: add pixi task to fix the format and spelling (fix-style)

- autotest/test_gwf_maw04.py
NumPy 2.0.0 deprecates `np.unicode_` in favor of `np.str_`, see https://numpy.org/devdocs/release/2.0.0-notes.html#numpy-2-0-python-api-removals
___
> test(test_gwf_maw04.py): switch deprecated np.unicode_ -> np.str_

- .github/workflows/ci.yml
- autotest/test_prt_track_events.py
- autotest/test_prt_voronoi1.py
The Voronoi grid generated in `test_prt_voronoi1.py` is slightly different on macos-14 for some reason. I haven't been able to reproduce locally. To workaround, skip the snapshot on macos-14 in CI. Also re-enable intersections instead of hardcoding in the same test (intersections seem faster than they used to be) and drop the "node" column before the comparison of prt and mp7 results in `test_prt_track_events.py`, as this might vary depending which side of a boundary the particle is computed to be on.
___
> test(test_prt_voronoi1.py): intersect cells, skip snapshot in macos-14 ci

- src/Utilities/Idm/mf6blockfile/Mf6FileListInput.f90
Updated error report:
```
ERROR REPORT:
1. Error in list input. Expected numeric value or time-series name, but
found 'tswrong'.
UNIT ERROR REPORT:
1. ERROR OCCURRED WHILE READING FILE 'ts01.wel'
```
With multiple errors:
```
ERROR REPORT:
1. Error in list input. Expected numeric value or time-series name, but
found 'tswrong2'.
2. Error in list input. Expected numeric value or time-series name, but
found 'tswrong'.
UNIT ERROR REPORT:
1. ERROR OCCURRED WHILE READING FILE 'ts01.wel'
```
> fix(idm): set correct file and exit with timeseries read error

- .build_rtd_docs/styleguide.md
In this PR the styleguide has been extended
- The rules have grouped in different sections to which can be linked
- Examples have been added to most of the rules to clarify the intent
> docs(styleguide) Add formatting and explanations to the Style guide 

- .build_rtd_docs/requirements.rtd.txt
- .readthedocs.yml
In a previous commit the requirements.rtd.txt had been removed in favor of creating a pixi rtd environment. However the ReadTheDocs site doesn't support pixi and requires either pip or conda.
This commit restores the requirements.rtd.txt to satisfy that requirement
> fix(rtd) Restore the requirements.rtd.txt file

- distribution/build_dist.py
Temporary hack to exclude backwards tracking examples from the distribution until supported without a Python post-processing step, see https://github.com/MODFLOW-USGS/modflow6-examples/pull/214. That PR should merge first so this is CI tested with the backwards tracking examples.
___
> ci(release): omit backwards particle tracking examples

- .github/PULL_REQUEST_TEMPLATE.md
- msvs/mf6core.vfproj
* in the msvs project filie, the SourceLoad.f90 file needs to be explicitly marked as requiring preprocessing
* includes minor update to pull request template
> fix(msvs): preprocess SourceLoad.F90

- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- src/Model/ParticleTracking/prt-prp.f90
- src/Model/ParticleTracking/prt.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
- src/Solution/ParticleTracker/Particle.f90
Some cleanup in the particle release package. More consistent variable names. Factor out routines to calculate release time and release the particle. Also, add a value 0 -> "default" for the `DEV_EXIT_SOLVE_METHOD` option, and defer the selection of a default root-finding algorithm to the ternary method rather than the PRP package.
___
> refactor(prp): factor out routine for particle release

- autotest/test_swf_dfw_gwf.py
- doc/mf6io/mf6ivar/dfn/exg-swfgwf.dfn
- src/Exchange/exg-swfgwf.f90
- src/Idm/exg-swfgwfidm.f90
- src/Model/SurfaceWaterFlow/swf-zdg.f90
This PR changes the way SWF and GWF models are coupled.  The exchange is now based on a flow expression that uses a dynamically calculated conductance that depends on the upstream head.  The flow expression is linearized using the Newton expansion and smoothing is used to help with convergence.  The zero-depth gradient (ZDG) package was modified to use a smoothed depth, which improves convergence for example problems.  Tests are under development and will be included in a separate pull request.
> feat(swf-gwf): generalize and improve SWF-GWF Exchange

- doc/mf6io/prt/oc.tex
Previously the PRT OC section of mf6io did not describe tracking events beyond the enumeration substituted in from DFN files. Thanks @mnfienen for the suggestion and review. The new section has also been reviewed/edited by @aprovost-usgs.
___
> docs(prt-oc): add subsection describing tracking events

- distribution/build_dist.py
Update the MF6 examples zipfile name in `distribution/build_dist.py`, as per https://github.com/MODFLOW-USGS/modflow6-examples/pull/217.
___
> chore(scripts): update mf6 examples zipfile name in build_dist.py

- autotest/TestTimeStepSelect.f90
- autotest/meson.build
- autotest/tester.f90
- make/makedefaults
- make/makefile
- msvs/mf6core.vfproj
- src/Model/GroundWaterFlow/gwf-oc.f90
- src/Model/GroundWaterTransport/gwt-ist.f90
- src/Model/ModelUtilities/TimeStepSelect.f90
- src/Model/ParticleTracking/prt-oc.f90
- src/Model/SurfaceWaterFlow/swf-oc.f90
- src/Model/TransportModel/tsp-oc.f90
- src/Utilities/OutputControl/OutputControl.f90
- src/Utilities/OutputControl/OutputControlData.f90
- src/Utilities/OutputControl/PrintSaveManager.f90
- src/meson.build
- utils/mf5to6/make/makedefaults
- utils/mf5to6/make/makefile
- utils/zonebudget/make/makedefaults
- utils/zonebudget/make/makefile
In the spirit of `TimeSelect`, factor out a module and type `TimeStepSelect` for time step selections. This simplifies `PrintSaveManager` which can compose two of the latter. Add unit tests. Cleanup docstrings, comments, and style in base and concrete OC types.
This can also be used by PRT, to come in a separate PR which cleans up particle release logic.
___
> refactor(oc): introduce module/type for time step selection

- .github/actions/test-extended/action.yml
- meson.build
Separate logic for parallel and extended builds. Previously a netcdf dependency was declared even for a parallel-only (not extended) build. This can cause issues if meson detects a netcdf that has been improperly installed or incompletely setup as seems to now be the case on Mac CI runner images
___
> fix(meson.build): separate parallel/extended dependencies

- doc/mf6io/gwe/namefile.tex
Per @rbwinst-usgs's #1916, mention of the `MVE` package was missing from a table that listed which packages are available to the GWE model.  The table in question is located in the description of the namefile for the GWE model.
> doc(namefile.tex): mention of mve package was missing in gwe namefile table

- doc/mf6io/prt/mip.tex
MIP options block was omitted from structure of blocks section.
___
> doc(mf6io): fix PRT MIP section in IO guide

- autotest/TestTimeStepSelect.f90
- src/Model/ModelUtilities/TimeStepSelect.f90
#1923 introduced a module/type for time step selections, with a `log()` routine to handle logging of selected steps. This routine did not work properly when selecting multiple time steps with different keyword options (as supported by OC period-block settings). To restore the desired logging behavior, switch exclusive to inclusive conditionals, and reorder the conditions to preserve the original order of lines written to the list file. Also add a unit test for multiple selections.
___
> fix(oc): fix TimeStepSelect logging

- autotest/test_gwf_csub_zdisp02.py
- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/gwf-csub.dfn
- src/Model/GroundWaterFlow/gwf-csub.f90
Fix z-displacement issue with inactive cells when saving z-displacement data, initialize flag_string, add warning if saving delay bed convergence data and delay beds are not included in a simulation, and add a simple csub test that covers the changes.
> fix(csub): fix a few memory issues in csub package

- .github/workflows/ci.yml
- .github/workflows/release.yml
- src/Exchange/exg-gwegwe.f90
- src/Exchange/exg-gwfgwf.f90
- src/Exchange/exg-gwtgwt.f90
- src/Exchange/exg-swfgwf.f90
- src/Model/GroundWaterTransport/gwt-ist.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/TransportModel/tsp-ssm.f90
- src/Utilities/CharString.f90
A modflow6 binary compiled in debug mode fails on most tests due to array bound checking, and in some cases, a compiler error is encountered due to an `is_recursive` symbol error in CharString.  The following two changes allow for gfortran to compile in debug mode and have tests pass.
* allow zero-sized auxvar to be passed properly without array bounds runtime error
* convert charstring routine to recursive to allow operator overloading to work with debug executable
* unpin gcc-12 in ci.yml and release.yml
> refactor(debug):  fix source to allow debug executable to run tests

- src/Utilities/Memory/MemoryContainerIterator.f90
- src/Utilities/Memory/MemoryManagerExt.f90
- src/Utilities/Memory/MemoryStore.f90
Fixes the memory leaks present in the PtrHashTableIterator and PtrHashTable
> fix(mem): address memory leak related to the MemoryStore

- autotest/test_gwe_obs.py
- doc/ReleaseNotes/develop.tex
- src/Model/Connection/GweInterfaceModel.f90
- src/Model/Connection/GwtInterfaceModel.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/TransportModel/tsp-obs.f90
- src/Model/TransportModel/tsp.f90
The mf6io guide appropriately included a section on using the OBS utility with a GWE model; however, support in the MF6 source code was lacking for a TEMPERATURE `obstype`.  This issue was originally pointed out in #1944
> fix(tsp-obs): the OBS utility in GWE not supporting TEMPERATURE keyword

- .github/common/test_modflow6.bat
- .github/workflows/ci.yml
- autotest/test_par_gwf02.py
Skip the slowest parallel test cases on Windows CI. Also don't use xdist to avoid unwanted oversubscription (though we deliberately oversubscribe in the test cases themselves).
TODO: re-enable all autotests for parallel test job, rather than only parallel tests, since we want to make sure the parallel build doesn't regress any serial functionality.
xref https://github.com/actions/runner-images/issues/7320 where many others have reported inexplicably slow Windows runners
___
> ci(parallel): skip test_par_gwf02 cases d-f, no xdist on windows

- src/Utilities/PtrHashTable.f90
- src/Utilities/PtrHashTableIterator.f90
This fixes a compilation issue in the PtrHastTable on the HPC by making the buckets variable public
> (fix) Fix compilation on the HPC

- autotest/test_prt_libmf6_budget.py
- src/Solution/BaseSolution.f90
- src/Solution/ExplicitSolution.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.F90
During development of the particle tracking (PRT) and surface water flow (SWF) models, a new `ExplicitSolutionType` was added to mf6 for models that do not need to be solved as part of a matrix solution.  Instead, the `ExplicitSolutionType` simply asks each model assigned to it to solve itself.  Prior to the changes in the PR, the bmi-xmi extension could only access `NumericalSolutionType` objects, and so PRT did not work with the XMI-level calls through the API.
This PR changes the `getSolution()` function in `mf6bmiUtil.f90` to return a parent `BaseSolutionType` object, rather than the concrete `NumericalSolutionType` object which it did previously.  This means that `getSolution` now returns either a numerical or explicit solution.  To get this to work properly, the `BaseSolutionType` …
> fix(bmi-ems): ExplicitModelSolution for PRT fixed for XMI/API calls

- .github/workflows/ci.yml
- autotest/test_prt_disv1.py
Add jobs to the gfortran test matrix in `ci.yml` to build and test in debug mode. The intent is to catch situations like the one fixed by #1959. To avoid too much CI burden this PR only adds `macos-14` and `ubuntu-22.04` jobs. This seems to add ~15min to total runtime.
___
> ci: add jobs to build/test with gfortran in debug mode

- src/Distributed/MpiRouter.f90
which was causing a problem for the model in issue #1964 
> fix(par): header receive counter was allocated to the wrong size

- doc/ReleaseNotes/develop.tex
- src/Model/GroundWaterFlow/gwf-uzf.f90
On the [FloPy repo](https://github.com/modflowpy/flopy), an [issue was reported that UZF was not writing a message](https://github.com/modflowpy/flopy/issues/2277) to the GWF listing file when it had finished processing UZF's `PACKAGEDATA` block.  A line of code was added to gwf-uzf.f90 to insert the missing line into the standard output file for a GWF model.  A new test isn't needed for this change, however, the following screen grabs were collected from one of the autotests before and after the change to confirm that the expected line is now written.
**Before**:
**After**:
> fix(gwf-uzf): write msg to listing file when UZF finishes processing PACKAGEDATA block

- src/Model/GroundWaterFlow/gwf-uzf.f90
The fix included in this PR looks like it was originally implemented in #1742:
But somewhere along the way was lost and is resulting in the following warning message:
This PR restores the updated variable name in order to turn off the warning message.
> fix(gwf-uzf): variable name NTRAIL should be NTRAIL_PVAR

- src/Exchange/DisConnExchange.f90
- src/Exchange/exg-swfgwf.f90
While compiling MODFLOW on windows using a intel fortran 19.* compiler the error as stated below is produced.
This commit fixes it. It removes the the pointer definition making the variable a reference.
```
FAILED: src/libmf6core.a.p/Exchange_DisConnExchange.f90.obj src/libmf6core.a.p/disconnexchangemodule.mod
"ifort" "-Isrc\libmf6core.a.p" "-Isrc" "-I..\src" "-Isrc\libmf6_external.a.p" "/MTd" "/nologo" "/warn:general" "/warn:truncated_source" "/stand:f08" "/Zi" "/traceback" "/O2" "/fpe:0" "/heap-arrays:0" "/traceback" "/fpp" "/Qdiag-disable:7416" "/Qdiag-disable:7025" "/Qdiag-disable:5268" "/Qdiag-disable:10448" "/Fdsrc\libmf6core.a.p\Exchange_DisConnExchange.f90.pdb" "/module:src\libmf6core.a.p" /Fosrc/libmf6core.a.p/Exchange_DisConnExchange.f90.obj "/c" …
```
> fix(compiler) Fixes a compilation error occurring when using the intel 19.* compiler on windows

- doc/ReleaseNotes/develop.tex
- src/Model/GroundWaterEnergy/gwe-cnd.f90
- src/Model/GroundWaterEnergy/gwe-est.f90
- src/Model/GroundWaterEnergy/gwe-lke.f90
- src/Model/GroundWaterEnergy/gwe-mwe.f90
- src/Model/GroundWaterEnergy/gwe-sfe.f90
- src/Model/GroundWaterEnergy/gwe-uze.f90
In the EST package, inadvertently setting `HEAT_CAPACITY_WATER` and `DENSITY_WATER` to 0.0 results in a divide by zero error.  Error added to the src code and checked manually.  No dedicated test problem added.
> fix(gwe-est): add error checks for user-specified values of 0.0

- .hpc/cray-hovenweep-meson-build.slurm.batch
- .hpc/cray-meson-build.slurm.batch
- meson.build
- src/Utilities/Export/DisNCMesh.f90
- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/DisvNCMesh.f90
- src/Utilities/Export/NCModel.f90
Tested on Hovenweep as described in issue.  Updates to meson build script and slurm batch scripts included.
> fix(netcdf): address export hpc compile issues

- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.F90
Assignments from the result of `string_to_char_array` fail on ARM mac with GNU Fortran when the LHS and RHS are of different lengths. This seems like a compiler bug? Confirmed with gfortran 12-14. Work around it by introducing a subroutine to do the conversion.
@mjr-deltares and I have discussed and determined as a next step to create a minimal reproduction and post on the Fortran discourse forum. I will add a link here once that's done.
This should resolve the modflowapi macOS CI failures.
___
> fix(mf6bmiutil): workaround ARM mac char array assignment issue

- src/Utilities/Export/DisNCMesh.f90
- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/DisvNCMesh.f90
Refactor Fortran reshape functions from model NetCDF exports.  Segfaults were observed in these routines in large models on Denali.
> fix(netcdf): refactor reshape from model exports

- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.F90
Making the assigned-to argument `intent(inout)` resolves the ARM mac + gfortran assignment problem which #1993 originally solved with a subroutine instead of a function call. Thanks to @scharlton2 for the [suggestion](https://github.com/MODFLOW-USGS/modflow6/pull/1993#issuecomment-2293914993).
@mjr-deltares I will still post on the fortran-lang forum at some point to see if anyone has more info on this behavior.
___
> fix(mf6bmiutil): remove subroutine workaround, make args inout

- autotest/test_gwf_libmf6_evt01.py
- autotest/test_gwf_libmf6_ghb01.py
- autotest/test_gwf_libmf6_ifmod01.py
- autotest/test_gwf_libmf6_ifmod02.py
- autotest/test_gwf_libmf6_ifmod03.py
- autotest/test_gwf_libmf6_rch01.py
- autotest/test_gwf_libmf6_rch02.py
- autotest/test_gwf_libmf6_riv01.py
- autotest/test_gwf_libmf6_riv02.py
- autotest/test_gwf_libmf6_sto01.py
- autotest/test_prt_libmf6_budget.py
pytest fails with an error if the autotest suite is run and modflowapi is not installed.  By moving the ModflowApi import into api_func, pytest discovery doesn't fail if modflowapi is not available.  This makes it possible to run the test suite (without the libmf6 tests) even if modflowapi isn't available.
> refactor(modflowapi): move ModflowApi import into api_func

- autotest/test_gwf_tdis.py
Follow up to #1997.  Skip test if xmipy not installed (instead of failing and not running tests)
of the bug fix, change, feature; required for changes that may affect users
> refactor(xmipy): skip test_gwf_tdis if xmipy not installed

- autotest/test_chf_dfw.py
- autotest/test_chf_dfw_beg2022.py
- autotest/test_chf_dfw_bowl.py
- autotest/test_chf_dfw_loop.py
- autotest/test_chf_dfw_swrt2.py
- autotest/test_chf_dfw_swrt2b.py
- autotest/test_chf_dis.py
- autotest/test_chf_dis_fdc.py
- autotest/test_chf_gwf.py
- autotest/test_olf_dfw_swrt2dis.py
- autotest/test_olf_dis.py
- autotest/test_olf_gwf.py
- autotest/test_olf_vcatch.py
- doc/mf6io/mf6ivar/dfn/chf-dis2d.dfn
- doc/mf6io/mf6ivar/dfn/chf-disv1d.dfn
- doc/mf6io/mf6ivar/dfn/olf-dis2d.dfn
- doc/mf6io/mf6ivar/dfn/swf-dis2d.dfn
- doc/mf6io/mf6ivar/dfn/swf-disv1d.dfn
- src/Idm/chf-dis2didm.f90
- src/Idm/chf-disv1didm.f90
- src/Idm/olf-dis2didm.f90
- src/Idm/swf-dis2didm.f90
- src/Model/Discretization/Dis2d.f90
- src/Model/Discretization/Disv1d.f90
- src/Model/Discretization/Disv2d.f90
- src/Model/ModelUtilities/Connections.f90
Improved capabilities for surface water models:
* added support for IDOMAIN
* added tests to ensure binary grid files are correct
* renamed botm to bottom for the three surface water grid types (DISV1D, DIS2D, DISV2D)
Tests require corresponding changes in flopy ([PR #2295](https://github.com/modflowpy/flopy/pull/2295)) in order to work.
> fix(swf-dis): fixes for swf dis functionality

- meson.build
Applies existing mac workaround to linux environments for HDF5 library issue https://github.com/HDFGroup/hdf5/issues/3831.
> fix(netcdf):  address gcc hdf5 build issue on linux

- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- doc/mf6io/prt/oc.tex
- doc/mf6io/prt/prp.tex
The new dimensions and tracktimes/releasetimes blocks added to output control and particle release packages, respectively, were not mentioned in the mf6io guide. Also fix inconsistent descriptions of the release time schedule in the PRP DFN.
___
> docs(prt): update structure of blocks section for prp/oc

- autotest/test_gwt_mst02.py
- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/gwt-mst.dfn
- src/Model/GroundWaterEnergy/gwe.f90
- src/Model/GroundWaterTransport/gwt-mst.f90
- src/Model/GroundWaterTransport/gwt.f90
- src/Model/TransportModel/tsp.f90
Sorbate concentrations can now optionally be saved to a binary file.  A new `SORBATE FILEOUT <sorbatefile>` option can be specified in the options block of the MST Package.
Also rewired some of the inheritance patterns in the transport model output routine to better support GWT and GWE.  
> feat(mst): add capability to save sorbate concentrations to binary file

- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
The description of RELEASE_TIME_TOLERANCE and RELEASE_TIME_FREQUENCY failed to mention that these are real numbers, and did not describe epsilon as machine precision. Moreover the default RELEASE_TIME_TOLERANCE was incorrectly stated to be epsilon times 10^9, where in fact it is epsilon times 10^11.
Thanks to @rbwinst-usgs for catching these mistakes.
___
> docs(prt): fix PRP package parameter descriptions

- doc/mf6io/mf6ivar/dfn/utl-tas.dfn
- doc/mf6io/mf6ivar/dfn/utl-ts.dfn
Add `in_record true` to several record fields in `utl-ts.dfn` and `utl-tas.dfn`. Motivated by https://github.com/modflowpy/flopy/pull/2317. FloPy can infer this, evidently, but a less clever (and ideally much simpler) implementation may require them explicitly. IMO it makes sense to do this anyway for consistency's sake, at least while the DFN specification is flat and record membership cannot be inferred directly from the spec's structure.
This is not necessarily comprehensive, further work may reveal the same (or similar) updates are needed elsewhere.
> refactor(dfns): add in_record attr to utl-ts and utl-tas vars

- doc/mf6io/mf6ivar/dfn/gwf-lak.dfn
- doc/mf6io/mf6ivar/dfn/gwf-sfr.dfn
Minor typos discovered while working on a fix for the SPC utility for application in GWE models
> fix(gwf-lak.dfn; gwf-sfr.dfn): minor typos

- autotest/test_gwf_sfr_kinematic01.py
- doc/MODFLOW6References.bib
- doc/ReleaseNotes/ReleaseNotes.bbl
- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/gwf-sfr.dfn
- src/Model/GroundWaterFlow/gwf-sfr.f90
* Add PinderSauer example to ReleaseNotes develop.tex with associated references
* update test_gwf_sfr_kinematic01.py to use revised dev_storage_weight variable name
> refactor(sfr): convert storage_weight to dev variable

- src/Model/ModelUtilities/Xt3dInterface.f90
* warning message showing iallpc getting added multiple times to hashtable
* fix by using mem_reallocate instead of mem_deallocate/mem_allocate for the second call
Replace this paragraph with a written description of the pull request.  Include images and files as necessary to help with the documentation.  Descriptions for trivial and minor pull requests should be brief.
> fix(xt3d): iallpc getting adding twice to memory manager

- src/Utilities/Idm/mf6blockfile/LoadMf6File.f90
- src/Utilities/Idm/mf6blockfile/StructArray.f90
This change addresses the IDP issue reported in #2025:
- currently IDM tries to load a dimension 0 static list block without the dimension
- Loading in this way doesn't support 2d variables in list input (auxiliary variable)
- This change allows a dimension 0 static list input load to be acted upon in the expected way
> fix(idm): tolerate dimension 0 static list input

- doc/ReleaseNotes/develop.tex
- src/Model/ParticleTracking/prt-fmi.f90
Temporary fix for #2042, pending a more complete solution for #2041 where ideally we can standardize treatment of array- and list-based input and avoid the special handling.
> fix(PrtFmiType): accommodate 0s in nodelist

- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/MeshNCModel.f90
Change file creation mode to logical AND of 'NC_CLOBBER' (= recreate when present) and 'NF90_NETCDF4' (desired file format) instead of OR
> fix(netcdf): rerun should overwrite netcdf output file

- .git-blame-ignore-revs
- DEVELOPER.md
This PR attempts to clear some "noise" when using GitHub's "blame view" UI tool to see changes in code history for individual files.
These commits are chosen as they are mostly style-related changes rather than code refactors (minor refactors are OK):
- 41e98a24cec6d3607138558fa538621191260efa
- c033fc85713770ace7d51f3c382257bc90d9932f
- 571dcfd5cd439ba7129ed86b6e54e6e0c7340d35
- cc444d0364f97e47c965b91efd6b480d66ea2105
- 04e82dd660541b3fa61b9cfe3343a827698f113a
- b063109202645a13a2f6d8b9799048c304e525d9
- 9514eb46c14f0d4f4860fbfb0eb96c2606ac597f
- c3f415362edd6a8e033204967281fd10061dacf8
- ff1f8e596680ce1a5bdad589b80b2746bc6dca55
- d56a12e0db8ff9d052b7ef9d7157506528e1a70e
- 9f7c07aea29d55f9c0ef2a61f62bc15d45321695
- 9d55d586439b832c33feb196718a6122973dc6aa
- …
> chore: add .git-blame-ignore-revs

- .codespell.ignore
- .codespellrc
- .github/common/check_spelling.py
- autotest/test_chf_dis.py
- autotest/test_chf_dis_fdc.py
- autotest/test_gwe_drycell_cnd4.py
- autotest/test_gwe_esl02.py
- autotest/test_gwe_split_analyt.py
- autotest/test_gwf_csub_sub01_adjmat.py
- autotest/test_gwt_sft_inactive01.py
- autotest/test_olf_dis.py
This PR has two primary aims:
1. Add a codespell configuration, so that users can type `codespell` to check everything and show suggested changes. This takes 1.5 seconds on my laptop.
2. `python3 .github/common/check_spelling.py` now checks Python source files. This takes 12.5 seconds on the same laptop.
Other changes:
- Fix a small handful of typos from Python source files.
- Expand the list of ignored words. Some case-sensitive ignores are enforced, others that don't raise errors are removed.
- Improve use of [`subprocess.run()`](https://docs.python.org/3/library/subprocess.html#subprocess.run) usage in  `check_spelling.py`
> chore: add codespell configuration, check python source files

- .github/workflows/ci.yml
- .github/workflows/compilers.yml
Carved out of #2054. The `macos-12` runner will be deprecated soon and has started seeing warning outages. Also shrink the test matrix for the compiler compatibility tests to include only the latest of each platform.
___
> ci(macos): switch macos-12 -> 13, trim compiler compat test matrix

- src/Model/GroundWaterFlow/gwf-lak.f90
- src/Model/GroundWaterFlow/gwf-maw.f90
- src/Model/GroundWaterFlow/gwf-mvr.f90
- src/Model/GroundWaterFlow/gwf-sfr.f90
- src/Model/GroundWaterFlow/gwf-uzf.f90
- src/Model/GroundWaterTransport/gwt-ist.f90
- src/Model/TransportModel/tsp-apt.f90
- src/Model/TransportModel/tsp-mvt.f90
- src/Utilities/InputOutput.f90
Add InputOutput GetUnit() wrapper:
- throw error if provided integer has valid assigned i/o unit number (>0)
- assign a valid unit number if provided integer in initialized state (<=0) 
- #1786 
> feat(io): add wrapper routine with check around getunit

- autotest/TestInputOutput.f90
- doc/ReleaseNotes/develop.tex
- src/Utilities/InputOutput.f90
There was a 30 character limit hardwired into urword.  This seemed arbitrary and could cause problems for programs like PEST as described in #1638.  This PR relieves this restriction and instead defers to the Fortran casting from a string to an integer to determine if there is a problem.
Simple fix is to change from
```
100 if (ncode == 2 .or. ncode == 3) then
rw = ' '
l = 30 - istop + istart
if (l < 1) go to 200
rw(l:30) = line(istart:istop)
if (ncode == 2) read (rw, '(i30)', err=200) n
if (ncode == 3) read (rw, '(f30.0)', err=200) r
end if
return
```
to 
```
100 if (ncode == 2 .or. ncode == 3) then
l = istop - istart + 1
if (l < 1) go to 200
if (istart > linlen) then
! support legacy urword behavior to return a zero value when
! no more data is on the line
if (ncode == 2) n = 0
if …
```
> fix(urword): increase number of characters for integers and floats

- src/Utilities/CharString.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileGridInput.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileListInput.f90
- src/Utilities/Idm/mf6blockfile/StructArray.f90
- src/Utilities/Memory/Memory.f90
- src/Utilities/Memory/MemoryManager.f90
Current valgrind log associated with PR: [valgrind.log](https://github.com/user-attachments/files/16235351/valgrind.log)
- Linux x86_64 compiling with gfortran 11.4
- ```test_gwf_csub_zdisp02.py``` as in issue description
Issue #1943 
> fix(utils): address memory leaks in CharacterStringType, Idm

- autotest/conftest.py
- autotest/framework.py
- autotest/test_chf_dfw_loop.py
Many of the autotest scripts have code for plotting results.  This PR establishes a convention for passing in a --plot command line option to pytest, which will cause a `plot_output()` function to be called.  
> ci(plot): add plot option to conftest

- DEVELOPER.md
- autotest/test_chf_dfw_beg2022.py
- autotest/test_chf_dfw_swrt2.py
- autotest/test_chf_dfw_swrt2b.py
- autotest/test_chf_dis.py
- autotest/test_chf_dis_fdc.py
- autotest/test_gwt_buy_solute_heat.py
- autotest/test_gwt_henry_nr.py
- autotest/test_gwt_ist02.py
- autotest/test_gwt_ist03.py
- autotest/test_gwt_moc3d01_zod.py
- autotest/test_gwt_mwt02.py
- autotest/test_gwt_prudic2004t2.py
- autotest/test_gwt_prudic2004t2gwtgwt.py
- autotest/test_olf_dfw_swrt2dis.py
- autotest/test_olf_dis.py
- autotest/test_olf_vcatch.py
Some autotests have plotting routines.  This PR modifies them to use a consistent format that works with the new pytest --plot hook.
> ci(plotting): update autotests with plots to use new pytest --plot hook

- doc/mf6io/gwe/esl.tex
patching up a small typo in the ESL section of the mf6io guide
> fix(gwe-esl): src/esl typo in mf6io guide

- autotest/test_par_hpc01.py
- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/utl-hpc.dfn
- src/Distributed/DistributedSim.f90
- src/Idm/utl-hpcidm.f90
> feat(hpc): add option to print partition table to file

- src/Utilities/Export/NCModel.f90
NetCDF exports when in validate mode don't contain timeseries data and are intended to generate files containing supported package input data.  This update makes this more explicit by adding a input suffix identifier to the export.
For a model named "rch", a typical NetCDF export would be named "rch.nc". With this change, if running in validate mode, the export would be named "rch.in.nc".
The primary benefit of this change is that it avoids file name collisions if a user generates an input file in validate mode and then directly uses the file as a NetCDF input while also trying to generate a new timeseries export (with the same name).
For additional information see [instructions for contributing](/MODFLOW-USGS/modflow6/.github/CONTRIBUTING.md) and …
> refactor(export): add "in" suffix to netcdf export name when in validate mode

- autotest/test_netcdf_gwe_cnd.py
- autotest/test_netcdf_gwf_disv.py
- autotest/test_netcdf_gwf_lak_wetlakbedarea02.py
- autotest/test_netcdf_gwf_rch01.py
- autotest/test_netcdf_gwf_rch03.py
- autotest/test_netcdf_gwf_sto01.py
- autotest/test_netcdf_gwf_vsc03_sfr.py
- autotest/test_netcdf_gwt_dsp01.py
- autotest/test_netcdf_gwt_prudic2004t2.py
- doc/mf6io/mf6ivar/dfn/gwe-nam.dfn
- doc/mf6io/mf6ivar/dfn/gwf-nam.dfn
- doc/mf6io/mf6ivar/dfn/gwt-nam.dfn
- doc/mf6io/mf6ivar/examples/netcdf-nam-example.dat
- src/Idm/gwe-namidm.f90
- src/Idm/gwf-namidm.f90
- src/Idm/gwt-namidm.f90
- src/Idm/utl-ncfidm.f90
- src/Utilities/Export/DisNCMesh.f90
- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/DisvNCMesh.f90
- src/Utilities/Export/MeshNCModel.f90
- src/Utilities/Export/ModelExport.f90
- src/Utilities/Export/NCExportCreate.f90
- src/Utilities/Export/NCModel.f90
- src/Utilities/Idm/SourceLoad.F90
GWF, GWT and GWE name files to this point have supported the ```EXPORT_NETCDF``` tag which takes an argument for the NetCDF export type, ```mesh``` or ```structured```.  This change replaces ```EXPORT_NETCDF``` with the fileout tags ```NETCDF_STRUCTURED``` and ```NETCDF_MESH2D```, and allows the user to specify the NetCDF output filename.  
For example:
```
NETCDF_MESH2D  FILEOUT  gwf_sto01.nc
```
> refactor(netcdf): replace export_netcdf input tag with type specific fileout tags

- doc/mf6io/mf6ivar/dfn/gwe-lke.dfn
- doc/mf6io/mf6ivar/dfn/gwe-sfe.dfn
The description for the `EVAPORATION` keyword in SFE and LKE was leftover from using the SFT and LKT .dfn files as a launch point for the SFE and LKE .dfn files.  The effects of evaporation in a GWT vs GWE are fundamentally different and the description should reflect this.
> fix(mf6io): cleanup description of EVAPORATION keyword in SFE and LKE

- autotest/test_gwe_bad_input.py
- autotest/test_prt_quad_refinement.py
- autotest/test_prt_ternary_methods.py
We missed a few tests that should only run in develop mode (`IDEVELOPMODE = 1`). It's making the release build fail.
___
> chore: mark developmode tests

- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
- src/Solution/ParticleTracker/Particle.f90
Fix several related issues that can occur with the generalized tracking method on vertex grids.
1. The polygon centroid formula used when dividing cells into subcells can fail due to floating (im)precision when the vertex coordinates are all large and near to one another, i.e. big grids with really small cells. One option is to do a point-in-polygon check on the result of the centroid calculation and use a simple geometric mean if it fails, but the check is not cheap. Another option is to always use the geo mean instead of the polygon centroid &mdash; to guarantee that this is safe we will need to check that the cell vertices don't "wrap around" or contain duplicates I think. In the meantime this PR aims for an 80/20 solution and uses the geometric mean if the cell has 3 vertices, …
> fix(prt): avoid fpes, patch centroid calculation

- doc/ReleaseNotes/appendixA.tex
- doc/ReleaseNotes/develop.tex
- doc/ReleaseNotes/previous/v6.6.0.tex
Reset the release notes after releasing 6.6.0.
> chore(release): reset release notes

- doc/mf6io/mf6ivar/dfn/gwe-lke.dfn
- doc/mf6io/mf6ivar/dfn/gwe-mwe.dfn
- doc/mf6io/mf6ivar/dfn/gwe-sfe.dfn
- src/Model/GroundWaterEnergy/gwe-lke.f90
- src/Model/GroundWaterEnergy/gwe-mwe.f90
- src/Model/GroundWaterEnergy/gwe-sfe.f90
- src/Model/TransportModel/tsp-apt.f90
The variables `ktf`, thermal conductivity of the of the interface between the aquifer cell and the apt feature, for example a stream reach, and `rfeatthk`, a real value that defines the thickness of the streambed material through which conduction occurs, are specific to `GWE` and shouldn't have been added to `APT` in the first place.  This PR removes both variables from APT and distributes them to `SFE`, `LKE`, and `MWE` where they are needed.  Three pre-existing GWE autotests were already in place to help ensure that the changes didn't break anything (`test_gwe_sfe_strmbedcond.py`, `test_gwe_lke_conduction.py`, and `test_gwe_mwe_conduction.py`).
> refactor(tsp-apt): remove gwe-specific code from apt and distribute to advanced gwe packages

- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- src/Model/ModelUtilities/ReleaseSchedule.f90
- src/Model/ParticleTracking/prt-prp.f90
Mentioned in the discussion in #2125, skip release times before simulation start, and after simulation end if no extended tracking.
___
> fix(prt): skip release times falling outside tdis

- src/Model/ParticleTracking/prt-prp.f90
The arguments did not match the format, causing a crash. The error message could be improved anyway.
> fix(prp): fix error msg format, improve msg

- src/Solution/ParticleTracker/CellDefn.f90
- src/Solution/ParticleTracker/Method.f90
- src/Solution/ParticleTracker/MethodDisv.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
#2066 introduced a bug where particle coordinates were prematurely transformed back from cell-local coords to model coords. This produced incorrect particle positions within quad-refined cells and cells adjacent to a quad-refined cell.
See e.g. https://modflow6-examples.readthedocs.io/en/master/_notebooks/ex-prt-mp7-p04.html.
> fix(prt): don't reset transform in subcell rect method

- src/Utilities/Memory/MemoryHelper.f90
Fixes crash that occurred when compiled with flang-new 19.1.1 on windows
> fix(MemoryHelper.f90) Added optional checks

- autotest/test_gwf_disu.py
- doc/ReleaseNotes/develop.tex
- doc/mf6io/framework/binaryoutput.tex
- src/Model/Discretization/Disu.f90
The binary grid file written by MODFLOW 6 for DISU models did not include the IDOMAIN array.  The binary grid file now includes IDOMAIN for all discretization types, including DISU.
> feat(disu-idomain): write idomain to binary grid file for disu models

- distribution/build_docs.py
We could just do this in the release.yml workflow with `actions/download-artifact`, now that v4 supports downloads from arbitrary workflow runs. But we probably want to run fresh benchmarks at release time.
Also remove some awkward tests for things that get exercised nightly in the release workflow anyway.
> ci(release): don't download benchmark artifacts in build_docs.py

- doc/ReleaseNotes/develop.tex
Neglected in https://github.com/MODFLOW-USGS/modflow6/commit/244583587cc2d2fcb375831dc721e87d63387e22
> docs(release): add release note for recent PRT fix

- autotest/test_prt_exg.py
- doc/ReleaseNotes/develop.tex
- src/Exchange/exg-gwfgwe.f90
- src/Exchange/exg-gwfgwt.f90
- src/Exchange/exg-gwfprt.f90
- src/Model/ModelUtilities/FlowModelInterface.f90
Check that models connected to a flow model by an exchange have an idomain identical to the flow model's idomain. This is an easy error to make, and (up to now) hard to detect.
I only added a test for PRT for now. The logic is identical in GWT and GWE. I wondered if there are suitable autotests for those models to add a test case to? Or maybe this behavior should have its own autotest?
#2144 facilitates adding the same check for flow model interface. I figure that can be done in a separate PR since it probably deserves a separate release note?
___
> fix(exg-gwf*): check for equal idomain 

- autotest/test_prt_exg.py
- doc/mf6io/gwe/fmi.tex
- doc/mf6io/gwt/fmi.tex
- doc/mf6io/prt/fmi.tex
The first paragraph in the prt fmi section could be read to indicate that the fmi file is always required. Add some clarification. Also update a test to make sure the head/budget file paths provided via fmi are ignored when the simulation uses an exchange
> docs(prt-fmi): clarify only required when post-processing

- src/Utilities/Memory/MemoryManager.f90
To optimize the deallocation of variables when MODFLOW finalizes, this PR moves the responsibility of deallocation to a single method instead of having the responsibility per package.
Add the moment the responsibility is moved away from the packages by simply having the mem_deallocate return immediately. In the end the entire mem_deallocate method should be removed
@mjr-deltares provided a test-case to stress test the deallocation of variables.
The test case consist of 1521820 variables and a single timestep.
The time from start to till completion of the solution is about 5 seconds. The remainder of the time is spent finalizing the simulation. 
The total time spent running the simulation is:
|  	|  Current deallocation |  New deallocation|
|---	|---	|---	|
|   Total time 	|   5m42	| …
> Deallocate all the assigned memory in one go when MODFLOW finalizes

- src/Idm/olf-flwidm.f90
- src/Model/ModelUtilities/SfrCrossSectionUtils.f90
- src/Model/ModelUtilities/SwfCxsUtils.f90
The routine for calculating the wetted station length was simplified based on a suggestion by @aprovost-usgs.  The resulting subroutine is shorter and likely slightly faster and will produce the same results.
> refactor(get-wetted-station): simplify and speed up calculation

- environment.yml
- make/makedefaults
- make/makefile
- utils/mf5to6/make/makedefaults
- utils/mf5to6/make/makefile
- utils/zonebudget/make/makedefaults
- utils/zonebudget/make/makefile
pymake has been updated to reduce unimportant changes. Regenerate makefiles with updated pymake. Also removed defaults channel from `environment.yml` by specifying `nodefaults`.
This was first submitted by @jdhughes-usgs, and recreated here due to merge conflicts on #2169.
> refactor(makefiles): regenerate makefiles with updated pymake

- src/Utilities/KeyValueList.f90
In the KeyValueList there is the clear_node method that recursively calls itself until the entire list is cleared.
This works find for small lists, however for large lists this may cause issues. The reason being that each recursive call creates a new call stack which can eventually lead to a segmentation error.
In this PR the recursive method is replaced by a do while loop which mitigates this issues
> Replace the recursive clear_nodes method by a do while loop

- distribution/build_docs.py
upload/download-artifact@v4 migration is a PITA inflamed by my reluctance to finally confront it
> Revert "Revert "ci(release): don't download benchmark artifacts in build_docs.py (#2147)" (#2175)"

- msvs/mf6core.vfproj
- src/Utilities/Memory/Memory.F90
- src/Utilities/Memory/Memory.f90
- src/Utilities/Memory/MemoryManager.f90
- src/meson.build
- utils/mf5to6/msvs/mf5to6.vfproj
- utils/mf5to6/pymake/extrafiles.txt
Due to a bug in gfortran 11, 12, 13.1, and 13.2 we cant store a str1d in the MemoryType.
Upon deallocation a segmentation fault is produced. That's because due to the bug the len of the character is correctly assigned to the type descriptor
We worked around this by either ignoring it (potential bug) or using the CharString type
In this PR I added another workaround that allows us deallocated the str1d. To do so I'm using a c_ptr cast to readd the needed information to the type descriptor.
**Note:**
I tested it in WSL using gfortran 11.4
I tested it in WSL using gfortran 12.3
I tested it in WSL using gfortran 13.1
I tested it in WSL using gfortran 13.2
I tested it in WSL using gfortran 13.3
I tested it in WSL using gfortran 14.1
**Note2**
This also fix the remaining memory leaks we have …
> Fix str1d deallocation

- doc/mf6io/mf6ivar/dfn/gwt-ist.dfn
- src/Model/GroundWaterTransport/gwt-ist.f90
Indicate sorption option must be same in GWT-MST and GWT-IST Packages.
> docs(ist): indicate sorption in IST and MST must be same

- autotest/test_gwe_decay01.py
- autotest/test_gwe_decay02.py
- doc/ReleaseNotes/develop.tex
- doc/mf6io/mf6ivar/dfn/gwe-est.dfn
- src/Model/GroundWaterEnergy/gwe-est.f90
- src/Model/GroundWaterTransport/gwt-mst.f90
Support for specifying energy decay in the solid phase was missing despite it being described in the Supplemental Technical Information document.  The best I can figure is that during development it was initially skipped over with the intention of coming back to it - but then was forgotten about.
> fix(gwe-est): add support for energy decay in the solid phase

- src/Solution/ParticleTracker/MethodSubcellTernary.f90
Since #2127 we do not allow release times before the beginning of the simulation (i.e. negative).
> chore(prt): fix comment to reflect prohibition on pre-start releases

- .github/workflows/ci.yml
- .github/workflows/compilers.yml
Use LDFLAGS workaround to select classic linker on macOS. Also add gcc14 to test matrix.
> ci: fix compiler compatibility workflow

- src/Model/GroundWaterTransport/gwt-mst.f90
Improve `MST` code readability with enumeration
> refactor(gwt-mst): apply enumeration to mst package for readability

- msvs/mf6.vfproj
- msvs/mf6bmi.vfproj
- msvs/mf6core.vfproj
- utils/mf5to6/msvs/mf5to6.vfproj
In https://github.com/MODFLOW-USGS/modflow6/pull/2161 a fix has been created that for its use depends on the fortran preprocessor. This is enabled by adding /fpp to the compiler arguments and has been added to the meson configuration files. However it is missing in the the vcproj files.
This PR corrects that.
It fixes the differences in errors produced by IFX compiler as is mentioned in https://github.com/MODFLOW-USGS/modflow6/issues/2187
> (fix) Enable the preprocessor in the visual studio files

- distribution/build_docs.py
should fix the full distribution test in the nightly build, it was looking for the benchmark results in the wrong place
> ci(release): fix docs build script

- distribution/benchmark.py
Keep the downloaded release directory out of the generated docs artifact
> fix(benchmark.py): remove latest mf6 download dir after rebuilding

- pixi.toml
This PR removes `pip` options `--no-build-isolation` and `--no-deps` for installing Python packages. This enables these packages to have the default behavior to be built in isolation and can request their own dependencies as required.
> chore(pixi): remove pip options --no-build-isolation --no-deps

- src/Utilities/Export/ModelExport.f90
- src/Utilities/Idm/IdmLoad.f90
- src/Utilities/Idm/InputLoadType.f90
Idm maintains a model inputs list so stress period data can be loaded at the right time.  To this point, input models have been added to the list only if it contains packages with dynamic data.  The NetCDF export capability uses this model list as well but in this case all input models are relevant so a NetCDF output file can be created whether or not the model has dynamic data.
> fix(netcdf): add all models to model inputs list

- src/Model/GroundWaterEnergy/gwe-est.f90
- src/Model/GroundWaterFlow/TvBase.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
While working on sensible heat flux utility (`shf`), made various spot changes with the intent of helping improve code uniformity, particularly in `BoundaryPackage,` which I've had to look at a fair bit while developing a first draft of `shf`.  The indentation of the docstrings defining the subroutines was different than all the other src files.
> chore(various): accumulated lints

- environment.yml
- pixi.lock
- pixi.toml
After https://github.com/modflowpy/flopy/commit/c5b5a41f626ad24d8f0e564a83ab8dc673cc9b7b flopy needs boltons for code generation. Would ideally install transitively thru the optional dependency group but currently flopy is installed from github. And boltons is useful enough to warrant addition IMO
> chore: add boltons to pixi/conda envs

- autotest/binary_util.py
- autotest/test_gwt_adv01_fmi.py
- autotest/test_gwt_dsp01_fmi.py
- autotest/test_gwt_fmi01.py
- autotest/test_gwt_mst05.py
These were removed in https://github.com/modflowpy/flopy/pull/2475 as they were only used in a few autotests. Second-guessing moving these into flopy (from pymake) a while back, they're just utilities to mock up binary files for testing.
> test: move binary file write utils from flopy

- doc/mf6io/mf6ivar/examples/prt-fmi-example.dat
The head and budget file keyword names in PRT FMI were described as `PRTHEAD` and `PRTBUDGET`. They should begin `GWF...` instead.
> docs(prt-fmi): correct head/budgetfile keywords

- .github/actions/test-extended/action.yml
(see commit ce78bad in their repo) forces us to set back our version to 3.22 for the time being.
> fix(petsc): breaking changes in PETSc 3.23 

- src/Model/TransportModel/tsp-ssm.f90
gwt-ssm.f90 was generalized and moved to tsp-ssm.f90 (#1398).  The error message modified by this PR should have been updated at that time to account for the fact that either a `GWF-GWT` or `GWF-GWE` exchange could be missing.
> style(tsp-ssm): amend error message

- pixi.lock
Revert a3155cdbaa39ae04fc252df438725bddf2f28f1e, it broke something (netcdf-related?) in the macos extended build.
> Revert "chore: update pixi.lock (#2266)"

- .github/workflows/ci.yml
- .github/workflows/compilers.yml
- .github/workflows/large.yml
- .github/workflows/release.yml
- .gitignore
- autotest/compare.py
- autotest/framework.py
- autotest/test_largetestmodels.py
- autotest/test_testmodels_mf5to6.py
- autotest/test_testmodels_mf6.py
Replace [the old fixtures](https://modflow-devtools.readthedocs.io/en/latest/md/fixtures.html#loading-example-models) with the new models module for accessing models from various repositories. Also some renaming and cleanup in the regression/comparison utilities.
> test: use devtools models api, misc cleanup

- doc/mf6io/mf6ivar/dfn/gwf-buy.dfn
- doc/mf6io/mf6ivar/dfn/gwf-vsc.dfn
GWE should have been listed in the description of the modelname parameter for both the `BUY` and `VSC` Packages.  
> docs(mf6io): modelname description incomplete in buy and vsc packages

- .github/actions/test-extended/action.yml
Fix macOS extended build: ```netcdf-fortran``` in the environment was recently upgraded from ```4.6.1``` to ```4.6.2``` which included a change to the ```nf-config``` interface.
For additional information see [instructions for contributing](/MODFLOW-ORG/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-ORG/modflow6/.github/DEVELOPER.md).
> fix(ci): macos extended build

- doc/Common/gwf-csubobs.tex
- doc/ReleaseNotes/develop.toml
- src/Model/GroundWaterFlow/gwf-csub.f90
Add interbed-compaction-pct observation to CSUB. Also moved CSUB convergence table initialization after reading interbed data to eliminate false warning.
For additional information see [instructions for contributing](/MODFLOW-ORG/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-ORG/modflow6/.github/DEVELOPER.md).
> feat(csub): add percent compaction observation

- autotest/test_gwe_sfe_strmbedcond.py
- doc/ReleaseNotes/develop.toml
- src/Model/GroundWaterEnergy/gwe-sfe.f90
In the MF6io guide, in the SFE observations section, one of the observation types listed was `STRMBD-COND`.  However, there was no actual support for this observation type in the src code.  This PR adds support for it and tests that it is working OK by modifying an existing autotest (`test_gwe_sfe_strmbedcond.py`)
> fix(gwe-sfe): add support for strmbd-cond observation type in sfe

- autotest/test_gwf_ifmod_idomain02.py
- autotest/test_par_gwf_idomain02.py
- doc/ReleaseNotes/develop.toml
- src/Distributed/MpiRouter.f90
- src/Distributed/VirtualBase.f90
This can occur for truly large models, think  ~50M nodes or more.
For additional information see [instructions for contributing](/MODFLOW-ORG/modflow6/.github/CONTRIBUTING.md) and [instructions for developing](/MODFLOW-ORG/modflow6/.github/DEVELOPER.md).
> fix(par): avoid integer overflow of MPI message size

- .github/workflows/docs.yml
- distribution/README.md
- distribution/build_docs.py
- doc/ReleaseNotes/mk_releasenotes.py
- pixi.toml
#2108 neglected to document `mk_releasenotes.py` for developers, do so. Give the script named `--toml` and `--tex` parameters with default values `develop.toml` and `develop.tex` in the same directory as the script. Add a pixi task to run the script with defaults. Rename the `deprecations` task to `collect-deprecations`, following pattern `verb[-noun]`.
> chore(pixi): add pixi task to make release notes tex, update dev docs

- src/Model/GroundWaterFlow/gwf-sfr.f90
Docstrings in SFR had a different indentation than the rest of the code
> chore(gwf-sfr): nit-linting (the linting form of nit-picking)

- doc/mf6io/mf6ivar/dfn/utl-ncf.dfn
- src/Utilities/Export/DisNCMesh.f90
- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/DisvNCMesh.f90
- src/Utilities/Export/MeshNCModel.f90
- src/Utilities/Export/NCModel.f90
- src/Utilities/Idm/netcdf/NCContextBuild.f90
Adjustment to model NetCDF input file creation that align with [FloPy #2417](https://github.com/modflowpy/flopy/pull/2417):
- Fix DIS mesh_face_x array, which was off by an index
- Rotate mesh x and y coordinates when angle of rotation has been specified
- Structured export projected coordinates are never rotated.  Only translate if angrot is 0.0, otherwise leave in grid local coordinates.
- Structured exports support either latitude / longitude geographic coordinates or a projection variable for grid mapping via the wkt string but not both.  Latitude and longitude coordinates can be rotated.
- change global attributes "modflow6_grid" and "modflow6_model" to "modflow_grid" and "modflow_model", as these identifiers might be more generally applied
- After FloPy PR is merged, a follow up PR …
> refactor(netcdf): updates focused on flopy parity

- pixi.toml
- utils/idmloader/dfns.txt
- utils/idmloader/scripts/dfn2f90.py
Instead of accepting a text file specifying DFN files &mdash; a temporary measure while IDM supports a subset of the full specification &mdash; just accept one or more path arguments, each of which can be a DFN file or a folder containing DFN files, and feed the `dfns.txt` file to this from the shell.
A prep step before code generation is switched to consume TOML DFNs, coming shortly.
**Note to model developers**: after this, the behavior of running `dfn2f90.py` directly with no arguments will change to include all DFNs by default. To get the old behavior (i.e. the subset of DFNs IDM supports), it will be necessary to use the pixi task or feed `dfns.txt` to the script with e.g. 
```shell
cat dfns.txt | xargs python ...
```
> refactor(dfn2f90.py): accept 1+ dfn files or directories

- doc/mf6io/mf6ivar/dfn/gwf-maw.dfn
Looking in the MAW source code, it looks like MF6 is expecting the keyword `CUMULATIVE`, not `COMPOSITE`.  
Thanks for pointing this out @mkennard-aquaveo.
> chore(gwf-maw): correct typos in maw dfn file

- pixi.lock
- pixi.toml
`tomli_w` is needed by the devtools models API as of https://github.com/MODFLOW-ORG/modflow-devtools/pull/210. It'd get installed transitively if we used devtools optional dependency groups as part of the custom install task, but it's probably worth having it explicitly in the environment since we are adopting TOML more generally as a configuration format.
> chore(dependencies): add tomli_w to pixi environment

- doc/mf6io/mf6ivar/deprecations.py
- doc/mf6io/mf6ivar/dfn/prt-oc.dfn
- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- doc/mf6io/prt/oc.tex
We had a lingering reference to TRACK_TIMES and TRACK_TIMESFILE, fix it. And also, I'm not sure why I removed the options from the DFNs in https://github.com/MODFLOW-ORG/modflow6/commit/bf47ec6f26597ccff3d8f100efe5c00037fb711d, for deprecations/removals we conventionally leave the options in the DFN and just mark them as such. The automation will then put them in the deprecation section in the release notes.
> docs(prt): fix ref to removed option, restore dfns

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/develop.tex.jinja
- doc/ReleaseNotes/mk_releasenotes.py
- doc/mf6io/mf6ivar/deprecations.py
Better visual differentiation between section and subsection headers (tweak style and add vertical padding). Also apply ruff where lacking in previous commit
> docs: tweak release notes section header format

- doc/mf6io/mf6ivar/mf6ivar.py
Previously removed options still made it into the MF6IO doc. Revise `mf6ivar.py` to filter them out. And simplify some conditionals.
> chore: update mf6ivar to ignore removed options

- distribution/README.md
- doc/ReleaseNotes/appendixA.tex
Neglected to do this after 6.6.1. Also move the section of the distribution guide describing how to reset the release notes after a release to the Procedure section, where it belongs
> chore: add v6.6.1 release notes to appendix A
