MODFLOW-ORG/modflow6

- README.md
- code.json
- doc/mf6io/mf6ivar/dfn/gwf-npf.dfn
- doc/mf6io/mf6ivar/dfn/sim-nam.dfn
- doc/mf6io/mf6ivar/dfn/utl-obs.dfn
- doc/mf6io/mf6ivar/readme.md
- doc/version.tex
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Utilities/version.f90
- version.txt
Modified csub convergence check to evaluate a fixed number of
significant digits (8) instead of a defined percent difference. The
defined percent difference had issues with the delay bed flows were
small (< 1e-10).
> csub(feat): convergence check with defined precision

- autotest/test_z01_nightly_build_examples.py
- autotest/test_z02_nightly_build_mf5to6.py
- autotest/test_z03_nightly_build_largeexamples.py
Refactor nightly build autotest scripts to find appropriate directories
rather than having them predefined.
> refactor(autotest): refactor nightly build autotest scripts

- doc/mf6io/gwf/gwf.tex
> docs(gwf.tex): minor fix

- src/Utilities/OutputControl/OutputControl.f90
> fix(oc): error message causing runtime error

- distribution/mkdist.py
> fix(mkdist): error output problem in the make distribution script

- autotest/test_gwf_evt01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/mf6io/mf6ivar/dfn/gwf-evt.dfn
- src/Model/GroundWaterFlow/gwf3evt8.f90
> fix(evt): fixed error in evapotranspiration rate calculation

- src/Model/GroundWaterFlow/gwf3lak8.f90
> fix(gwf3lak8): trap for outlet lakein compares against noutlet instead of nlakes

- autotest/test000_setup.py
- autotest/test_gwf_npf04_spdis.py
- src/Model/GroundWaterFlow/gwf3npf8.f90
This change addresses issue #216
> fix(npf): reset lastedge to zero

- .travis.yml
* reduce repetition in test matrix
* remove inactive features like sudo and cache: apt
* install packages with apt-get rather than miniconda
Supersedes #225
> ci(.travis.yml): upgrade to xenial, replace miniconda with apt-get

- autotest/disu_util.py
- autotest/test_gwf_errors.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3disu8.f90
> feat(disu): ensure cell elevations decrease with depth

- src/Model/GroundWaterFlow/gwf3buy8.f90
Buoyancy terms were incorrect when layer thicknesses were variable
> fix(buy): cl1 and cl2 need to be reversed if n < m

- autotest/test000_setup.py
- src/Exchange/GhostNode.f90
- src/Model/GroundWaterFlow/gwf3hfb8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/Connections.f90
- src/Model/NumericalModel.f90
- src/Solution/NumericalSolution.f90
- src/Utilities/TimeSeries/TimeArraySeriesManager.f90
- src/Utilities/TimeSeries/TimeSeriesManager.f90
> fix(fortran): turn on gfortran 2008 standard check

- dllsrc/bmi.f90
- dllsrc/mf6dll.f90
- dllsrc/run_mf6.py
- msvs/mf6.sln
- msvs/mf6dll.vfproj
- src/Timing/tdis.f90
- src/Utilities/Memory/MemoryManager.f90
- src/Utilities/Sim.f90
- src/Utilities/comarg.f90
- src/mf6lib.f90
A first working version of bmi (exposing c-style pointer to our internal arrays). We still need to discuss how we can use the CSDMS interface explicitly, and how they have wrapped it into Python.
> Refactor src

- src/Model/GroundWaterFlow/gwf3uzf8.f90
* Error introduced as part of recent UZF refactoring
* Closes #273
> fix(uzf): fix indexing error in UZF

- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Utilities/Memory/MemoryManager.f90
Implemented new check in develop mode so code bombs with error if memory manager variable not deallocated
> fix(memory): some variables not deallocated

- src/Model/ModelUtilities/Xt3dInterface.f90
This change is required for transport, which accumulates terms in flowja
> refactor(xt3d): accumulate flowja instead of set

- autotest/test_gwf_utl04_auxmult.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/ModelUtilities/DiscretizationBase.f90
- src/Utilities/TimeSeries/TimeSeriesManager.f90
* partially addresses #314 
* change order of time series interpolation so aux is done first in case it is an auxmult column
> fix(auxmult): auxmult fix when auxmult and bound are in time series

- src/Model/GroundWaterFlow/gwf3maw8.f90
fix bug introduced with the new table objects
> fix(maw): new headtable corrected to have nmawwells rows instead of maxbound

- autotest/test_gwf_mvr01.py
- doc/mf6io/mf6ivar/dfn/gwf-lak.dfn
combined lakeperioddata and outletperioddata into perioddata
> refactor(lak package dfn - perioddata): combined all perioddata into one recarray

- src/Model/LinearNetworkFlow/lnf3disl8.f90
- src/Model/ModelUtilities/Connections.f90
- src/Model/ModelUtilities/DislGeom.f90
This sets up lnf cell connection properties from disl package data (ja, ia, cl1, cl2, sparse connection matrix, etc).
> feat(lnf): lnf cell connection properties

- doc/mf6io/mf6ivar/dfn/gwf-mvr.dfn
> docs(gwf-mvr.dfn): clarify mvrtype definition

- doc/mf6io/mf6ivar/dfn/gwf-sfr.dfn
> docs(gwf-sfr.dfn): clarify 2nd idv definition

- autotest/test_gwf_noptc01.py
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
* changes should have no affect on develop version of code
* changes are being made to support future addition of a Buoyancy Package
> refactor(advanced packages): minor changes to support buoyancy package

- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
> fix(uzf): fix memory leak in UzfCellGroup

- autotest/test_gwf_mvr01.py
- autotest/test_gwf_ts_maw01.py
- autotest/test_gwf_ts_uzf01.py
- doc/mf6io/mf6ivar/dfn/gwf-uzf.dfn
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/GroundWaterTransport/gwt1lkt1.f90
- src/Model/GroundWaterTransport/gwt1mwt1.f90
- src/Model/GroundWaterTransport/gwt1sft1.f90
- src/Model/GroundWaterTransport/gwt1uzt1.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
- src/Utilities/BlockParser.f90
- src/Utilities/Constants.f90
- src/Utilities/Memory/Memory.f90
- src/Utilities/Memory/MemoryManager.f90
- src/Utilities/Message.f90
- src/Utilities/Table.f90
- src/Utilities/TimeSeries/TimeSeriesManager.f90
* changes required to transport to remove MemoryTSType
> refactor(transport): merge in develop

- autotest/test_gwf_csub_subwt02.py
- src/Model/GroundWaterFlow/gwf3csub8.f90
> refactor(csub): use read_value_or_time_series_adv() for timeseries

- autotest/test_gwf_mvr01.py
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/ModelUtilities/PackageMover.f90
* mvr budget now contains lake number instead of outlet number when lake is a provider
* added first cut of maw density routine
> refactor(mvr): implement provider mapping array for mvr budget

- autotest/simulation.py
- autotest/test_gwf_maw06.py
- src/Utilities/Constants.f90
- src/Utilities/Memory/MemoryManager.f90
- src/mf6core.f90
Add subroutine definitions to all routines and standardize dummy
variable names for scalars, integer arrays, and real arrays.
> refactor(MemoryManager): memory usage units function of allocated size

- DEVELOPER.md
- autotest/simulation.py
- autotest/targets.py
- autotest/test000_setup.py
- autotest/test_z01_nightly_build_examples.py
- autotest/test_z02_nightly_build_mf5to6.py
- autotest/test_z03_nightly_build_largeexamples.py
- distribution/examples_setup.py
- distribution/mkdist.py
- pymake/makedefaults
- pymake/makefile
- srcbmi/mf6bmi.f90
- travis/before_script.sh
- travis/install_pypack.sh
Update autotest files to reflect recent pymake changes. Remove
unused variables from mf6bmi.f90. Update mf6 makefile.
> ci(repos): update repo paths

- src/Utilities/HashTable.f90
- src/Utilities/TimeSeries/TimeSeriesManager.f90
Attempt to partially address #488 and #494
> refactor(hashtable): rewrite the hash table to be robust and efficient

- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
Increase erroneous string assignment
Closes #513
> fix(boundname): boundname for LAK, MAW, UZF fix

- autotest/test_gwf_obs01.py
- autotest/test_gwt_obs01.py
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Utilities/ArrayHandlers.f90
- src/Utilities/Constants.f90
- src/Utilities/Observation/Obs3.f90
- src/Utilities/Observation/ObsOutput.f90
- src/Utilities/Observation/ObsOutputList.f90
- src/Utilities/Observation/Observe.f90
> refactor(OBS): refactor observations to reduce model spin-up

- src/Solution/SparseMatrixSolver/ims8linear.f90
> fix(ims8linear): DVMAX is not correctly updated

- msvs/mf6bmi.vfproj
- src/Model/NumericalPackage.f90
- src/Solution/NumericalSolution.f90
- src/Timing/tdis.f90
- src/mf6core.f90
- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- srcbmi/mf6xmi.f90
- add doxygen description to main BMI routines (more to follow)
- created BMI util module
- BMI grid routines are now in a separate module, as they have a separate status (currently experimental)
- add function to XMI to compose the address string for a variable in a package, model, or solution
> BMI refactoring, cleaning cont'd:

- .vscode/README.txt
- .vscode/build_vscode.py
- .vscode/launch.json
- .vscode/modflow6.code-workspace
- .vscode/run_python.cmd
- .vscode/tasks.json
> VSCode integration

- srcbmi/mf6bmiUtil.f90
also here we should use the general MemoryHelper routines now...
> bug fix in get_model_name (bmi grid)

- srcbmi/mf6bmiGrid.f90
`get_grid_face_nodes` expects now a preallocated array
as defined in the BMI
`get_grid_nodes_per_face` expects now an integer
instead of the (incorrect) double
> fix(bmi): Fix grid_functions

- srcbmi/mf6bmiGrid.f90
- srcbmi/mf6bmiUtil.f90
- Fix usage of `confirm_grid_type`
- Move `confirm_grid_type` and `get_grid_type_model` to Util
- Refactor the grid type checks
- Whitespace changes
> bmi: Refactor bmiGrid

- src/Utilities/Memory/MemoryManager.f90
- srcbmi/mf6bmi.f90
this is a work in progress on issue #575
> add set_value function to bmi (currently for float64 only)

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/GroundWaterTransport/gwt1adv1.f90
> fix(tvd): corrected tvd mass flow calculation

- autotest/test_gwt_sft01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterTransport/gwt1apt1.f90
> fix(apt): correct constant-concentration budget tabulation

- .github/workflows/ci-latest-compilers.yml
- .github/workflows/ci-latest.yml
- autotest/test_gwt_henry_openclose.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3buy8.f90
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterTransport/gwt1adv1.f90
- src/Model/GroundWaterTransport/gwt1dsp.f90
- src/Model/GroundWaterTransport/gwt1fmi1.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
- src/Model/GroundWaterTransport/gwt1mst1.f90
- src/Model/GroundWaterTransport/gwt1mvt1.f90
- src/Model/GroundWaterTransport/gwt1ssm1.f90
> fix(utl): some parser%GetBlock calls did not support open/close

- autotest/test_gwf_uzf_surfdep.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3uzf8.f90
> fix(uzf): enforce surfdep < cell thickness

- autotest/test_gwf_utl05_budparse.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Utilities/Budget.f90
Numeric values with 3-digit exponents did not include the E character
Close #615
> fix(budget): force numbers in budget table to include E

- autotest/test000_setup.py
- doc/ReleaseNotes/appendixA.tex
Requires that pymake is up to date
> refactor(setup): minor change to compile on windows

- src/Utilities/Memory/MemoryManager.f90
- srcbmi/mf6bmi.f90
- srcbmi/mf6bmiUtil.f90
> Issue624 bmi

- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Utilities/Memory/MemoryManager.f90
Added check that all variable names are upper case to MemoryManager.
> refactor(csub): make all CSUB variable names upper case.

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Exchange/GhostNode.f90
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3buy8.f90
- src/Model/GroundWaterFlow/gwf3chd8.f90
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3hfb8.f90
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/GroundWaterTransport/gwt1adv1.f90
- src/Model/GroundWaterTransport/gwt1cnc1.f90
- src/Model/GroundWaterTransport/gwt1dsp.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
* renamed package mb() method to bd()
* renamed package flowja() methods to cq()
* updated release notes
* moved failed to converge message to follow budget summary tables
> refactor(bd-cq): additional cleanup on the cq()/bd() changes

- utils/mf5to6/src/SfrPackageWriter.f90
- utils/mf5to6/src/mf5to6.f90
> fix(mf5to6): intermittent memory issue in sfr-sfr mover connections

- src/Exchange/BaseExchange.f90
- src/Model/BaseModel.f90
- src/Solution/BaseSolution.f90
- src/Solution/NumericalSolution.f90
- src/Timing/tdis.f90
- src/mf6core.f90
* separate tdis_tu() into a tdis_pu() and tdis_tu()
* implement vacant _tu() methods for models, exchanges, and solutions
* These changes should have no affect on anything
> feat(ats): implement hooks for adaptive time stepping

- src/Solution/NumericalSolution.f90
* also prepend solution name to iteration table titles
> refactor(ims): store number of outer iterations

- src/Utilities/Message.f90
- src/Utilities/Sim.f90
> fix(messages): sim messages were not deallocated

- msvs/mf6core.vfproj
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/ModelUtilities/GwfNpfGridData.f90
- src/Model/ModelUtilities/GwfNpfInputData.f90
- src/Model/ModelUtilities/GwfNpfOptions.f90
These are the discussed changes to npf for our interface model, should have no impact on the current use cases.
> Rfct npf setdata

- autotest/test_gwf_uzf01.py
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/ModelUtilities/UzfCellGroup.f90
* clean up code to allow ATS restore state
* Fix sign of UZF-GWRCH term in GWF budget file
> refactor(uzf): clean up to isolate advance / restore state

- src/Exchange/BaseExchange.f90
- src/Exchange/GwfGwfExchange.f90
- src/Exchange/NumericalExchange.f90
- src/SimulationCreate.f90
- src/Solution/BaseSolution.f90
- src/Solution/NumericalSolution.f90
Refactoring preparing the interface model approach, next to the existing exchanges. This PR should not affect any test outcome.
> refactor(numEx)

- autotest/test_gwf_lak01.py
- autotest/test_gwf_uzf02.py
- src/Model/ModelUtilities/UzfCellGroup.f90
Fixed indexing error in uzfcellgroup and added test
> fix(uzf): unsat ET not correct in uzf budget

- .github/workflows/ci-gfortran-latest.yml
- autotest/common_regression.py
- autotest/test_gwf_lak01.py
- autotest/test_gwf_uzf01.py
- autotest/test_gwf_uzf02.py
black formatting on a few autotest test scripts.
> ci: modify common_regression.py for CI runs on Windows

- autotest/test_gwf_uzf03.py
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/GroundWaterTransport/gwt1ist1.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
* remove unused code
* implement save_print_model_flows() routine for bnd simvals and simtomvr
* add new uzf test
> refactor(bnd): remove unused code

- msvs/mf6core.vfproj
- src/Exchange/DisConnExchange.f90
- src/Exchange/GwfGwfExchange.f90
- src/Exchange/NumericalExchange.f90
- src/Model/ModelUtilities/GwfNpfGridData.f90
- src/Solution/NumericalSolution.f90
anticipating interface model, should be no functional changes here.
> Isolate connection data for exchanges into DisConnExchangeType

- autotest/test_gwf_lakobs01.py
The additional lines of script included with this PR should have been included with #710.  I caught this mistake while working on #715.
> fix(test_gwf_lakobs01.py): update contents of test_mf6model() function

- src/Model/GroundWaterTransport/gwt1mst1.f90
Minor change that will only affect nonlinear isotherm applications with transient changes in saturation
> fix(mst): a saturation term was missing from the nonlinear isotherm RHS equation

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3hfb8.f90
> fix(hfb): enforce horizontal adjacency requirement for flow barriers

- README.md
adding reference to https://doi.org/10.1111/gwat.13117
> docs(new journal article): update to readme.md

- .build_rtd_docs/Doxyfile
- autotest/test_gwf_wel01.py
- doc/Common/gwf-welobs.tex
- doc/mf6io/gwf/wel.tex
- src/Model/GroundWaterFlow/gwf3api8.f90
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/GroundWaterFlow/gwf3wel8.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/ModelUtilities/GwfStorageUtils.f90
- src/Model/NumericalPackage.f90
- src/Utilities/Constants.f90
- src/Utilities/Message.f90
- src/Utilities/Sim.f90
- src/Utilities/SimVariables.f90
- src/Utilities/kind.f90
- src/mf6.f90
- src/mf6core.f90
Added an autotest for reduce q observarions and updated the observations
in the mf6io document. Also added doxygen comments to a number of
modules.
> feat(wel): add reduced q observation

- src/SimulationCreate.f90
> doc: Move docs in SimulationCreate to doxygen

- autotest/test_gwf_npf04_spdis.py
- src/Exchange/GwfGwfExchange.f90
- src/Model/GroundWaterFlow/gwf3.f90
(cherry picked from commit 6cf6c1a95cf1ce7d078ee1027d8d10ab4f2afc12)
> Fix diag sum in flowja for GWF-GWF fluxes

- autotest/budget_file_compare.py
- autotest/test_gwf_disu01.py
- autotest/test_gwf_npf04_spdis.py
- autotest/test_gwf_ts_lak01.py
- autotest/test_gwf_ts_maw01.py
- autotest/test_gwf_ts_sfr01.py
- autotest/test_gwf_ts_sfr02.py
- autotest/test_gwf_ts_uzf01.py
- autotest/test_gwf_uzf01.py
- autotest/test_gwf_uzf02.py
- autotest/test_gwf_uzf03.py
- autotest/test_gwt_adv02.py
- autotest/test_gwt_adv03.py
- autotest/test_gwt_dsp02.py
- autotest/test_gwt_dsp03.py
- autotest/test_gwt_uzt01.py
Recent flopy changes broke a few autotests.  This should fix it.
> fix(ci): upgrade autotests to use latest flopy changes

- autotest/test_gwf_rch02.py
- autotest/test_gwf_rch03.py
- autotest/test_gwf_utl06_tas.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/GroundWaterFlow/gwf3evt8.f90
- src/Model/GroundWaterFlow/gwf3rch8.f90
- src/Model/GroundWaterTransport/gwt1ssm1.f90
- src/Utilities/TimeSeries/TimeArray.f90
- src/Utilities/TimeSeries/TimeArraySeries.f90
- src/Utilities/TimeSeries/TimeArraySeriesManager.f90
* fix bound and nodelist so they are not compressed for READARRAYS input with rch and evt
* time-array series did not work correctly for DIS and DISV models with IDOMAIN
* minor cleanup on time-array series source files
* Close #789
> fix(rch/evt): fix rch and evt packages to work with time-array series

- .vscode/README.md
- DEVELOPER.md
- README.md
- Explain building with meson
- Mention all steps to be able to run the tests
- Remove duplication between developer docs and vscode docs
> docs: Update developer documentation to reflect latest changes

- src/Model/ModelUtilities/BoundaryPackage.f90
- src/SimulationCreate.f90
- src/Solution/NumericalSolution.f90
- src/Solution/SparseMatrixSolver/ims8linear.f90
- src/Utilities/BlockParser.f90
- src/Utilities/Budget.f90
- src/Utilities/Memory/MemoryManager.f90
- src/Utilities/Observation/Obs3.f90
- src/Utilities/Observation/Observe.f90
- src/Utilities/TimeSeries/TimeArraySeriesManager.f90
- src/Utilities/comarg.f90
* ensure allocatable strings are deallocated
* ensure block parser is cleared
* May possibly help with #813
> fix(deallocate): clean up memory deallocation

- make/makedefaults
- make/makefile
- msvs/mf6core.vfproj
- src/Solution/SparseMatrixSolver/ims8base.f90
- src/Solution/SparseMatrixSolver/ims8linear.f90
- src/Utilities/Libraries/blas/blas1_d.f90
- src/Utilities/Libraries/sparskit2/LGPL
- src/Utilities/Libraries/sparskit2/ilut.f90
- src/Utilities/version.f90
- src/meson.build
- utils/mf5to6/make/makedefaults
- utils/mf5to6/make/makefile
- utils/zonebudget/make/makedefaults
- utils/zonebudget/make/makefile
Document changes to original ilut routine.
> refactor(ilut): move ilut to Utilities\Libraries\sparskit2

- autotest/test_gwt_mvt02.py
- autotest/test_gwt_mvt02fmi.py
- src/Exchange/GwfGwtExchange.f90
- src/Model/GroundWaterTransport/gwt1fmi1.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Utilities/Memory/MemoryManager.f90
- src/Utilities/PackageBudget.f90
* Store GWF flows in FMI in the memory manager so they can be accessed with the API
* Close #835
* Should try to get budtxt in through the set_name() method
* Need some cleanup in set_pointers routine in gwf-gwt
> refactor(packagebudget): store FMI GWF flows in memory manager

- autotest/test_gwt_prudic2004t2fmi.py
- autotest/test_gwt_prudic2004t2fmiats.py
- autotest/test_gwt_ssm05.py
- src/Model/GroundWaterFlow/gwf3rch8.f90
* Add test_gwt_ssm05.py
* Ensure proper cleanup of 3 tests that were leaving detritus
* Cleanup recharge package error messages
* Check of #852, which we can't reproduce yet
> test(ssm05): add SSM test for recharge array aux concentration

- autotest/test_gwf_ifmod_rewet.py
- doc/SuppTechInfo/body.tex
- doc/SuppTechInfo/interface-model.tex
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/GwfInterfaceModel.f90
- src/Model/Connection/GwtGwtConnection.f90
- src/Model/Connection/GwtInterfaceModel.f90
- add skeleton for ifmod documentation in supp tech info
> - add rewetting to interface model, including autotest

- distribution/make_release.py
- doc/ConverterGuide/converter_mf5to6.tex
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/zonebudget/zonebudget.tex
Update the make_release.py script to accept command line arguments.  This will allow it to work with the modflow6-distribution repo under development.  This will allow GitHub Actions to automate a complete build of a  modflow 6 distribution for Linux, Mac, and Windows.
> ci(make_release): update make_release.py script

- autotest/test_gwf_ifmod_buy.py
- src/Exchange/DisConnExchange.f90
- src/Exchange/GwtGwtExchange.f90
- src/Model/Connection/ConnectionBuilder.f90
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/GwtGwtConnection.f90
- src/Model/Connection/GwtInterfaceModel.f90
- a bit of cleanup and shuffling
(cherry picked from commit b73eea654a361bedadd65939a2cb7a727dc98a85)
> - Fix in setting dispersion data for the GWTGWT interface model

- autotest/build_exes.py
- distribution/build_makefiles.py
- distribution/evaluate_run_times.py
- distribution/make_release.py
- distribution/mkdist.py
black formatting of distribution scripts
> ci: update build_exes.py for latest pymake changes

- autotest/test_gwf_libmf6_ifmod01.py
- autotest/test_gwf_libmf6_ifmod02.py
- autotest/test_gwf_libmf6_ifmod03.py
- autotest/test_gwt_sft01.py
- autotest/test_gwt_sft01gwtgwt.py
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/GwtGwtConnection.f90
- src/Model/GroundWaterTransport/gwt1fmi1.f90
* turn off writing of list file for gwf and gwt interface models
* add test_gwt_sft01gwtgwt.py
> test(gwtgwt): add new gwt-gwt test with mvt

- doc/SuppTechInfo/storage-modifications.tex
- doc/SuppTechInfo/tvk-tvs.tex
Edits to Ch 5 (Storage) and Ch 6 (TVK-TVS) for wording and consistency of notation. Note that I've embedded comments/questions in red that will need to be deleted.
> docs(mf6suptechinfo): edits to Ch 5 (Storage) and Ch 6 (TVK-TVS)

- src/Utilities/InputOutput.f90
Start adding doxygen comments and reformatting older code.
Closes #931
> fix(openfile): report file that could not be opened

- .vscode/build_vscode.py
- Removes compile call. This is already done by install. Now it doesn't give a confusing message anymore.
- Print the commands it runs
> Improve vscode meson integration

- autotest/disu_util.py
- autotest/test_gwt_disu01.py
- src/Model/GroundWaterFlow/gwf3npf8.f90
- utils/idmloader/src/gwfdisinputdata.f90
> ci(disu): add disu transport test

- src/mf6core.f90
> (fix) small mf6core style issues

- src/Exchange/BaseExchange.f90
- src/Exchange/DisConnExchange.f90
- src/Exchange/GhostNode.f90
- src/Exchange/GwfGwfExchange.f90
- src/Exchange/GwfGwtExchange.f90
- src/Exchange/GwtGwtExchange.f90
- src/Exchange/NumericalExchange.f90
- src/Solution/BaseSolution.f90
- src/Solution/LinearMethods/ims8base.f90
- src/Solution/LinearMethods/ims8linear.f90
- src/Solution/LinearMethods/ims8misc.f90
- src/Solution/LinearMethods/ims8reordering.f90
- src/Solution/NumericalSolution.f90
- src/Solution/SolutionGroup.f90
> style(exchange, solution): apply fprettify formatting

- .github/common/fortran-format-check.sh
- utils/zonebudget/src/budgetdata.f90
- utils/zonebudget/src/grb.f90
- utils/zonebudget/src/zbud6.f90
- utils/zonebudget/src/zone.f90
- utils/zonebudget/src/zoneoutput.f90
> style(zonebudget): apply fprettify formatting

- src/Model/GroundWaterFlow/gwf3tvk8.f90
> fix(tvk): correct k33/k11 calculation

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Exchange/GwfGwtExchange.f90
* close #946
* GWF must be in a separate IMS that is solved before GWT
> fix(gwfgwt): ensure GWF and GWT are in different IMS

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3disv8.f90
> fix(disv): check for zero cell area

- doc/Common/gwt-uztobs.tex
> doc(gwt-uztobs.tex): fix typo in uzt obs type

- autotest/test_gwt_mwt01.py
- autotest/test_gwt_prudic2004t2.py
- autotest/test_gwt_uzt01.py
- doc/Common/gwt-lktobs.tex
- doc/Common/gwt-sftobs.tex
- doc/Common/gwt-uztobs.tex
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/GroundWaterTransport/gwt1lkt1.f90
- src/Model/GroundWaterTransport/gwt1mwt1.f90
- src/Model/GroundWaterTransport/gwt1sft1.f90
- src/Model/GroundWaterTransport/gwt1uzt1.f90
* Close #1019
* Close #1021 
* Add GWT OBS tests to test_gwt_prudic2004t2.py and to MWT and UZT tests
* Update release notes
* Update erroneous observation text in mf6io
> fix(gwt obs): refactor GWT obs for LKT, SFT, MWT, and UZT

- autotest/test_gwf_uzf01.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
> fix(budgetcsv): fix intermittent failure with budgetcsv option

- autotest/test_gwt_prudic2004t2.py
- src/Model/GroundWaterTransport/gwt1.f90
- src/Model/GroundWaterTransport/gwt1adv1.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
* arrays used for indexing locations in the numerical solution array are now stored in memory manager
* revise the way the symmetric matrix indicator is set for GWT
> patch(apt): add variables to memory manager

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3csub8.f90
- src/Model/GroundWaterFlow/gwf3evt8.f90
- src/Model/GroundWaterFlow/gwf3hfb8.f90
- src/Model/GroundWaterFlow/gwf3lak8.f90
- src/Model/GroundWaterFlow/gwf3maw8.f90
- src/Model/GroundWaterFlow/gwf3mvr8.f90
- src/Model/GroundWaterFlow/gwf3rch8.f90
- src/Model/GroundWaterFlow/gwf3sfr8.f90
- src/Model/GroundWaterFlow/gwf3sto8.f90
- src/Model/GroundWaterFlow/gwf3tvbase8.f90
- src/Model/GroundWaterFlow/gwf3uzf8.f90
- src/Model/GroundWaterTransport/gwt1apt1.f90
- src/Model/ModelUtilities/BoundaryPackage.f90
- src/Model/ModelUtilities/GwtSpc.f90
- src/SimulationCreate.f90
- src/Utilities/InputOutput.f90
- src/Utilities/OutputControl/OutputControl.f90
* uget_block did not terminate with an error when looking for a required block and found end of file instead
* update release notes
* Close #148
> fix(getblock): add error message if block not found

- autotest/test_gwf_returncodes.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/GroundWaterFlow/gwf3dis8.f90
- src/Model/GroundWaterFlow/gwf3disu8.f90
- src/Model/GroundWaterFlow/gwf3disv8.f90
- src/Model/GroundWaterFlow/gwf3npf8.f90
- src/Model/GroundWaterTransport/gwt1dsp.f90
- src/Utilities/ArrayRead/LayeredArrayReader.f90
- src/Utilities/Idm/LoadMf6FileType.f90
- src/Utilities/kind.f90
* update release notes for next release
* continue with lowercase renaming for messages
> refactor(io): miscellaneous io cleanup

- autotest/test_gwf_uzf05.py
- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/ModelUtilities/UzfCellGroup.f90
* uzf did not route water to water table unless there was an underlying uzf cell
* Close #1075
* add test for uzf fix
* update release notes for next release
> fix(uzf): uzf not routing properly

- doc/SuppTechInfo/Tables/mf6enhancements.tex
Should've been included with #1071
> doc(suptechinfo): Update MF6 enhancements table in Ch. 1

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/zonebudget/zonebudget.tex
- utils/zonebudget/msvs/zonebudget.vfproj
- utils/zonebudget/src/zbud6.f90
* update release notes
* close #771 
* update msvs project file for zonebudget
> fix(zbud): fix zonebudget for spaces in path

- DISCLAIMER.md
- README.md
- code.json
- distribution/make_release.py
- doc/version.py
- doc/version.tex
- src/Utilities/version.f90
- version.txt
* start v6.5.0 release candidate
> ci(develop): reinitialize develop after 6.4.0 release

- README.md
- code.json
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/appendixA.tex
- doc/ReleaseNotes/folder_struct.tex
- doc/version.py
- doc/version.tex
- meson.build
- src/Utilities/version.f90
- version.txt
* set up for minor patch
* reinitialize release notes
> refactor(version): set next version to 6.4.1

- doc/ReleaseNotes/ReleaseNotes.tex
- src/Model/ModelUtilities/BoundaryPackage.f90
ReleaseNotes.tex included with this PR starts with the version forthcoming in #1099 
Fixes #1098 
Ran fprettify
> fix(BoundaryPackage): bnd_store_user_cond function already uses reduced node number

- .github/workflows/release.yml
- distribution/check_dist.py
- distribution/utils.py
- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/v6.4.1.tex
Final fixes and updates to the release workflow preceding 6.4.1
* fix develop/release mode conditional in `release.yml`
* add tests for develop/release mode in `check_dist.py`
* update release date in release notes to December 9
> fix(distribution): misc

- README.md
* add latest release badge
* remove badge for removed nightly build workflow
* expand description of release/branching strategy
* mention `code.json` in Nightly Builds section
> docs(readme): misc

- src/Model/GroundWaterTransport/gwt1sft1.f90
Hopefully helps with variable naming consistency in SFT
> fix(sft): clean-up some minor typos in SFT

- src/Utilities/Memory/MemoryManager.f90
fix(MemoryManager): fixes
* set MemoryType reallocated array pointer in reallocate_charstr1d
* get_isize should return -1 when variable not found
> fix(MemoryManager): reallocate_charstr1d and get_isize fixes

- autotest/conftest.py
- autotest/simulation.py
- autotest/test_gwf_csub_sk01.py
- autotest/test_gwf_pertim.py
- autotest/test_z01_testmodels_mf6.py
- autotest/test_z02_testmodels_mf5to6.py
- autotest/test_z03_examples.py
- src/mf6core.f90
* Add autotest for fix (test_gwf_pertim.py)
* Run black on autotest subdirectory.
* Close #1133
> fix(pertim): modify Mf6Run in mf6core.f90 to accept pertim = 0

- msvs/mf6core.vfproj
to have it working when building release mode / x64
> fix(msvs): add preprocess for SolutionFactory.F90

- DEVELOPER.md
- mention `ifx` incompatibility
- remove leftover sentence stub
- warn that tests may be skipped if model repos aren't found
> docs: fix minor issues and add some details to dev docs

- autotest/test_par_gwf03.py
- src/Distributed/Mapper.f90
- src/Distributed/VirtualBase.f90
- src/Distributed/VirtualDataContainer.f90
- src/Distributed/VirtualExchange.f90
- src/Distributed/VirtualGwfModel.f90
- src/Distributed/VirtualGwtExchange.f90
- src/Distributed/VirtualGwtModel.f90
- src/Distributed/VirtualModel.f90
- src/Model/Connection/DistributedVariable.f90
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/GwtGwtConnection.f90
- src/Model/Connection/SpatialModelConnection.f90
- src/Model/GroundWaterFlow/gwf3.f90
- src/RunControl.f90
- src/SimulationCreate.f90
- src/Solution/LinearMethods/ImsLinearSolver.f90
- src/Solution/LinearSolverBase.f90
- src/Solution/NumericalSolution.f90
- src/Solution/PETSc/PetscConvergence.F90
- src/Solution/PETSc/PetscSolver.F90
- src/Solution/ParallelSolution.f90
- src/Utilities/CharString.f90
- src/Utilities/SimStages.f90
- src/Utilities/SimVariables.f90
- src/mf6core.f90
where GWT in parallel is not functional yet
> feat(par): add load balancing for gwf and gwt

- doc/ReleaseNotes/v6.5.0.tex
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/NumericalModel.f90
- src/Solution/NumericalSolution.f90
Also modify order of model_ptcchk so that it is not called if 
NO_PTC ALL or NO_PTC FIRST option are specified.
> fix(ptc): fix ptc residual calculation

- autotest/test_gwf_ifmod_idomain.py
- autotest/test_gwf_ifmod_newton.py
- autotest/test_gwf_ifmod_rewet.py
- autotest/test_gwf_ifmod_vert.py
- autotest/test_par_gwf_idomain.py
- autotest/test_par_gwf_newton.py
- src/Model/GroundWaterFlow/gwf3.f90
- src/Model/NumericalModel.f90
- src/Solution/LinearMethods/ImsLinearSolver.f90
- src/Solution/LinearSolverBase.f90
- src/Solution/NumericalSolution.f90
- src/Solution/PETSc/PetscSolver.F90
- src/Solution/ParallelSolution.f90
- src/Utilities/Matrix/MatrixBase.f90
- src/Utilities/Matrix/PetscMatrix.F90
- src/Utilities/Matrix/SparseMatrix.f90
- src/Utilities/Vector/PetscVector.F90
- src/Utilities/Vector/SeqVector.f90
- src/Utilities/Vector/VectorBase.f90
- add calculation of (global) residual to solution instead of model ptc
- extend matrix and vector functionalities to do so
> rfct(par): add parallel ptc

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/large.yml
- .github/workflows/release.yml
> ci: switch provision-with-micromamba to setup-micromamba

- .github/dependabot.yml
We are quite happy with it at https://github.com/Deltares/Ribasim.
After this is merged you will get pull requests like this one: https://github.com/Deltares/Ribasim/pull/220
> Use dependabot to update github actions

- src/Distributed/VirtualDataManager.f90
- src/Distributed/VirtualModel.f90
- src/Distributed/VirtualSolution.f90
- src/Model/Connection/GwfGwfConnection.f90
- src/Model/Connection/SpatialModelConnection.f90
- src/Solution/NumericalSolution.f90
- validate connection parallel-proof (activated again)
- clean up circ. dep. with VirtualSolution
> rfct(par): validation of connections parallel-proof

- .github/workflows/release.yml
- distribution/check_dist.py
also fix one of the tests for distribution contents
> ci: set execute permission before building docs

- autotest/simulation.py
- autotest/test_par_gwf01.py
- autotest/test_par_gwf02.py
- autotest/test_par_gwf_ims_csv.py
- meson.build
- src/Solution/NumericalSolution.f90
- src/Utilities/InputOutput.f90
- src/mf6core.f90
* add function to append processor id to file names (`append_processor_id()`)
* update mf6core to use `append_processor_id()` to append processor id to `mfsim.lst`
* add test for inner and outer solver csv output
> fix(imscsv): fix issue with csv solver output in parallel

- .build_rtd_docs/requirements.rtd.txt
* same fix as https://github.com/modflowpy/flopy/pull/1900
> docs: constrain sphinx and sphinx-rtd-theme versions

- autotest/test_gwf_vsc01.py
- doc/ReleaseNotes/develop.tex
- src/Model/GroundWaterFlow/gwf3vsc8.f90
> fix(gwf3vsc8.f90): fix for the text header in the vsc package's binary output file

- src/Distributed/VirtualDataManager.f90
* Prior to this change, it was not possible to add a new type of numerical model and have the simulation complete unless the new model also had a corresponding virtual data container
* This fix allows the program to run to completion if a new model type does not yet have a virtual data container
> fix(VirtualDataManager): allow new model to work without virtual support

- autotest/pytest.ini
* c.f. https://github.com/modflowpy/flopy/pull/1967
* easier on the eyes
> ci: enable colorful pytest output

- .github/workflows/ci.yml
- .github/workflows/docs.yml
Same motivation as https://github.com/modflowpy/flopy/pull/1987
> ci: remove branch filters from push trigger

- src/Model/GroundWaterFlow/gwf3chd8.f90
- PR addresses a comment @mjreno left here: https://github.com/MODFLOW-USGS/modflow6/pull/1413#discussion_r1380567761
- Updated docstrings
- Ran fprettify
> fix(gwf3chd8.f90): account for auxiliary multiplier value in IDM modifications to CHD

- autotest/TestDevFeature.f90
- autotest/TestInputOutput.f90
- autotest/TestSim.f90
- autotest/meson.build
- autotest/tester.f90
* exploratory unit testing for a few standalone utilities
* some work originally here was moved to separate branches
* tests for linked list
* approximate floating point equality tests/potential refactor
> test: add minimal unit tests for some utilities

- src/Exchange/GwfGwtExchange.f90
> fix(GwfGwtExchange): check node counts before comparison

- doc/mf6io/mf6ivar/dfn/gwt-mwt.dfn
> fix(gwt-mwt.dfn): typo

- doc/mf6io/mf6ivar/dfn/gwt-lkt.dfn
> fix(gwt-lkt.dfn): typo

- src/Model/ExplicitModel.f90
- src/Solution/ExplicitSolution.f90
* follow up to #1161 
* add `ibound` and `filename` to `ExplicitModelType` (broad relevance)
* add `set_idsoln()` routine (consistent with numerical model)
* fix docstrings in explicit model and explicit solution
* remove unneeded returns
> refactor(ExplicitModel): add shared members

- autotest/TestMathUtil.f90
- src/Utilities/MathUtil.f90
* moved ~~unaltered~~ from / used by PRT ternary solution for DISV grids
* modified style (removed gotos, explicit local variables)
* unit tested briefly
> feat(MathUtil): add root-finding functions

- autotest/build_exes.py
- autotest/build_mfio_tex.py
- autotest/conftest.py
- autotest/cross_section_functions.py
- autotest/framework.py
- autotest/get_exes.py
- autotest/test_examples.py
- autotest/test_gwf_henry_nr.py
- autotest/test_gwf_obs01.py
- autotest/test_gwf_ts_lak01.py
- autotest/test_largetestmodels.py
- autotest/test_testmodels_mf5to6.py
- autotest/test_testmodels_mf6.py
- autotest/update_flopy.py
* ongoing refactor building on
* #1520 
* #1512 
* #1464
* better htol/rclose handling
* remove unused utilities from `conftest.py`
* remove outdated version exclusions from external model tests &mdash; most recent was 6.4.1, regression tests only compare with latest release
> test: refactor test framework (continued)

- autotest/framework.py
* remove unused `pdtol` property
* use `traceback.format_exc()` for full trace instead of printing exceptions
* cleanup htol adjustment
> test(framework): remove unused pdtol, use traceback.format_exc

- autotest/framework.py
* framework now supports multiple simulations under test but `xfail` applied to all of them &mdash; support an independent success/failure expectation per registered simulation or model
* attach simulation/model logs to framework so tests can check their contents
* accommodate missing comparison model namfile (for future mp7 support)
> test(framework): support per-sim/model xfail, attach logs

- autotest/framework.py
* remove util function for resolving executable paths
* previously framework could test an erroneous mf6
* locate programs explicitly, don't discover on the PATH
* require all target binaries to be registered with framework
> test(framework): fix binary selection, require known targets

- src/Model/ModelUtilities/Connections.f90
> chore(connections.f90): cleanup docstrings in connections class

- autotest/TestHashTable.f90
- autotest/meson.build
- autotest/tester.f90
- src/Utilities/HashTable.f90
- src/Utilities/TimeSeries/TimeSeriesManager.f90
* consistent naming for routines, variables
* use compact format for docstrings, update some language
* add minimal unit test
> refactor(HashTable): update naming, docstrings, format

- src/Utilities/SmoothingFunctions.f90
> style(smoothing): doxygenate smoothing function source

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/develop.tex
Update release notes in preparation for 6.4.3 release
> docs(release): prepare release notes for 6.4.3 release

- autotest/test_par_gwf_disu.py
- src/Distributed/VirtualModel.f90
- src/Exchange/DisConnExchange.f90
- src/Exchange/GwfGwfExchange.f90
- src/Exchange/GwtGwtExchange.f90
- src/Model/Connection/GridConnection.f90
and
- add test for print_input in exchange
- add test for parallel disu coupling
> fix(par): bug with print_input in exchange

- environment.yml
* fix nightly build full distribution test [failures](https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/7634684509/job/20800005044#step:14:2747)
> refactor(dependencies): use devtools develop version in environment.yml

- .github/workflows/release.yml
* followup to https://github.com/MODFLOW-USGS/modflow6/pull/1573
* https://github.com/MODFLOW-USGS/modflow6-nightly-build/actions/runs/7649076783
> ci(release): don't exclude utils/**/pymake from dist

- src/Utilities/Idm/IdmLoad.f90
when multiple exchanges are loaded that connect to the same remote model, NCELLDIM was deallocated for the first and then allocated for the next. mem_deallocate does not remove the entry from the memory list though. Setting a pointer at a later stage then always points to the first entry (which has been set to null at deallocation) simply because it is first in the list. 
This relates to the general idea that our memory manager is not set up for managing 'temporary' items like NCELLDIM. Something that we should probably discuss in more detail.
> fix(idm): loading of exchanges with remote models (parallel case)

- DEVELOPER.md
* suggest Chocolatey and winlibs mingw distributions
* mention conda mingw distribution's incompatibility
* motivated by #1609
> docs(DEVELOPER.md): update Windows compiler install recommendations

- .github/workflows/release_dispatch.yml
* reset PR step was removed from release procedure, remove mention of it
> ci(release): fix wording in release PR description

- autotest/framework.py
- autotest/test_examples.py
- autotest/test_largetestmodels.py
- autotest/test_testmodels_mf5to6.py
- autotest/test_testmodels_mf6.py
* move setup logic into external model repo tests
* simplify framework state mgmt
> test(framework): remove setup() method

- autotest/framework.py
* unused outside the framework
* simplifies use pattern to create and `run()`
> test(framework): make functions private (rename with leading _)

- autotest/test_swf_dfw.py
- autotest/test_swf_dfw_bowl.py
- doc/mf6io/mf6ivar/dfn/swf-dfw.dfn
- src/Model/GroundWaterEnergy/gwe.f90
- src/Model/GroundWaterFlow/gwf.f90
- src/Model/GroundWaterTransport/gwt.f90
- src/Model/NumericalModel.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
- src/Model/SurfaceWaterFlow/swf-flw.f90
- src/Model/SurfaceWaterFlow/swf-obs.f90
- src/Model/SurfaceWaterFlow/swf-oc.f90
- src/Model/SurfaceWaterFlow/swf-sto.f90
- src/Model/SurfaceWaterFlow/swf.f90
- src/Model/TransportModel/tsp.f90
> refactor(swf): minor cleanup

- DEVELOPER.md
* update DEVELOPER.md so that meson setup command can be copied separately for Linux/MacOS and Windows
> docs: update DEVELOPER.md

- autotest/test_gwf_sfr_inactive.py
- doc/ReleaseNotes/develop.tex
* add description of the bug fixed by PR #1633
* extend test_gwf_sfr_inactive autotest to reactive sfr reaches after inactivating 3 of 6 reaches
> docs: update release notes

- autotest/test_gwf_lakobs02.py
- src/Model/GroundWaterFlow/gwf-lak.f90
* in cases with multiple outlets in a lake the outlet observation used the incorrect index when evaluating the package ibound
* added test that compares outlet observations to known values
> fix(lak): fix issue with outlet observations

- autotest/test_gwegwe_exchng_with_comp2gwt.py
- autotest/test_par_gwe_comp2gwt.py
- src/Distributed/MpiMessageBuilder.f90
- src/Distributed/VirtualGweModel.f90
- src/SimulationCreate.f90
These minor changes should enable the first working version of GWE parallel, thanks to the great work by @mjr-deltares!
> feat(par/gwe): minor changes to get GWE parallel up and running

- autotest/test_prt_budget.py
- autotest/test_prt_disv1.py
- autotest/test_prt_exg.py
- autotest/test_prt_fmi.py
- autotest/test_prt_notebooks.py
- autotest/test_prt_release_timing.py
- autotest/test_prt_stop_zones.py
- autotest/test_prt_track_events.py
- autotest/test_prt_weak_sinks.py
* workaround for netcdf flopy branch not yet having PRT utils (needs rebase)
* unblock mf6 netcdf work for @mjreno
> test(PRT): move import statements into check fns

- src/Model/SurfaceWaterFlow/swf-disl.f90
* does not account yet for IDOMAIN
* CHD package checks head against disbase%bot so this needed to be updated
> fix(disl): copy disl%reach_bottom into disbase%bot

- .github/workflows/ci.yml
- autotest/test_gwe_split_analyt.py
- New autotest based on `test_gwe_esl_analyt_sln.py`, splits the 1D domain into two 1D domains
- An important difference with `test_gwe_esl_analyt_sln.py` is that `xorgin` must be specified or solution will return negative temperatures
- black
> test(gwe): New autotest for GWE that will facilitate additional parallel testing of GWE

- .github/common/update_fortran_style.py
* support recursively reformatting a whole directory at once
* more accurate/descriptive docstrings
> ci: support dir path in fortran style script

- autotest/test_gwe_split_analyt.py
- autotest/test_par_gwe_comp2carslaw_jaeg.py
- autotest/test_par_gwe_split_analyt.py
- Doubling up on the number of autotests for parallel GWE with this second contribution
- Runs 3 parallelized tests that compare stitched-together temperatures to analytical solutions described in Carslaw & Jaeger (1947) 
- This test leverages new test introduced in #1659
- Adopts the same approach to parallel testing used in #1656 
- Ran black
> test(par/gwe): second autotest for parallel gwe

- .github/workflows/release.yml
- .github/workflows/release_dispatch.yml
* until refactored and better tested
* [test run](https://github.com/wpbonelli/modflow6/actions/runs/8573666908/job/23500111452)
> ci(release): restore pre-pixi release workflows

- pixi.lock
The last attempt apparently didn't work
> Update pixi.lock file

- autotest/test_gwf_ats_lak01.py
* test works in mf6 CI but not in flopy CI
* allocate budget array instead
> fix(test): numpy resize not reliable in test_gwf_ats_lak01.py

- autotest/test_prt_ternary_methods.py
- autotest/test_prt_triangle.py
https://github.com/modflowpy/flopy/pull/2154#issuecomment-2057548390
> test(prt): remove bad flopy usages from triangle and ternary tests

- autotest/test_swf_dfw.py
- autotest/test_swf_dfw_beg2022.py
- autotest/test_swf_dfw_gwf.py
- autotest/test_swf_dfw_loop.py
- autotest/test_swf_vcatch.py
- src/Model/Discretization/Dis2d.f90
- src/Model/Discretization/Disv1d.f90
* fix a bug
* update test to load the binary grid file
* use consistent naming in binary grid file
* Close #1737 
tests may fail until [corresponding flopy change](https://github.com/modflowpy/flopy/pull/2157) has been implemented
> fix(grb): fix binary grid output

- src/Distributed/MpiRunControl.F90
- src/Distributed/MpiWorld.f90
- src/Exchange/exg-gwfgwf.f90
- src/Model/Connection/GwfGwfConnection.f90
- src/Utilities/ErrorUtil.f90
- no GNC when parallel
- 'gently' mpi abort instead of stop
should close #1733
> fix(par): GNC is not supported in parallel

- autotest/test_par_gwf04.py
- src/Distributed/InterfaceMap.f90
- src/Distributed/MpiRouter.f90
- src/Distributed/MpiRunControl.F90
- src/Distributed/RouterBase.f90
- src/Distributed/VirtualDataContainer.f90
- src/Distributed/VirtualDataManager.f90
- src/Model/Connection/SpatialModelConnection.f90
- src/RunControl.f90
- src/Utilities/ArrayHandlers.f90
> fix(par): XT3D on exchange no longer hangs simulation

- .codespell.ignore
- src/Exchange/exg-gwegwe.f90
- src/Exchange/exg-gwfgwf.f90
- src/Exchange/exg-gwtgwt.f90
- src/Exchange/exg-swfgwf.f90
- src/Model/GroundWaterFlow/gwf-csub.f90
- src/Model/GroundWaterFlow/gwf-lak.f90
- src/Model/GroundWaterFlow/gwf-maw.f90
- src/Model/GroundWaterFlow/gwf-npf.f90
- src/Model/GroundWaterFlow/gwf-obs.f90
- src/Model/GroundWaterFlow/gwf-uzf.f90
- src/Model/ParticleTracking/prt-obs.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
- src/Model/SurfaceWaterFlow/swf-obs.f90
- src/Model/TransportModel/tsp-apt.f90
- src/Model/TransportModel/tsp-obs.f90
- src/Solution/LinearMethods/ImsLinearBase.f90
- src/Utilities/Observation/Obs.f90
* words removed - blak, thck, numer, strng, htmp
* added thckstrt
> refactor(codespell): modify codespell ignore words

- DEVELOPER.md
Fixed a broken link in DEVELOPER.md
> docs: fix broken url in developer.md

- autotest/test_testmodels_mf6.py
* https://github.com/modflowpy/flopy/issues/2053
* https://github.com/modflowpy/flopy/issues/2145
* needs https://github.com/MODFLOW-USGS/modflow6-testmodels/pull/12
> test(modflow6-testmodels): reinstate excluded models

- autotest/TestMathUtil.f90
- src/Model/SurfaceWaterFlow/swf-cdb.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
- src/Model/SurfaceWaterFlow/swf-sto.f90
- src/Model/SurfaceWaterFlow/swf-zdg.f90
- src/Utilities/Constants.f90
- src/Utilities/MathUtil.f90
* calculate jacobian based on C.T. Kelley method
* refactor flow area calculation to be consistent with conductance calculation
> feat(swf): implement proper perturbation for jacobian calculation

- .github/common/msvs_vfproj_check.py
- utils/mf5to6/msvs/mf5to6.vfproj
- utils/zonebudget/msvs/zonebudget.vfproj
MSVS files for mf5to6 and zonebudget were out of date, update them and include them in the validation script we run in CI
> fix(msvs): update mf5to6/zbud6 msvs files, include in validation script

- src/Model/ModelUtilities/TrackData.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
* previously corresponded to mp7 'terminated for unknown reason'
> refactor(prt): define istatus=9, subcell with no exit face

- autotest/TestMathUtil.f90
- autotest/test_prt_ternary_methods.py
- doc/mf6io/mf6ivar/dfn/prt-mip.dfn
- src/Solution/ParticleTracker/TernarySolveTrack.f90
- src/Utilities/MathUtil.f90
* remove test method root function from `MathUtil`
* limit zeromethod options to 1 brent, 2 chandrupatla in ternary solution
* cleanup, use named constants
> refactor(prt): remove euler and test methods from ternary soln

- autotest/TestGeomUtil.f90
- src/Utilities/GeomUtil.f90
* vertices in clockwise (default) or ccw order
* for use by PRT
> feat(geomutil): add polygon area routine

- src/Exchange/exg-gwfgwt.f90
- src/Model/GroundWaterFlow/gwf-buy.f90
- suppress BUY message for interface model
- add safety check to avoid bound exception in comparison
> fix(par): suppress BUY message for interface models

- src/Solution/SolutionGroup.f90
- Came across some more old style docstrings while looking for something else.  Cleaning 'em up.
- fprettify
> chore(SolutionGroup.f90): cleanup docstrings in SolutionGroup class

- src/Solution/ParticleTracker/Method.f90
- src/Solution/ParticleTracker/MethodCellPassToBot.f90
- src/Solution/ParticleTracker/MethodCellPollock.f90
- src/Solution/ParticleTracker/MethodCellPollockQuad.f90
- src/Solution/ParticleTracker/MethodCellPool.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodDis.f90
- src/Solution/ParticleTracker/MethodDisv.f90
- src/Solution/ParticleTracker/MethodPool.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
- src/Solution/ParticleTracker/MethodSubcellPool.f90
- src/Solution/ParticleTracker/MethodSubcellTernary.f90
* factor out routines for cleaner `MethodDisType` and `MethodDisvType`
* optimize cell definition load: merge loops when setting cell faceflows
* rename `destroy()` -> `deallocate()` in method types
* misc cleanup, improve docstrings
> refactor(prt): cleanup, refactoring, optimization in dis/disv methods

- autotest/test_prt_disv1.py
- autotest/test_prt_notebooks.py
- autotest/test_prt_release_timing.py
- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
- src/Model/ParticleTracking/prt-prp.f90
- src/Model/ParticleTracking/prt.f90
Package logging wasn't connected to `iprpak` in base type, wire it up. Also idm mempath was used where it should not be. And add some tests
> fix(prt-prp): fix particle release point package logging

- doc/mf6io/mf6ivar/dfn/gwf-evta.dfn
- doc/mf6io/mf6ivar/dfn/gwf-rcha.dfn
- doc/mf6io/mf6ivar/dfn/utl-spca.dfn
- doc/mf6io/mf6ivar/dfn/utl-spta.dfn
> docs(readasarrays): minor clarification

- autotest/test_gwt_adv02_gwtgwt.py
- autotest/test_par_gwt_adv02.py
- src/Exchange/exg-gwfgwt.f90
fix matching of connection/interface models between GWF and GWT by imposing stricter conditions.
This closes #1811.
> fix(gwtgwt): improved matching of GWF flows to GWT interfaces

- doc/MODFLOW6References.bib
- doc/SuppTechInfo/Tables/mf6enhancements.tex
- doc/SuppTechInfo/body.tex
- doc/SuppTechInfo/groundwater-energy-model.tex
- doc/SuppTechInfo/mf6suptechinfo.bbl
- New GWE chapter will appear as chapter 10
- A couple of minor clean-ups remain, but ready for review
> doc(supptechinfo): Update with new GWE chapter

- doc/mf6io/body.tex
- doc/mf6io/framework/binaryoutput.tex
- doc/mf6io/mf6output.tex
- doc/mf6io/mf6switches.tex
- doc/mf6io/prt/prt.tex
Add sections describing particle track binary and CSV output files
> docs(prt): describe particle track output, misc revisions

- autotest/pytest.ini
- autotest/test_largetestmodels.py
these tests can be selected by file, there is no need for a marker
> test: remove unneeded marker

- autotest/test_prt_disv1.py
- autotest/test_swf_dfw.py
- autotest/test_swf_dfw_beg2022.py
- autotest/test_swf_dfw_bowl.py
- autotest/test_swf_dfw_gwf.py
- autotest/test_swf_dfw_swrt2.py
- autotest/test_swf_dfw_swrt2b.py
- autotest/test_swf_dfw_swrt2dis.py
- autotest/test_swf_vcatch.py
Mark some tests that need to be skipped in release mode
> test: mark tests with developmode

- src/Model/TransportModel/tsp-fmi.f90
- src/Model/TransportModel/tsp-ssm.f90
- minor stuff, including typos and removal of unneeded lines in `tsp-fmi.f90` and `tsp-ssm.f90`
- fprettify
> chore(tsp): minor code cleanups

- .github/workflows/docs.yml
* only allow one concurrent workflow run per branch
> ci: add concurrency group to docs.yml

- .github/PULL_REQUEST_TEMPLATE.md
add reminder to run black on new and/or modified autotests
> ci(pr-template): modify pr template

- .vscode/build_vscode.py
- .vscode/run_python.cmd
- .vscode/run_python.sh
- .vscode/tasks.json
- pixi.toml
* rearrange pixi.toml tasks an add builddir function
> refactor: add pixi support to vscode tasks

- .build_rtd_docs/conf.py
- .build_rtd_docs/dev.rst
- .github/workflows/docs.yml
> docs(rtd): upload accidentally omitted dirs

- src/Model/SurfaceWaterFlow/swf-zdg.f90
The zero-depth-gradient (ZDG) boundary was written using a conductance-based formulation, though that is not necessary because of the newton formulation used for the surface water flow model.  In this PR, the ZDG formulation was changed to use a simple flow calculation based on the product of conveyance and the square root of the slope.  
> refactor(swf-zdg): clean up flow calculation

- src/Model/GroundWaterFlow/gwf-csub.f90
Fix minor memory leak in csub. This is a continuation of PR #1935
Replace this paragraph with a written description of the pull request.  Include images and files as necessary to help with the documentation.  Descriptions for trivial and minor pull requests should be brief.
> fix(csub): fix minor memory leak in csub

- src/Distributed/VirtualDataManager.f90
- src/Distributed/VirtualModel.f90
> fix(mem): address memory leaks

- src/Solution/PETSc/PetscConvergence.F90
- src/Solution/PETSc/PetscSolver.F90
- also marked this, and petsc preconditioning, as development feature (so no update to release notes)
> feat(par): add convergence check based on petsc L2 norm

- doc/mf6io/prt/namefile.tex
> docs(prt): indicate that multiple PRPs are allowed

- doc/ReleaseNotes/previous/v0.9.01.tex
- doc/ReleaseNotes/previous/v0.9.02.tex
- doc/ReleaseNotes/previous/v0.9.03.tex
- doc/ReleaseNotes/previous/v6.0.0.tex
- doc/ReleaseNotes/previous/v6.0.1.tex
- doc/ReleaseNotes/previous/v6.0.2.tex
- doc/ReleaseNotes/previous/v6.0.3.tex
- doc/ReleaseNotes/previous/v6.0.4.tex
- doc/ReleaseNotes/previous/v6.1.0.tex
- doc/ReleaseNotes/previous/v6.1.1.tex
- doc/ReleaseNotes/previous/v6.2.0.tex
- doc/ReleaseNotes/previous/v6.2.1.tex
- doc/ReleaseNotes/previous/v6.2.2.tex
- doc/ReleaseNotes/previous/v6.3.0.tex
- doc/ReleaseNotes/previous/v6.4.0.tex
- doc/ReleaseNotes/previous/v6.4.1.tex
- doc/ReleaseNotes/previous/v6.4.2.tex
- doc/ReleaseNotes/previous/v6.4.3.tex
- doc/ReleaseNotes/previous/v6.4.4.tex
- doc/ReleaseNotes/previous/v6.5.0.tex
> doc: standardize previous version changes

- .github/actions/build-netcdf-win/action.yml
Update curl invocation in the windows build NetCDF action, which has been failing in the nightly build.
> ci(netcdf): update curl command in windows build action

- src/Utilities/Export/DisNCMesh.f90
- src/Utilities/Export/DisNCStructured.f90
- src/Utilities/Export/DisvNCMesh.f90
- src/Utilities/Export/MeshNCModel.f90
- src/Utilities/Export/ModelExport.f90
- src/Utilities/Export/NCExportCreate.f90
- src/Utilities/Export/NCModel.f90
- src/Utilities/Idm/BoundInputContext.f90
- src/Utilities/Idm/DefinitionSelect.f90
- src/Utilities/Idm/DynamicPackageParams.f90
- src/Utilities/Idm/IdmLoad.f90
- src/Utilities/Idm/IdmLogger.f90
- src/Utilities/Idm/InputLoadType.f90
- src/Utilities/Idm/ModelPackageInputs.f90
- src/Utilities/Idm/ModflowInput.f90
- src/Utilities/Idm/SourceCommon.f90
- src/Utilities/Idm/SourceLoad.F90
- src/Utilities/Idm/mf6blockfile/IdmMf6File.f90
- src/Utilities/Idm/mf6blockfile/LoadMf6File.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileGridInput.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileListInput.f90
- src/Utilities/Idm/mf6blockfile/Mf6FileStoInput.f90
- src/Utilities/Idm/mf6blockfile/StructArray.f90
- src/Utilities/Idm/mf6blockfile/StructVector.f90
- src/Utilities/Idm/netcdf/NCArrayReader.f90
- src/Utilities/Idm/netcdf/NCContextBuild.f90
- src/Utilities/Idm/netcdf/NCFileVars.f90
- src/Utilities/Idm/netcdf/NetCDFCommon.f90
Follow on to #2039.  Bring IDM in line with style guide.
> style(idm):  align with style guide

- meson.build
strictly cosmetic tweaks: fc_id -> compiler ID, follow meson format where message is 'attribute: value'
___
> chore(meson): clarify build configuration messages

- autotest/test_chf_dfw_loop.py
- doc/mf6io/swf/disv1d.tex
- doc/mf6io/swf/swf.tex
- src/Model/GroundWaterFlow/gwf-buy.f90
- src/Model/SurfaceWaterFlow/swf-cdb.f90
- src/Model/SurfaceWaterFlow/swf-cxs.f90
- src/Model/SurfaceWaterFlow/swf-dfw.f90
- src/Model/SurfaceWaterFlow/swf-flw.f90
- src/Model/SurfaceWaterFlow/swf-ic.f90
- src/Model/SurfaceWaterFlow/swf-obs.f90
- src/Model/SurfaceWaterFlow/swf-oc.f90
- src/Model/SurfaceWaterFlow/swf-sto.f90
- src/Model/SurfaceWaterFlow/swf-zdg.f90
- src/Model/SurfaceWaterFlow/swf.f90
- src/Utilities/Idm/mf6blockfile/StructArray.f90
Minor cleanup on the surface water modeling code.
> refactor(swf): minor swf cleanup

- autotest/test_gwf_libmf6_evt01.py
- autotest/test_gwf_libmf6_ghb01.py
- autotest/test_gwf_libmf6_ifmod01.py
- autotest/test_gwf_libmf6_ifmod02.py
- autotest/test_gwf_libmf6_ifmod03.py
- autotest/test_gwf_libmf6_rch01.py
- autotest/test_gwf_libmf6_rch02.py
- autotest/test_gwf_libmf6_riv01.py
- autotest/test_gwf_libmf6_riv02.py
- autotest/test_gwf_libmf6_sto01.py
- autotest/test_libmf6_api.py
- autotest/test_prt_libmf6_budget.py
- src/Utilities/Idm/mf6blockfile/StructVector.f90
- srcbmi/mf6xmi.F90
This is following the findings in the PR on xmipy: https://github.com/Deltares/xmipy/pull/138
> ci(api): add autotest to test API routines (e.g. get_version)

- doc/ReleaseNotes/develop.tex
Mention #1993 / #1996 in the release notes
___
> docs(releasenotes): mention arm mac string -> char array conversion issue

- .vscode/build_vscode.py
> fix(vscode): small change to build extended instead of parallel by default

- .github/workflows/release.yml
update ubuntu version for release binaries
> ci(ubuntu): update to 22.04 in build binaries for release

- .github/workflows/ci.yml
We previously only tested the example models on Linux. We have recently seen some platform-specific behavior differences in whose consideration it seems wise to test all platforms.
___
> ci: test example models on all platforms

- autotest/prt_test_utils.py
The utility function only supported unstructured grids
> test(prt): support structured grids in plot util function

- doc/mf6io/mf6ivar/dfn/prt-prp.dfn
> docs(prp): include last keyword in releasesetting

- .github/workflows/compilers.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
v3 is deprecated and has started to fail
> ci: update upload-/download-artifact actions

- .github/workflows/ci.yml
- .github/workflows/compilers.yml
- .github/workflows/docs.yml
follow the [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md)
> ci: update deploy-pages version

- doc/mf6io/mf6ivar/dfn/utl-ats.dfn
Correct error in ATS dtadj description
> doc(ats): correct error in dtadj description

- CONTRIBUTING.md
This PR updates the style guide link in `CONTRIBUTING.md`
> docs(styleguid): update style guide link

- doc/mf6io/prt/prp.tex
> docs(prt-prp): fix block order

- pixi.lock
Windows extended build still broken
> Revert "chore: update `pixi.lock` (#2193)"

- .github/workflows/compilers.yml
> ci: fix compiler compatibility check workflow

- src/Model/ParticleTracking/prt-fmi.f90
- src/Model/ParticleTracking/prt-mip.f90
- src/Solution/ParticleTracker/CellRectQuad.f90
- src/Solution/ParticleTracker/CellUtil.f90
- src/Solution/ParticleTracker/MethodCellTernary.f90
- src/Solution/ParticleTracker/MethodSubcellPollock.f90
- src/Solution/ParticleTracker/TernarySolveTrack.f90
Remove leading "-- " from comments per styleguide conventions
> style(prt): clean up comments

- distribution/benchmark.py
Expand the list of "generic names" to work with the wider set of scenario subdirectory names now in use in the examples repository. Some other miscellaneous cleanup. And temporarily skip backwards tracking PRT models until we have native support or some other solution for the head/budget reversal problem.
> ci(benchmarks): fix benchmark script

- doc/ReleaseNotes/ReleaseNotes.tex
- doc/ReleaseNotes/develop.tex
- doc/ReleaseNotes/vx.y.z-template.tex
Update release notes for new bugfix version.
> docs(release): update release notes for mf6.6.1

- doc/mf6io/gwe/ic.tex
- doc/mf6io/gwt/ic.tex
- doc/mf6io/mf6ivar/dfn/utl-ncf.dfn
NetCDF related documentation review fixes: #2205, #2208
> doc(mf6io): netcdf documentation fixes

- .github/actions/build-netcdf-win/action.yml
Remove not needed 7-zip action, not working after #2218. 
> fix(ci): remove 7-zip action

- .github/actions/build-netcdf-win/action.yml
- pixi.lock
- Address meson dependency resolution issue exposed by pixi update
- Update win-64 pixi environment
> fix(ci): update windows pixi environment 

- README.md
> doc(new refs): update list of reports and papers

- doc/ReleaseNotes/develop.toml
https://github.com/MODFLOW-ORG/modflow6-examples/pull/265
@cneyens let me know if the phrasing needs any tweaks. We add release notes for new example models, just FYI.
> docs: add release note for new GWE example

- autotest/pytest.ini
- autotest/test_largetestmodels.py
- autotest/test_testmodels_mf5to6.py
- autotest/test_testmodels_mf6.py
> test: use models api for mf5to6 tests

- autotest/test_largetestmodels.py
- autotest/test_testmodels_mf6.py
Followup to #2265, accommodating https://github.com/MODFLOW-ORG/modflow-devtools/pull/207
> test: update prefix for model lookups

- .build_rtd_docs/conf.py
- src/Solution/ParticleTracker/mf6_6_0_prt_migration_guide.md
Followup to #2287 in view of https://github.com/mgaitan/sphinxcontrib-mermaid/issues/175
> docs(rtd): fix myst config and unbracket mermaid fenced code blocks

- .build_rtd_docs/requirements.rtd.txt
Close but no cigar https://modflow6.readthedocs.io/en/latest/_migration/mf6_6_0_prt_migration_guide.html, I think this is it
> docs(rtd): add sphinxcontrib-mermaid to requirements.rtd.txt

- doc/MODFLOW6References.bib
- doc/ReleaseNotes/ReleaseNotes.tex
A few recent pubs to augment the release notes
> chore(ReleaseNotes): update bibliography for including new entries in release notes

- doc/ReleaseNotes/ReleaseNotes.tex
Small modification to the ReleaseNotes for the next micro release.
> doc(ReleaseNotes): clarify known issue message
